### ISSUE TITLE
Auth0 Won't Work with Windows Subsystem for Android

### ISSUE THREAD

**Issue by AuriR** [auth0/docs#10013]
### Description

Tested with a Xamarin.Forms + Xamarin.Android app using Windows Subsystem for Android, aka WSA.

The LoginAsync() method will not work in WSA. However, it works on a normal phone. My GUESS is this is due to no default browser in WSA.

Expected result:

A browser should appear to handle the login process.

Actual result:

The LoginAsync() function simply hangs. There is no error in logcat. I'm thinking this should have:

a) Some sort of timeout in the method, and
b) Some sanity check that a default browser is registered with the system, otherwise throw an error

### Reproduction

1. Install an app on WSA that uses Auth0 Oidc client for Android. In this case it was v3.2.4.
2. Add a button to a form or view with an event handler or command that calls LoginAsync().
3. Call to LoginAsync never launches a browser and never returns.

Then do the same on a "real" Android device:
1. Install an app on WSA that uses Auth0 Oidc client for Android. In this case it was v3.2.4.
2. Add a button to a form or view with an event handler or command that calls LoginAsync().
3. Call to LoginAsync properly launches browser to handle login process.

### Environment

Windows Subsystem for Android
Auth0.OidcCient.Android v3.2.4

**Comment by evansims** [comment]
Hi @AuriR 👋 Thanks for creating an issue. This doesn't appear to be a documentation issue so much as a bug report around a specific implementation. If you would, please create an issue about this in the appropriate GitHub repository for the SDK you're facing issues with. Thanks!

**Comment by AuriR** [comment]
You're right - this is the wrong place for it. Thanks!
