### ISSUE TITLE
Typos On Auth0 Documentation

### ISSUE THREAD

**Issue by mehreencs87** [auth0/docs#1001]
On [this page](https://auth0.com/how-it-works) at the bottom, all of the 
links (in blue) aren't preceded by a space, so you end up with 
statements like "Browse ourdocumentation to reach out...".
"flexible pricing plansto fit your needs" 
I guess whatever you've got in there that's adding links is forgetting some spacing.
Related to zendesk ticket 6048

**Comment by iannyanes** [comment]
Solved
