### ISSUE TITLE
Laravel 9 - Target class [Auth0\\Login\\Repository\\Auth0UserRepository] does not exist

### ISSUE THREAD

**Issue by abhishekjain-itsme-highpointe** [auth0/docs#10096]
I'm using:

PHP 8.0.1
Laravel 9.13.0
"auth0/login": "7.0",

After following getting issue of Target class [Auth0\\Login\\Repository\\Auth0UserRepository] does not exist

Below is my exact error when I am using API

`{"error":"Target class [Auth0\\Login\\Repository\\Auth0UserRepository] does not exist.","status":500}{"error":"Target class [Auth0\\Login\\Repository\\Auth0UserRepository] does not exist.","status":500}`

I already tried with the below solution but didn't work for Laravel 9

` $this->app->bind(
            '\Auth0\Login\Contract\Auth0UserRepository',
            '\Auth0\Login\Repository\Auth0UserRepository');`

**Comment by evansims** [comment]
Hi @abhishekjain-itsme-highpointe 👋 Happy to help. Please create issues around quickstarts at their respective repositories, in this case https://github.com/auth0-samples/auth0-laravel-php-web-app or https://github.com/auth0-samples/auth0-laravel-api-samples depending on your use case.

I think you might be referencing an old quickstart. We no longer use this `Auth0UserRepository` class or the `Auth0\Login` namespace.

Please start fresh with the new quickstart, available at the links above. Notice that a custom user repository is demonstrated at https://github.com/auth0-samples/auth0-laravel-php-web-app/blob/master/app/app/Auth/CustomUserRepository.php, and should be configured within your app here: https://github.com/auth0-samples/auth0-laravel-php-web-app/blob/d5a89ad986b07d49e97bf74f64befa92382c4c5d/app/config/auth.php#L82-L83.
