### ISSUE TITLE
IOS Touch ID Identity Providers documentation page is empty

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#102]
Clicking the link to IOS Touch ID in the Identity Providers supported by Auth0 page (https://auth0.com/docs/identityproviders) sends to an empty documentation page (https://auth0.com/docs/connections/passwordless/ios-touch)

![2015-06-07_1647](https://cloud.githubusercontent.com/assets/12707130/8025963/f79ed1b0-0d34-11e5-8285-a8a85e4c04f2.png)
![2015-06-07_1646](https://cloud.githubusercontent.com/assets/12707130/8025962/f79ded9a-0d34-11e5-8ef5-164b1390b5b3.png)

**Comment by ntotten** [comment]
This should link to: https://auth0.com/docs/connections/passwordless/ios-touch-id-swift

We need metadata to forward the md page to that page.

**Comment by mpaktiti** [comment]
Link goes to https://auth0.com/docs/connections/passwordless/ios-touch-id-swift
