### ISSUE TITLE
Links point to localhost 3000

### ISSUE THREAD

**Issue by antoniormrzz** [auth0/docs#10228]
### Description

Docs links pointing to localhost:3000.
![image](https://user-images.githubusercontent.com/45634189/220683820-43d249d5-a1f3-4fb9-a462-37d055a30e7d.png)
when I hover over the react sublink on second line and the Single-Page App sublink, the base url is pointing to localhost:3000.

### Reproduction

go to https://auth0.com/docs/search?q=react&page=1 and navigate over the sublink react under the second result.

**Comment by pclavier92** [comment]
Hi Antonio! Thanks for reporting this. Will proceed to close this issue as it has been already fixed.
