### ISSUE TITLE
Auth0-react failing silently on succesful login

### ISSUE THREAD

**Issue by sammbeller** [auth0/docs#10272]
### Description
As requested in [this community forum post](https://community.auth0.com/t/auth0-react-failing-silently-on-succesful-login/109142/3), `auth0-react` is failing silently on login.
> Clicking the login button succeeds - I can see Success Login events in my user’s history. But the Auth0Provider’s reducer still has `isAuthenticated` set to false and no user populated.

### Reproduction
My `Auth0ProviderWithHistory` is as follows:
```ts
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Auth0Provider, Auth0ProviderOptions } from '@auth0/auth0-react';

type Auth0ProviderWithHistoryProps = React.PropsWithChildren<{}>;

const Auth0ProviderWithHistory = (props: Auth0ProviderWithHistoryProps) => {
  const domain = process.env.REACT_APP_AUTH0_DOMAIN;
  if (!domain) {
    throw new Error("Could not get auth domain from env");
  }
  const clientId = process.env.REACT_APP_AUTH0_CLIENT_ID;
  if (!clientId) {
    throw new Error("Could not get auth client ID from env");
  }

  const navigate = useNavigate();

  const onRedirectCallback: Auth0ProviderOptions["onRedirectCallback"] = (appState) => {
    navigate(appState?.returnTo || window.location.pathname);
  };

  return (
    <Auth0Provider
      authorizationParams={{ redirect_uri: window.location.origin }}
      clientId={clientId}
      domain={domain}
      onRedirectCallback={onRedirectCallback}
    >
      {props.children}
    </Auth0Provider>
  );
};

export default Auth0ProviderWithHistory;
```
Login is implemented as described in the login tutorial [here](https://auth0.com/docs/quickstart/spa/react/01-login). Login fails every time as described above.

### Environment
- **Version of this library used:** `@auth0/auth0-react: ~2.0.2`
- **Version of the platform or framework used, if applicable:** `react: ^17.0.2`
- **Other relevant versions (language, server software, OS, browser):** 
  - node: v16.18.0
- **Other modules/plugins/libraries that might be involved:** none that I can think of

**Comment by evansims** [comment]
Please direct SDK-specific questions to the appropriate repository; https://github.com/auth0/auth0-react — or https://github.com/auth0-samples/auth0-react-samples is this is more relevant to the quickstart itself.

**Comment by tabismd933-ctrl** [comment]
I am very much happy
