### ISSUE TITLE
Documentation for Windows 8 (C#) doesn't load from Quick Start page for Open Dashboad

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#103]
When trying to load Windows 8 (C#) Documentation using the Quick Start link inside the https://manage.auth0.com page, the page doesn't load.

![2015-06-07_1655](https://cloud.githubusercontent.com/assets/12707130/8026074/ae5ccb7c-0d36-11e5-953d-ba0f6d78b790.png)

**Comment by ntotten** [comment]
Fixed.
