### ISSUE TITLE
[ Newbie Questions ] There is no back-end implementation when choosing SPA application?

### ISSUE THREAD

**Issue by anasouardini** [auth0/docs#10312]
This [docs page](https://auth0.com/docs/quickstart/spa/react/interactive) for adding authentication to an SPA is simple and effective but I don't see how this simple front-end implementation can grow to become an app with protected pages/routes etc!

I assume that there is some back-end lib for this that's not advertised properly??
Or maybe there is some public key that I can use in my API to confirm that the data sent by the client to the API is valid?

Thanks for consideration.

**Comment by evansims** [comment]
Hi @anasouardini 👋 Backend integration guidance is offered here: https://auth0.com/docs/quickstarts#backend
