### ISSUE TITLE
php api system requirements broken

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#1044]
As you can see it's broken
![image](https://cloud.githubusercontent.com/assets/1114365/13760664/f6f625f2-ea3c-11e5-8081-8bebbdce23a4.png)

**Comment by vmartynets** [comment]
despite https://github.com/auth0/docs/pull/1175 still don't fixed
![image](https://cloud.githubusercontent.com/assets/1114365/14601908/79660930-056d-11e6-9029-0e7aa082c9e9.png)

**Comment by mpaktiti** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/11715799/15097627/fa4265f0-1529-11e6-8a47-9b12dfb5c18e.png)
