### ISSUE TITLE
ASP.NET MVC 4 - Enterprise Providers ui

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#1051]
related to [this](https://auth0.com/docs/tutorials/aspnet-mvc4-enterprise-providers). UI of login is looks like UI of old version lock library.
![screenshot_11](https://cloud.githubusercontent.com/assets/1114365/13854071/6730dd58-ec72-11e5-8cc2-936dcbff1881.png)

**Comment by jerriep** [comment]
@Amialc @iannyanes I would like to understand where and how you got to this point. It seems to be simply and outdated version of lock.js right?

Did you get to here from one of the starter projects?

**Comment by vmartynets** [comment]
@jerriep well, i have followed by basic ASP.NET tutorial and then used [this tutorial](https://auth0.com/docs/tutorials/aspnet-mvc4-enterprise-providers).

**Comment by jerriep** [comment]
@Amialc Vlad, I am not sure how you got to that screen. As part of the basic ASP.NET tutorial, you will need to copy the code which the tutorial generate for you for the lock screen, right?

And that references lock.js 8.2:
![image](https://cloud.githubusercontent.com/assets/1006420/13932463/b6517160-ef6d-11e5-9f23-bcbb4ae24b73.png)

**Comment by vmartynets** [comment]
@jerriep 
I've got lock script included, but seems in using another script (see screenshot 2)
![image](https://cloud.githubusercontent.com/assets/1114365/13933696/2ea525dc-efb7-11e5-9758-a63d05ae56ce.png)

![image](https://cloud.githubusercontent.com/assets/1114365/13933688/256facb2-efb7-11e5-8bf2-8176b88996d2.png)

**Comment by jerriep** [comment]
@Amialc Well that is an even more recent version of the Lock library. The one you have in the screenshot is a very old version. I am not sure where it comes from....?

**Comment by vmartynets** [comment]
@jerriep [probably snippet in this step](https://auth0.com/docs/tutorials/aspnet-mvc4-enterprise-providers#3-add-the-provisioning-widget)

**Comment by jerriep** [comment]
In consutation with @ntotten we are removing this article:
https://github.com/auth0/docs/pull/1064

Will add a new generic (ie. non-platform specific) one:
https://trello.com/c/T1KSg0Bf/185-add-generic-document-explaining-enterprise-provisioning
