### ISSUE TITLE
ASP.NET MVC 4 - Enterprise Providers step title

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#1052]
Related to [this](https://auth0.com/docs/tutorials/aspnet-mvc4-enterprise-providers#4-a-modify-the-externallogincallback-method-in-accountcontroller-cs-as-follows-) tutorial. It extension of ASP.NET tutorial, but in ASP.NET tutorial there is no `accountcontroller.cs`
![image](https://cloud.githubusercontent.com/assets/1114365/13856020/e64e918a-ec7b-11e5-858b-504eeeb29e9b.png)

**Comment by jerriep** [comment]
In consutation with @ntotten we are removing this article:
https://github.com/auth0/docs/pull/1064

Will add a new generic (ie. non-platform specific) one:
https://trello.com/c/T1KSg0Bf/185-add-generic-document-explaining-enterprise-provisioning
