### ISSUE TITLE
Misleading information in API V2 docs

### ISSUE THREAD

**Issue by vikasjayaram** [auth0/docs#1073]
Api v2 email provider create, has misinformation. See attached information.
<img width="1274" alt="screen shot 2016-03-23 at 11 28 12 am" src="https://cloud.githubusercontent.com/assets/514093/13972379/580f5222-f0ec-11e5-9715-6bffdfa5a84a.png">

**Comment by mpaktiti** [comment]
Fixed https://github.com/auth0/api2/pull/1615
