### ISSUE TITLE
Link in lock customization page broken

### ISSUE THREAD

**Issue by yvonnewilson** [auth0/docs#1090]
https://auth0.com/docs/libraries/lock/customization#authparams-object-

In the authParams section - the link is broken for "Read here".  This should be a working link.
See screen shot.
<img width="778" alt="screen shot 2016-03-25 at 1 30 13 pm" src="https://cloud.githubusercontent.com/assets/9997803/14053333/bf592d2a-f28d-11e5-8d52-7617faebe0bc.png">

This is the page that link should point to
https://auth0.com/docs/libraries/lock/sending-authentication-parameters

**Comment by iannyanes** [comment]
Solved
