### ISSUE TITLE
Update Seed project to include Github SSO login

### ISSUE THREAD

**Issue by RussellBradley** [auth0/docs#110]
bug location - seed project for https://auth0.com/docs/quickstart/native-mobile/ios-objc/no-api

Users have the ability to sign up using Github SSO, the iOS seed project should allow users to login with their Github SSO login.

![sso-issues](https://cloud.githubusercontent.com/assets/2488791/8048236/2398f0b4-0e1d-11e5-86ac-13d8c84b1cbc.png)

![sso-ios](https://cloud.githubusercontent.com/assets/2488791/8048240/2b24a76a-0e1d-11e5-8a76-45ae777cffc1.png)

**Comment by iannyanes** [comment]
No t reproducible
