### ISSUE TITLE
Add api-auth doc reference to client grants APIv2 endpoint

### ISSUE THREAD

**Issue by rolodato** [auth0/docs#1103]
https://auth0.com/docs/api/v2#!/Client_Grants/get_client_grants

**Comment by mpaktiti** [comment]
Hey @rolodato, is it possible that you remember what you had in mind almost a year ago? :)

Sorry for the delay in addressing this. Could you have meant this one? https://auth0.com/docs/api-auth/config/using-the-management-api

**Comment by rolodato** [comment]
Good question :) Yes, I think I created this issue because we're missing a documentation link there that explains what a client grant is, how it should be created/used, etc. The link you referenced seems to be what we need.
