### ISSUE TITLE
Update Seed project to include live SSO login

### ISSUE THREAD

**Issue by RussellBradley** [auth0/docs#111]
bug location = seed project for https://auth0.com/docs/quickstart/native-mobile/ios-objc/no-api

Users have the ability to sign up using live SSO, the iOS seed project should allow users to login with their live SSO login.

![sso-issues](https://cloud.githubusercontent.com/assets/2488791/8048264/4e219f98-0e1d-11e5-8391-67b529d60a5a.png)

![sso-ios](https://cloud.githubusercontent.com/assets/2488791/8048265/50f19d4a-0e1d-11e5-9eb9-8a28bde35458.png)

**Comment by iannyanes** [comment]
Not reproducible
