### ISSUE TITLE
Tutorial should clarify to add "Twitter's Pod" to Podfile.

### ISSUE THREAD

**Issue by RussellBradley** [auth0/docs#112]
bug location - https://auth0.com/docs/quickstart/native-mobile/ios-objc/no-api

Although this is obvious, it's easier for a beginner if adding the twitter pod to the Podfile was clarified.

![podfile twitter](https://cloud.githubusercontent.com/assets/2488791/8048307/bd0dc53a-0e1d-11e5-8dc7-3d50a89adc7d.png)

**Comment by albertoperdomo** [comment]
No longer relevant. Closing.
