### ISSUE TITLE
Tutorial should clarify to add "Facebook Pod" to Podfile.

### ISSUE THREAD

**Issue by RussellBradley** [auth0/docs#113]
bug location = https://auth0.com/docs/quickstart/native-mobile/ios-objc/no-api

This should be clarified in the tutorial to add to the Podfile instead of generic language such as "Add facebook pod".

![podfile](https://cloud.githubusercontent.com/assets/2488791/8048342/051b9cf8-0e1e-11e5-9c11-ea9643a81b81.png)

**Comment by albertoperdomo** [comment]
No longer relevant. Closing.
