### ISSUE TITLE
SMS anchor links don't anchor link properly.

### ISSUE THREAD

**Issue by RussellBradley** [auth0/docs#114]
bug location - https://auth0.com/docs/quickstart/native-mobile/ios-objc/no-api

The SMS anchor link don't bring the user to the SMS anchor link, instead it brings the user to the top of another page.

![sms anchor link](https://cloud.githubusercontent.com/assets/2488791/8048360/453873ba-0e1e-11e5-9717-05797e4d31e8.png)

Should bring user here
![screenshot 2015-06-08 20 15 21](https://cloud.githubusercontent.com/assets/2488791/8048380/982e75a6-0e1e-11e5-857a-3f3d02f3e81a.png)

**Comment by iannyanes** [comment]
Fixed  https://auth0.com/docs/quickstart/native-mobile/ios-objc/no-api
