### ISSUE TITLE
all dependencies for iOS seed project are out of date

### ISSUE THREAD

**Issue by RussellBradley** [auth0/docs#116]
need to be updated to current latest version

Lock = 1.13.0
Facebook = 2.0.1
JWTDecode = 0.2.1
SimpleKeyChain = 0.4.0
MBProgress = 0.9.1

![dependencies](https://cloud.githubusercontent.com/assets/2488791/8048793/e48c1728-0e23-11e5-8604-7548da82bf77.png)

**Comment by hzalaz** [comment]
@RussellBradley @ntotten it will fetch the last minor/patch version (while keeping the major fixed)  because it's using `~>` for the version. The only issue is that we have the `Podfile.lock` but I tend to keep it up to date, otherwise a quick `pod update` fixes this locally

**Comment by ntotten** [comment]
@hzalaz a
