### ISSUE TITLE
Ionic 2 Tutorial - angular2-jwt version update

### ISSUE THREAD

**Issue by aguerere** [auth0/docs#1164]
The warning about using an older version of angular2-jwt is no longer valid, because Ionic 2 now ships with angular2@beta.13 and this is compatible with the latest angular2-jwt.

![ionic2-angular2-jwt-update](https://cloud.githubusercontent.com/assets/14084214/14516205/8a94a500-01ca-11e6-8992-5f839c224d2b.png)

**Comment by Annyv2** [comment]
This was fixed
