### ISSUE TITLE
Ionic 2 Tutorial - Ionic package rename

### ISSUE THREAD

**Issue by aguerere** [auth0/docs#1165]
The package name to reference modules has changed from 'ionic-framework/ionic' to 'ionic-angular'.
All occurrences must be updated.

![ionic2-ionic-angular-package-rename](https://cloud.githubusercontent.com/assets/14084214/14516287/47f66b42-01cb-11e6-9aee-563a9d65d665.png)
![ionic2-ionic-angular-correct-name](https://cloud.githubusercontent.com/assets/14084214/14516291/4cb2aa2e-01cb-11e6-9c9d-aefbefaabe9f.png)

**Comment by Annyv2** [comment]
This was fixed

**Comment by iannyanes** [comment]
This issue is not reproducible on the actual quickstart version
