### ISSUE TITLE
Ionic 2 Tutorial - Auth0Lock type no longer needed

### ISSUE THREAD

**Issue by aguerere** [auth0/docs#1166]
The declaration of the lock instance does no longer need to specify a type, in Step 4 of the tutorial.

![ionic2-auth0-lock-type-not-needed](https://cloud.githubusercontent.com/assets/14084214/14516395/3d9ab08a-01cc-11e6-9088-69c3172a74ad.png)
![ionic2-auth0lock-type](https://cloud.githubusercontent.com/assets/14084214/14516398/4363213c-01cc-11e6-914b-8cf780f4eb29.png)

**Comment by Annyv2** [comment]
This was fixed

**Comment by iannyanes** [comment]
This Issue is not reproducible on the actual version of the quickstart
