### ISSUE TITLE
Ionic 2 Tutorial - LocalStorage abstraction returns Promise

### ISSUE THREAD

**Issue by aguerere** [auth0/docs#1167]
Ionic 2 localStorage abstraction service now returns a Promise. All calls to retrieve values from localStorage should be handled properly.

![ionic2-localstorage-promise-1](https://cloud.githubusercontent.com/assets/14084214/14516504/7cf483f4-01cd-11e6-8e60-0d269e9e39ec.png)
![ionic2-localstorage-promise-1-fix](https://cloud.githubusercontent.com/assets/14084214/14516507/81a99c4a-01cd-11e6-9694-0204358df0f1.png)
![ionic2-localstorage-promise-2](https://cloud.githubusercontent.com/assets/14084214/14516511/86272472-01cd-11e6-8552-38bc5df820c1.png)
![ionic2-localstorage-promise-2-fix](https://cloud.githubusercontent.com/assets/14084214/14516516/8aad0b4c-01cd-11e6-8fed-47173285d69d.png)

**Comment by Annyv2** [comment]
This was fixed

**Comment by iannyanes** [comment]
Closing this issue - Not reproducible
