### ISSUE TITLE
Outdated Auth0.js tutorial

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#1169]
This tutorial https://auth0.com/docs/libraries/auth0js references auth0.js 6.7, but the latest one is 6.8

**Comment by mpaktiti** [comment]
Same thing for these also:
https://github.com/auth0/docs/tree/master/articles/custom-signup.md
https://github.com/auth0/docs/tree/master/articles/client-platforms/angular2.md
https://github.com/auth0/docs/tree/master/articles/client-platforms/aurelia.md
https://github.com/auth0/docs/tree/master/articles/client-platforms/vuejs.md
https://github.com/auth0/docs/tree/master/articles/native-platforms/ionic.md

**Comment by mpaktiti** [comment]
Assigned to TechAid: 3318

**Comment by mpaktiti** [comment]
Fixed by #2261
