### ISSUE TITLE
Auth0.js received feedback

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#1170]
We received a ticket in zendesk stating `If we don't want the "source" from git or the binaries with npm - where is the place on your site that points to the auth0-*.js existence? I couldn't find it except for querying auth0.login but then I would have to already know that exists. Just trying to let you know that it isn't easy to navigate finding it. I would have expected it alongside the "lock" widget versions in SDK area.`

Researching a little bit further in the docs page there's no direct reference to auth0.js 

Neither in any of these menus
![noreference](https://cloud.githubusercontent.com/assets/5016479/14534496/3ec2bf90-0233-11e6-8bbf-6e2b4228cec0.JPG)

nor here
![noreference2](https://cloud.githubusercontent.com/assets/5016479/14534497/40414eea-0233-11e6-8bea-f72328229440.JPG)

**Comment by mpaktiti** [comment]
Has been shipped https://github.com/auth0/docs/pull/2527
