### ISSUE TITLE
Broken link: Lock iOS, use your own UI

### ISSUE THREAD

**Issue by lobo** [auth0/docs#1189]
- Orange button at: https://auth0.com/docs/libraries/lock-ios/use-your-own-ui
- Repro steps: follow link, click in orange button.
- Ticket number: https://auth0.zendesk.com/agent/tickets/8370

**Comment by lobo** [comment]
@Annyv2 the downloaded file is corrupted, is this fixed or not yet? Thanks!

**Comment by Annyv2** [comment]
@lobo Oh, sorry. There's a typo, I'll fix it
