### ISSUE TITLE
Target Auth0\Login\Contract\Auth0UserRepository is not instantiable

### ISSUE THREAD

**Issue by albertojm** [auth0/docs#1210]
I'm using:

PHP 7
Laravel 5.2
auth/auth 3.0

After following https://auth0.com/docs/quickstart/hybrid/ionic/php-laravel i get

Target [Auth0\Login\Contract\Auth0UserRepository] is not instantiable while building [Auth0\Login\Middleware\Auth0JWTMiddleware].

**Comment by shane-kerwin** [comment]
Having the same issue. Any fix?

**Comment by shane-kerwin** [comment]
I changed this:

```
    public function register()
    {
        $this->app->bind(
            'Illuminate\Contracts\Auth\Registrar',
            'GiggRigg\Services\Registrar',
            '\Auth0\Login\Contract\Auth0UserRepository',
            '\Auth0\Login\Repository\Auth0UserRepository');
    }
```

to this:

```
    public function register()
    {
        $this->app->bind(
            'Illuminate\Contracts\Auth\Registrar',
            'GiggRigg\Services\Registrar');

        $this->app->bind(
            '\Auth0\Login\Contract\Auth0UserRepository',
            '\Auth0\Login\Repository\Auth0UserRepository');
    }
```

Fixed for me.

**Comment by iannyanes** [comment]
Thanks for the information @michaelshane 

Did it work for you @albertojm ?

**Comment by mpaktiti** [comment]
Assigned to TechAid.

**Comment by vmartynets** [comment]
Tested with PHP 7.0.9, laravel 5.3.6, auth0-php 3.4.3, all works fine without fixing anything.

**Comment by mpaktiti** [comment]
Hi @albertojm , we will close this issue since we cannot reproduce it. If you are still facing issues fell free to reopen it. Thanks! 👍

**Comment by Hesesses** [comment]
I'm using Laravel 5.4 and having the same issue

Following this tutorial: https://auth0.com/docs/quickstart/backend/php-laravel

**Comment by ghost** [comment]
I'm using Laravel 5.4 too, and i fixed it:

add this to the head of AppServiceProvider
```
use Auth0\Login\Contract\Auth0UserRepository as Auth0UserRepositoryContract; 
use Auth0\Login\Repository\Auth0UserRepository as Auth0UserRepository;
````
and change the code in register function
```
public function register()
    {
        $this->app->bind(
            Auth0UserRepositoryContract::class,
            Auth0UserRepository::class
        );
    }
````

**Comment by mpaktiti** [comment]
cc @chenkie

**Comment by taha-azzabi** [comment]
I have the same problem in Laravel 5.4,

**Comment by anis1011** [comment]
thanks @g0su ,it works for me 
but my lock widget didn't open ,it keep on loading but didn't open please help

**Comment by juanvillegas** [comment]
I would say it's time for Auth0 to upgrade their Laravel docs. As it is now, the guide doesn't work for Laravel 5.4/5.5...
