### ISSUE TITLE
Ionic Tutorial - Troubleshooting warning no longer required

### ISSUE THREAD

**Issue by aguerere** [auth0/docs#1211]
The troubleshooting warning about errors from Lock when using `ionic serve` or `Ionic View` is no longer necessary since it does work fine with the current Lock version.

![ionic-ionic_serve-ionic_view](https://cloud.githubusercontent.com/assets/14084214/14663999/663b473e-0690-11e6-98ed-f8f73f4d3dea.png)

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/1626
