### ISSUE TITLE
Enhancement Request - subscribe option on changelog

### ISSUE THREAD

**Issue by yvonnewilson** [auth0/docs#1227]
Enhancement request - add a subscribe option (such as email notification) to the 
auth0.com/changelog page so that customers get noticed pushed to them about changes instead
of having to remember to check the page.

Customer request cross reference: 8506

**Comment by mpaktiti** [comment]
@ntotten Can you take a look at this request? Should I add this to trello or move it to another repo (or something else)?

**Comment by mpaktiti** [comment]
Hello @yvonnewilson, if this is still a valid request please follow up with the website team. Thank you.
