### ISSUE TITLE
SocketIO no-api tutorial is incomplete and code base is outdated

### ISSUE THREAD

**Issue by javlc** [auth0/docs#125]
Link to SocketIO tutorial page: https://auth0.com/docs/quickstart/spa/socket-io/no-api

DESCRIPTION
Tutorial is incomplete, does not contain taylored content to user's account (clientSecret, tokens, etc). Such data is not included in sample code.
The seed project is missing, instead there is a link to a working sample in a github repo, which in turn contains outdated information, and probably incomplete/outdated dependencies.
When running `npm install` on the package.json file while using nodejs v. 0.12, a long set of error messages were displayed when building the dependencies.

**Comment by iannyanes** [comment]
Issue fixed. New Socket.io seed project and tutorial was made.
