### ISSUE TITLE
iOS Swift - Lock-Twitter pod does not install

### ISSUE THREAD

**Issue by aguerere** [auth0/docs#1268]
When I try to add Lock-Twitter to my project, i get an issue where dependencies between Lock and Lock-Twitter step on each other.

![ios-swift-twitter-pod-dependency](https://cloud.githubusercontent.com/assets/14084214/14973040/49550e2c-10b1-11e6-9308-27dc0ee4d7aa.png)

**Comment by mpaktiti** [comment]
Assigned to TechAid.

**Comment by albertoperdomo** [comment]
No longer relevant. Closing.
