### ISSUE TITLE
iOS Swift - Lock issue with Facebook web login

### ISSUE THREAD

**Issue by aguerere** [auth0/docs#1269]
When I enable Facebook connection for my auth0 app, then try to login using Facebook via Lock through the web view (no Lock-Facebook or Facebook app available) I get the following from Facebook:

![ios-swift-facebook-simulator-050216](https://cloud.githubusercontent.com/assets/14084214/14973079/a83c7ae2-10b1-11e6-9d72-82e430e8fd74.png)

**Comment by mpaktiti** [comment]
Assigned to TechAid.

**Comment by albertoperdomo** [comment]
No longer relevant (lock not used). Closing.
