### ISSUE TITLE
Auth0 python tutorial issues - consolidated in one.

### ISSUE THREAD

**Issue by javlc** [auth0/docs#129]
**TUTORIAL LINK**
https://auth0.com/docs/quickstart/webapp/python

**TEST CASES**
Has downloadable seed project? PASS
Has tutorial with steps? PASS
Does the tutorial have the user-customized API keys already set and configured? PASS
Do all the the links in the tutorial redirect to their intended webpages? PASS
Does the downloaded seed project have its customized contents according to the tutorial? FAULT
Are the auth0 library versions in tutorial the most up to date at the time of testing? FAULT

**OBSERVATIONS** (Need to be addressed/fixed)
1.  The file in seed project `requirements.txt` contains an extra reference to python library `dotenv` (all three references are: flask, dotenv, requests). Currently, the tutorial only indicates two references: flask & requests. There is no mention in tutorial about dotenv library nor what it does, nor a link, etc.
2.  Auth0 lock library version in tutorial is 7.1. The most up to date version at the time of testing is: 7.5.
3.  (Python seed project README has some outdated instructions) The README.md file in the seed project talks to the user about creating the .env file that contains the API keys, when in fact this file along its contents are already created with customized values for the user. 
4.  The Auth0 Callback Handler code in tutorial is not the same code that has been included in the seed project. Particularly noticeable is the addition of imports from dotenv
   SUGGESTION: Having the tutorial code be the same as the one in the seed project will greatly enhance the user's ability to implement a custom Auth0 implementation in their existing, new project.
5.  The seed project contains a script reference to https://cdn.auth0.com/w2/auth0-widget-5.js , however, the tutorial code does not include this reference anywhere.

**Comment by iannyanes** [comment]
Issues Fixed
