### ISSUE TITLE
api/v2/user-search link broken

### ISSUE THREAD

**Issue by MrPrashantT** [auth0/docs#1300]
https://auth0.com/docs/api/v2/user-search is broken. 

There are links to this from the Dashboard: https://manage.auth0.com/#/users
It is the link at the end of "To perform your search, press enter. For more information about Lucene syntax, please read our docs."

Related ticket: https://auth0.zendesk.com/agent/tickets/9457

**Comment by mpaktiti** [comment]
The [link](https://auth0.com/docs/api/management/v2/user-search) works now so we will close this issue.

Thanks @MrPrashantT !
