### ISSUE TITLE
WPF and Winforms Tutorial links to deprecated version of login widget

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#131]
Step 3 of WPF and Winforms Tutorial (https://auth0.com/docs/quickstart/native-mobile/wpf-winforms/) links to deprecated version of login widget:
https://auth0.com/docs/libraries/login-widget2
It should be using the newer "Lock" version.

![2015-06-12_2122](https://cloud.githubusercontent.com/assets/12707130/8142450/cd4ffadc-114a-11e5-8086-76f8bf65af70.png)

![2015-06-12_2125](https://cloud.githubusercontent.com/assets/12707130/8142449/cd4f3bba-114a-11e5-836c-c1e9a5f359cf.png)

**Comment by iannyanes** [comment]
Issue Fixed
