### ISSUE TITLE
bulk user imports

### ISSUE THREAD

**Issue by peterromfeldhk** [auth0/docs#1327]
Following this guide:
https://auth0.com/docs/bulk-import

and trying it out here:
https://auth0.com/docs/api/management/v2#!/Jobs/post_users_imports

always results in

```
RESPONSE CODE

400
RESPONSE BODY

{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Payload validation error: 'String does not match pattern ^con_[A-Za-z0-9]{16}$' on property connection_id",
  "errorCode": "invalid_body"
}
RESPONSE HEADERS

{
  "Content-Type": "application/json; charset=utf-8",
  "cache-control": "no-cache"
}
```

also the `get curl command` doesn't work

The api is also painful! it requires me to write max 10MB files and then listen for verification emails, parse them and retry...

**Comment by peterromfeldhk** [comment]
ok figured that i need the connection_id which is in the url when clicking on the connection and it works,
also that there is a get-jobs api to verify the job status.

The `show curl command` still doesnt work.
Also would be nice to have these things in the guide or docs

**Comment by manujrastogi** [comment]
I think Auth0 should explicitly tell users to user con_XXXXXXXXXX connection_id otherwise users will go mad as i did .But thanks peterromfeldhk for the solution.

**Comment by pamsilva** [comment]
But the `show curl command` still doesn't work!! and that's annoying.

**Comment by mpaktiti** [comment]
Hey @pamsilva @peterromfeldhk @manujrastogi I logged an issue with engineering to fix the `show curl command`, thanks for reporting this 👍 

I also added a clarification on the doc about `connection_id` and how to retrieve it https://github.com/auth0/docs/pull/4654
