### ISSUE TITLE
Broken link on Laravel Tutorial

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#137]
In the introduction of the Laravel Tutorial the link to the example application is broken.

![2015-06-14_1510_001](https://cloud.githubusercontent.com/assets/12707130/8150047/355ce4ce-12a8-11e5-9a44-af7eb2171a7e.png)
![2015-06-14_1510](https://cloud.githubusercontent.com/assets/12707130/8150048/355f4868-12a8-11e5-9be9-c8c4597db7f2.png)

**Comment by iannyanes** [comment]
Issue solved. https://auth0.com/docs/quickstart/webapp/laravel
