### ISSUE TITLE
Broken link: iOS Swift sample apps

### ISSUE THREAD

**Issue by lobo** [auth0/docs#1407]
Where it says:
- "Also you can check our Swift(broken link) and Objective-C(broken link)
  example apps. For more information on how to use Lock with Swift please check this guide"
- https://github.com/auth0/docs/blob/master/articles/libraries/lock-ios/index.md

**Comment by mpaktiti** [comment]
Hi @lobo ! Looks like these links have been replaced by "See the Swift and Objective-C example apps." which works, so I will close this issue. Thanks!
