### ISSUE TITLE
Deprecated method in iOS tutorial

### ISSUE THREAD

**Issue by lobo** [auth0/docs#1410]
- Here: https://github.com/auth0/docs/blob/master/articles/libraries/lock-ios/index.md
- `auth0APIToken` - is a deprecated method 
  Some explanation from Lock source code:

``` js
/**
*  Block that returns a signed JWT with `create:users` scope for API v2. It's required to send SMS code.
*  For more info: https://api.auth0.com/docs/api/v2
*  @deprecated 1.14.0. Lock now use `/passwordless/start` endpoint instead of API v2.
*/
@property (copy, nonatomic) NSString *(^auth0APIToken)() DEPRECATED_MSG_ATTRIBUTE("a API v2 JWT is no longer necessary");
```

**Comment by mpaktiti** [comment]
Hello @lobo ! I can't find this method in the doc. The only reference I can find is [this](https://github.com/auth0/docs/blob/69fbc0a178ae0f961d3a26997b0889b4d4e6c180/articles/libraries/lock-ios/sms-lock-ios.md) but that's not on master branch.

Can you clarify this issue a bit? Thanks!

**Comment by lobo** [comment]
@mpaktiti I'll be closing this issue, given that's been fixed on July 18th (after posting this issue). Thanks for bringing it up! Issue closed.
