### ISSUE TITLE
No need in NoOP lambda

### ISSUE THREAD

**Issue by 0rion7st** [auth0/docs#1413]
https://auth0.com/docs/integrations/aws-api-gateway/part-1

> One more AWS Lambda function is required that does nothing. This is needed by the OPTIONS method for CORS as described in the next step. Repeat the steps for creating a Lambda function and name it

Instead of creating new lambda, developer can rather create OPTIONS method in Gateway API with MOCK enabled.

**Comment by khorne3** [comment]
Completed with most recent update to the AWS tutorial.
