### ISSUE TITLE
Add step to social connection facebook tutorial to make logout to work

### ISSUE THREAD

**Issue by ntotten** [auth0/docs#1437]
As Phrasant commented here: https://ask.auth0.com/t/how-to-get-facebook-logout-redirect-working/2678 and reviewing our tutorial, we need to add an extra step to the [facebook tutorial](https://auth0.com/docs/connections/social/facebook) for the cases where the developer wants to logout from auth0 and facebook as well. Between 4 and 5 could be a good position for it, we could include a link to the logout docs: https://auth0.com/docs/logout

That step needs to explain to the user the need to create a Web Platform and set their `https://YOUR_NAMESPACE/` as Site URL.

<img width="1179" alt="step 4-5" src="https://cloud.githubusercontent.com/assets/1424663/15788085/f0a71df0-29c5-11e6-8228-35f5757831c9.png">

Notice images are out of date in that tutorial as well.

This has been found investigating this other issue: https://github.com/auth0/auth0-server/issues/773

**Comment by Catografix** [comment]
Is Site URL https:// or http:// ??

**Comment by ntotten** [comment]
https

**Comment by Catografix** [comment]
@ziluvatar These are all new screenshots from yesterday. 
What do you see that looks out of date?

**Comment by ziluvatar** [comment]
I meant some facebook images from https://auth0.com/docs/connections/social/facebook 
I followed that tutorial without any problem anyway. Don't worry too much about that sentence.
