### ISSUE TITLE
Broken link: Metadata in Rules - node-auth0 SDK

### ISSUE THREAD

**Issue by iuliiazhelem** [auth0/docs#1460]
Where it says:
- "Updating

All rules have available an auth0 object (which is an instance of the node-auth0 SDK (broken link) that can use API v2) which is pre-configured with permissions to update users."
- https://github.com/auth0/docs/blob/master/articles/rules/metadata-in-rules.md

**Comment by mpaktiti** [comment]
Fix deployed.
