### ISSUE TITLE
Broken link: Passwordless Touch Id 

### ISSUE THREAD

**Issue by iuliiazhelem** [auth0/docs#1467]
Where it says:
-    "NOTE: A sample application is available in the Lock.iOS-OSX repository on GitHub (broken link)"
-     https://github.com/auth0/docs/blob/master/articles/connections/passwordless/_using-lock-ios-touchid.md

**Comment by mpaktiti** [comment]
Hi @iuliiazhelem ! Thank you for reporting this issue.

The examples have been removed from the repo, so we will remove this note from the doc. Since there is [another issue](https://github.com/auth0/docs/issues/1696) about this, we will close this one as duplicate.
