### ISSUE TITLE
Broken link: Passwordless Touch Id

### ISSUE THREAD

**Issue by iuliiazhelem** [auth0/docs#1468]
Where it says:
- "NOTE: The Lock.iOS-OSX repository on GitHub (broken link) shows in detail how this same flow was used to build the UI of the Lock.iOS. You can use this as an example to build your own UI for Touch ID authentication."
-     https://github.com/auth0/docs/blob/master/articles/connections/passwordless/_using-lock-ios-touchid.md

**Comment by mpaktiti** [comment]
Hi @iuliiazhelem ! Thank you for reporting this issue. 

The folder has been removed from the repo so we will update our docs accordingly.

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/2115
