### ISSUE TITLE
Deprecated method in iOS tutorial

### ISSUE THREAD

**Issue by iuliiazhelem** [auth0/docs#1471]
- Here: https://github.com/auth0/docs/blob/master/articles/connections/passwordless/_touchid-configure-component-objc.md
- Here: https://github.com/auth0/docs/blob/master/articles/connections/passwordless/_touchid-configure-component-swift.md
- registerPublicKey - deprecated method
- removePublicKeyOfDevice - deprecated method

**Comment by jeffreylees** [comment]
https://auth0.com/docs/connections/passwordless/ios-touch-id-swift
https://auth0.com/docs/connections/passwordless/ios-touch-id-objc

Hi! Both of these docs pages are now marked as legacy. These solutions are deprecated at this point, but we're leaving the documentation in place to allow older implementations to find help where needed. Once we have an official replacement for these solutions, we'll replace them, and the issue you've raised here about the use of deprecated methods should be resolved as a result.

This feature is disabled for all new tenants as of June 8th 2017, and any tenant created after that date won't have the necessary legacy grant types to even use Touch ID at all -- just some older tenants will still be able to use it until they can be converted to a replacement.

Thanks for the input and sorry that this issue sat open for so long!
