### ISSUE TITLE
Broken link: Custom Social Extensions

### ISSUE THREAD

**Issue by iuliiazhelem** [auth0/docs#1478]
Where it says:
-  "You can use any of the Auth0 standard mechanisms to login a user with the new connection (e.g. direct links, Auth0 Lock(broken link), auth0.js(broken link), etc.). "
- "Note that Lock will not automatically show a button for the custom connection. If you want to add a button, see this instructions (broken link)."
- https://github.com/auth0/docs/blob/master/articles/extensions/custom-social-extensions.md

**Comment by mpaktiti** [comment]
Hello @iuliiazhelem 
All the aforementioned links work from the live document https://auth0.com/docs/extensions/custom-social-extensions
