### ISSUE TITLE
confusing docs

### ISSUE THREAD

**Issue by jeacott1** [auth0/docs#1490]
isn't this wrong in the react docs? (and in the go-jwt blog example and probably elsewhere).
the idToken can never be updated with this code unless you delete the localstorage token elsewhere, and that never happens in the docs or examples. 

why wouldn't you want to replace the local token with the hash if it exists?

```
 getIdToken: function() {
    var idToken = localStorage.getItem('userToken');
    var authHash = this.lock.parseHash(window.location.hash);
    if (!idToken && authHash) {
      if (authHash.id_token) {
        idToken = authHash.id_token
        localStorage.setItem('userToken', authHash.id_token);
      }
...

```

**Comment by chenkie** [comment]
@jeacott1 closing this as we have new tutorials now: https://auth0.com/docs/quickstart/spa/react

Please let us know if there is still an issue :)
