### ISSUE TITLE
Apache tutorial specifies wrong module name in command to run

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#152]
Step 1 of the Apache Web App tutorial says to run the following command to enable the auth-openidc module for Apache; sudo a2enmod mod_auth_openidc. The command fails because the name of the module that it's installed is auth_openidc, without the "mod_" at the beginning.

![2015-06-23_0023](https://cloud.githubusercontent.com/assets/12707130/8298957/a72e3e76-193e-11e5-80b5-13ac039e5264.png)

**Comment by iannyanes** [comment]
Issue fixed  https://auth0.com/docs/quickstart/webapp/apache
