### ISSUE TITLE
java seed project download error

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#1520]
when you try to download java web app seed project it comes with error:
![image](https://cloud.githubusercontent.com/assets/1114365/16048977/b43d04d2-325e-11e6-8f99-a250f2951b10.png)

**Comment by vmartynets** [comment]
https://github.com/auth0/docs/issues/1523 duplicate

**Comment by mpaktiti** [comment]
The docs and samples have been updated https://auth0.com/docs/quickstart/webapp/java
