### ISSUE TITLE
Update docs for Fitbit

### ISSUE THREAD

**Issue by ziluvatar** [auth0/docs#1521]
**This has to be deployed when this issue gets released https://github.com/auth0/manage/issues/2034**

Fitbit deprecated time ago its oauth1 apps. Currently we are developing the integration of their OAuth2 authentication api.

We will need to update https://auth0.com/docs/connections/social/fitbit to tell the users [about the deprecation](https://community.fitbit.com/t5/Web-API/OAuth-1-0a-removal-update/m-p/1272107#U1272107) and how to configure the new OAuth2 app.

New OAuth2 details in their devsite: https://dev.fitbit.com/docs/oauth2/

In dashboard it will look like this for new connections:

<img width="597" alt="screen shot 2016-06-22 at 7 11 45 pm" src="https://cloud.githubusercontent.com/assets/1424663/16276129/62747004-38ad-11e6-98c2-bc589c22089a.png">

Root issue: https://github.com/auth0/auth0-server/issues/2295

**Comment by jeffreylees** [comment]
https://github.com/auth0/docs/pull/1602

Should just be lacking a couple of screenshots that can be acquired after the release.

**Comment by mpaktiti** [comment]
@ziluvatar @jeffreylees Hey guys, the doc looks ok to me, can I close this issue?

**Comment by jeffreylees** [comment]
@mpaktiti yes, this can be closed
