### ISSUE TITLE
Broken Java seed project download

### ISSUE THREAD

**Issue by jgelsey** [auth0/docs#1523]
https://auth0.com/docs/server-apis/java-spring-security "Get Seed Project" results in error `{"cause":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/tmp/githubdownload116514-17892-fr3cf3/auth0-spring-security-api-master/examples/auth0-spring-security-api-sample/src/main/resources/auth0.properties"},"isOperational":true,"errno":-2,"code":"ENOENT","syscall":"open","path":"/tmp/githubdownload116514-17892-fr3cf3/auth0-spring-security-api-master/examples/auth0-spring-security-api-sample/src/main/resources/auth0.properties"}`

**Comment by arcseldon** [comment]
@jgelsey - thanks for raising this. We are currently publishing updates to quick starts (including linking to a new github account - `auth0-samples`) and associated docs - part of our expansion to support servlet / spring mvc / spring mvc + spring security / and spring api + spring security. Yesterday, all the libraries were released to Maven, and the samples are updated and published on github too. The quick starts and documentation tutorials are the final piece that is still WIP.

**Comment by mpaktiti** [comment]
The docs and samples have been updated https://auth0.com/docs/quickstart/backend/java-spring-security
