### ISSUE TITLE
symfony api tutorial different styles

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#1528]
As you can see, step one looks differently from dashboard and documentation pages
![image](https://cloud.githubusercontent.com/assets/1114365/16055118/bbe13f86-3278-11e6-86e7-57a27e14a90f.png)

**Comment by mpaktiti** [comment]
Confirmed. Issue to be moved to `manage` repo.

**Comment by mpaktiti** [comment]
From what I can see now they look mostly the same. There are some issues at the dashboard quickstarts that have already been reported to the team and they will be addressed shortly.

Thanks for reporting this @Amialc . If you can find other major differences please reopen this issue or create a new one.
