### ISSUE TITLE
User impersonation: Unable to switch programming language in code examples

### ISSUE THREAD

**Issue by iuliiazhelem** [auth0/docs#1531]
https://github.com/auth0/docs/blob/master/articles/user-profile/user-impersonation.md

There are several code examples on page with ability to switch programming languages - buttons with languages name, but they do not work properly: all buttons change languages only for first code example

**Comment by mpaktiti** [comment]
Hi @iuliiazhelem ! All the snippets seem to be working now on [this doc](https://auth0.com/docs/user-profile/user-impersonation) so I'm going to close this ticket. Thank you!
