### ISSUE TITLE
Apache tutorial's mod_auth_openidc module breaks Apache config file

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#155]
Apache server will not start after enabling auth_openidc module.

(Server was running fine without the module)

![2015-06-23_2355](https://cloud.githubusercontent.com/assets/12707130/8322519/9172815c-1a04-11e5-874d-c3d25f43fb26.png)

(After installing and enabling the module, the server will not run)
![2015-06-23_2359](https://cloud.githubusercontent.com/assets/12707130/8322520/91752f38-1a04-11e5-90fa-5185b5d53966.png)

(When disabling the module, server will go back online again)
![2015-06-24_0005](https://cloud.githubusercontent.com/assets/12707130/8322540/d543128e-1a04-11e5-8642-dddae76bde0a.png)

**Comment by zandbelt** [comment]
probably after the fact but: that points to a situation where a module that is compiled for Apache 2.2 is loaded in to an Apache 2.4 server
