### ISSUE TITLE
Wrong Seed Path

### ISSUE THREAD

**Issue by mehreencs87** [auth0/docs#1657]
[https://github.com/auth0/docs/blob/master/articles/server-platforms/servicestack/01-login.md#servicestack-tutorial](url)
![wrongpath](https://cloud.githubusercontent.com/assets/14890513/16449959/c1916248-3e13-11e6-93eb-4918f81ae1e6.JPG)

**Comment by mehreencs87** [comment]
fix #1456

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/2045
