### ISSUE TITLE
Broken link to Passwordless Touch ID Example

### ISSUE THREAD

**Issue by vikasjayaram** [auth0/docs#1696]
The link in https://auth0.com/docs/connections/passwordless/ios-touch-id-swift to a example touch id sample `NOTE: A sample application is available in the Lock.iOS-OSX repository on GitHub.`  is broken.

**Comment by mpaktiti** [comment]
Examples have been deleted from repo. We will remove this note.

Thank you @vikasjayaram !

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/2115
