### ISSUE TITLE
Changing a User's Password documentation missing API PATCH

### ISSUE THREAD

**Issue by Blackbaud-JonathanBell** [auth0/docs#1747]
The documentation for [Changing a User's Password](https://auth0.com/docs/connections/database/password-change) says there are 3 ways to change a users password:
- API to send reset email
- Lock to send reset email
- Dashboard - admin to manually change password through Auth0 dashboard.

The management API to [Update a user](https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id) supports supplying a new password for the user.   This seems like a legitimate approach for applications to use if they do not wish to redirect to the Auth0 password reset page, which doesn't allow you to configure the domain of the page.  That can be a problem in white-labeling the experience.

Given that this seems to be a legitimate approach to handling password resets, it seems misleading for this article to omit it, implying that those are the only 3 ways to change a user's password.

**Comment by mpaktiti** [comment]
Hello @Blackbaud-JonathanBell ! We updated our [documentation](https://auth0.com/docs/connections/database/password-change#using-the-management-api) to include the Management API. Thank you! 👍 

PR: https://github.com/auth0/docs/pull/2204
