### ISSUE TITLE
AWS API Setup does not match with AWS Portal

### ISSUE THREAD

**Issue by ntotten** [auth0/docs#179]
This doc is not updated since there is a new step asking for the role type.

https://auth0.com/docs/aws-api-setup it should be based on http://docs.aws.amazon.com/IAM/latest/UserGuide/roles-creatingrole-identityprovider.html

also, the steps are wrong numbered

**Comment by ntotten** [comment]
@Catografix I believe you already fixed this, if so please close this bug.

**Comment by Catografix** [comment]
@ntotten No, I haven't worked on this doc before. I will make these changes.

**Comment by Catografix** [comment]
@ntotten What is the correct Role Type for this example? Im guessing Role for Identity Provider Access >> Grant API access to SAML providers.

**Comment by Catografix** [comment]
![aws-api-setup-6a](https://cloud.githubusercontent.com/assets/12396567/11108256/55196130-88b3-11e5-9f49-8e6ac3df32ef.png)

**Comment by Catografix** [comment]
@ntotten Looks like you now have to create the custom policy **before** creating the role. I will add these steps.

**Comment by Catografix** [comment]
New PR #712
