### ISSUE TITLE
Typo in Angular Single Page App Quickstart

### ISSUE THREAD

**Issue by iannyanes** [auth0/docs#1790]
In the tutorial https://auth0.com/docs/quickstart/spa/angularjs

IN the following paragraph https://auth0.com/docs/quickstart/spa/angularjs#seed-samples

It says:

" ... Angular app can server as a starting point"

It should say "Angular app that can server as a starting point"

![image](https://cloud.githubusercontent.com/assets/2512171/16846633/d3b33776-49b2-11e6-9aee-5a4c7b0bd861.png)

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/1791
