### ISSUE TITLE
Documentation should be clear about what Auth0 Lock version it applies to

### ISSUE THREAD

**Issue by seanmangar** [auth0/docs#1873]
The documentation should be clear about which version it applies to. I ran into many issues trying to figure out how to customize the options for Auth0 Lock v10 due to breaking changes (e.g dict which is now language and languageDictionary). 
https://auth0.com/docs/libraries/lock/customization#dict-string-object-

**Comment by jeffreylees** [comment]
@mpaktiti this can be closed, lock library docs are now v10 by default, since v10 is released, and all contain a header warning about version changes.
