### ISSUE TITLE
Lock 10 problem for my app and how to solve it?!?! 

### ISSUE THREAD

**Issue by hughred22** [auth0/docs#1887]
This new tutorial (the ionic 2 update with the Lock 10) makes my app not working correctly anymore. First, the login() function do not return as promise. Which my app is waiting for the resolve to setRoot to a different page than login page. It is not gonna work on this new tutorial. Also I can not dynamic set the connections and closeable with this.lock.show({options}). The lock.show ignore all the options and I can not set the display of lock dynamically anymore. My situation is, before popup the Lock, I let user pick what kind of user they are , then show related SSO login depend the value they choose. PLEASE HELP! As I am going to launch my app and this change in code make my life again misable :(

**Comment by mpaktiti** [comment]
@jeffreylees Hey, can you have a look into this?

**Comment by jeffreylees** [comment]
@hughred22 
The newest version of Lock just released - 10.2.0 - includes the ability to override a short subset of options in `show()`. https://github.com/auth0/lock#showoptions - that might help with your second problem. Did you get your Ionic 2 / Lock 10 working?

**Comment by mpaktiti** [comment]
Hello @hughred22 ! Are you still facing issues? Can you check out Jeffrey's recommendation?

**Comment by mpaktiti** [comment]
Hello @hughred22 ! I'm going to close this issue but please feel free to contact us again if you are still having issues with your implementation. Thanks! 👍
