### ISSUE TITLE
unclear which fields are unique

### ISSUE THREAD

**Issue by aj0strow** [auth0/docs#1899]
It would be nice to specify which fields beyond `user_id` are unique (if any).

```
docs/articles/user-profile/user-profile-structure.md
```

Which of the following are unique? All? None?
- `email`
- `phone_number`
- `nickname`
- `username`

It's also unclear whether social providers are unique per user. How many `facebook` accounts can be linked to one user?
- `identity.provider`

**Comment by mpaktiti** [comment]
Fixed https://github.com/auth0/docs/pull/4145
