### ISSUE TITLE
Please update SAML SSO with Auth0 as ServiceProvider and as an Identity Provider

### ISSUE THREAD

**Issue by davesykeselateral** [auth0/docs#1923]
I have been working through SAML SSO with Auth0 as ServiceProvider and as an Identity Provider https://auth0.com/docs/samlsso-auth0-to-auth0 and a struggling due to some of the terms that have changed within Auth0 and additional options that have been added to the app, but not to the documentation. I think I've worked it all out until I get to step 9, testing my sample application, where the browser shows the login dialog but with this message

We could not reach the server.
Please try again.

I can see from debug tools that the browser is trying to load
https://cdn.eu.auth0.com/client/Elateral-HTML-SAML-App.js?t1469710181407 
but it returns a 403 unauthorised response.

I've tried in browsers that are already logged in to Auth0, and one that is not.

Any suggestions please?

Thanks

Dave

**Comment by jeffreylees** [comment]
Hey, @davesykeselateral, this guide was updated in the last month or so, to reflect the process as it works now, with new instructions and imagery. If you're still needing to try this out, can you try the guide again? If you have any further issues, let us know!
