### ISSUE TITLE
golang seed project partial download

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#1926]
After i've downloaded seed project it seems to be partial download of [example](https://github.com/auth0/auth0-golang/tree/master/examples/regular-web-app).
[Here](https://gfycat.com/WarmheartedResponsibleBlobfish) is the screencast that show partial download.
![image](https://cloud.githubusercontent.com/assets/1114365/17221368/43ed5a86-54fc-11e6-90e2-506e8d039af7.png).

**Comment by iannyanes** [comment]
This issue is not reproducible.
