### ISSUE TITLE
Windows Phone Native tutorial does not specify how to handle authentication cancell

### ISSUE THREAD

**Issue by iannyanes** [auth0/docs#193]
The tutorial on https://auth0.com/docs/quickstart/native-mobile/windowsphone/no-api does not specify how to handle the case when authentication is cancelled by the user. 

The following piece of code is recomended

try{
var user = await App.Auth0.LoginAsync();
}
catch (AuthenticationCancelException)
{
// Handle case wen user cancelled authentication
}

**Comment by xperiandri** [comment]
Please, merge https://github.com/auth0/Auth0.WindowsPhone/pull/18 in order to close this issue and keep documentation in sync with sample in the repository.
