### ISSUE TITLE
php web app outdated dependency

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#1958]
It is suggested by tutorial to install auth0-php@~3.0, but up-to-date version of auth0-php at [composer](https://packagist.org/packages/auth0/auth0-php) is 3.4.1
![image](https://cloud.githubusercontent.com/assets/1114365/17271211/b46c3dd0-567e-11e6-8726-821ba43e4af4.png)

**Comment by iannyanes** [comment]
This issue is closed due to the information on the following link

https://getcomposer.org/doc/articles/versions.md
