### ISSUE TITLE
Jquery Quickstart - broken link

### ISSUE THREAD

**Issue by tomascaslo** [auth0/docs#1977]
The href at "Step 3" is pointing to "#3-implement-the-login" which directs to an empty page.
It should be updated to "/#3-implement-the-login".
![jquery-quickstart-1](https://cloud.githubusercontent.com/assets/2105919/17336170/8835d4b2-58a2-11e6-9066-1d0bc56e6f9c.png)

**Comment by chenkie** [comment]
This is working for me as is. Which browser are you using?

**Comment by iannyanes** [comment]
Closing this issue as not reproducible.
