### ISSUE TITLE
VanillaJS Quickstart - Unnecessary system requirement

### ISSUE THREAD

**Issue by tomascaslo** [auth0/docs#1981]
I don't think JQuery is a necessary system requirement for the vanilla js quickstart as it is not used in the code. It might be confusing for users and in any case if it is needed we should refer to JQuery Quickstart.
![vanilla-quickstart-1](https://cloud.githubusercontent.com/assets/2105919/17339799/23d2f926-58b3-11e6-8d98-9cca934041e2.png)

**Comment by vmartynets** [comment]
@chenkie seems like you deleted jquery from the dependencies of jquery tutorial, not from the vanilla JS tutorial.
Also, nodejs in system requirements of jquery tutorial is not needed, it only needed for seed project to start web server using `npm install -g serve` and `serve`.

**Comment by chenkie** [comment]
thanks good catch
