### ISSUE TITLE
Rails Tutorial - Gem package version outdated

### ISSUE THREAD

**Issue by fiannolo** [auth0/docs#2004]
After running the seed project, the gem file shows a newer version of the omniauth and omniauth-auth0 packages (1.3.1 and 1.4.1 respectively) and the tutorial points to the versions 1.3 of ominauth and 1.4 of omniauth-auth0.

![image](https://cloud.githubusercontent.com/assets/18537446/17385691/523d3d08-59b2-11e6-932b-628ed34451f7.png)

**Comment by iannyanes** [comment]
This issue is not reproducible - The command gets the latest version 1.3.x and 1.4.x If this fails in the future we can detect it in the testing sprint.
