### ISSUE TITLE
play2scala seed project can't be downloaded

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2024]
![image](https://cloud.githubusercontent.com/assets/1114365/17480987/5c902610-5d83-11e6-8df0-6ccaa91dbf66.png)

**Comment by vmartynets** [comment]
@chenkie thanks for the quick response, but it isn't fixed problem.

**Comment by chenkie** [comment]
The changes aren't live yet :)

**Comment by vmartynets** [comment]
@chenkie oops, my bad. thanks for the quick fix.

**Comment by chenkie** [comment]
👍
