### ISSUE TITLE
Generating token for API v2 with multiple accounts is confusing

### ISSUE THREAD

**Issue by glena** [auth0/docs#204]
If I have multiple account access with my user, it is not clear which account is logged in when I am creating a token.

Since the only way I can switch between them is in the dashboard dropdown, when I am generating the token is not clear from which account is the token.

Maybe we can add the account name in the token generator (nor sure if in the ket/secret modal or over the scopes selector).

Also, I think it would be useful to add a small sentence saying that the client_id and secret we are showing are from the account and not from an app/client.

cc @vctrfrnndz

**Comment by ntotten** [comment]
Moving to auth0-docs
