### ISSUE TITLE
AngularJS Tutorial Dashboard Image outdated

### ISSUE THREAD

**Issue by fiannolo** [auth0/docs#2060]
The image displayed in the tutorial references the old version of the dashboard, where the applications menu item has been changed for clients and added the new section "client type".

![image](https://cloud.githubusercontent.com/assets/18537446/17573277/52e69806-5f27-11e6-9f65-50a07780a93a.png)

**Comment by mpaktiti** [comment]
Updated https://github.com/auth0/docs/pull/2061
