### ISSUE TITLE
System Requirements not present on Single Page App Javascript (Vanilla.js) 

### ISSUE THREAD

**Issue by mehreencs87** [auth0/docs#2068]
check here at
![vanilla](https://cloud.githubusercontent.com/assets/14890513/17586148/4c05e750-5fd9-11e6-8a58-cbc52677c5cd.png)
 https://auth0.com/docs/quickstart/spa/vanillajs

**Comment by chenkie** [comment]
In this case we don't really need anything because it's just JavaScript :)
