### ISSUE TITLE
AngularJS Tutorial Rule Template Image Outdated

### ISSUE THREAD

**Issue by fiannolo** [auth0/docs#2112]
The image displayed in the tutorial references the old version of the rule template, where the applications menu item has been changed for clients and added the new section "client type".
![rule_template_old](https://cloud.githubusercontent.com/assets/18537446/17719700/8f53b0cc-63ea-11e6-9f90-530b7532737d.png)

**Comment by mpaktiti** [comment]
@fiannolo @iannyanes 

This should be fixed. If you find any tutorials that still use the old screenshot please reopen this issue and provide the list of tutorials. Thank you!
