### ISSUE TITLE
Sensitive cookie auth0l scoped to parent domain

### ISSUE THREAD

**Issue by yvonnewilson** [auth0/docs#212]
The application sets a sensitive cookie with a "domain" attribute that is scoped to the parent domain. This cookie could be read by less trustworthy or less secure sites that share the same parent domain.
Omit the "domain" attribute when setting the cookie or explicitly scope the cookie to the application sub-domain. If the cookie must be shared, review the security of sites that share the same parent domain.
Cookie name is: auth0l

Please refer to FID-14 in SRP_Tech_Ref_[Count Autho Aura API].docx, sent separately for review, analysis and remediation.
Suggested fix - implement SSO between docs and apps

**Comment by jfromaniello** [comment]
Fixed last week, thanks for reporting
