### ISSUE TITLE
Android seed does not set configuration values

### ISSUE THREAD

**Issue by mpaktiti** [auth0/docs#2123]
The Android seeds do not set the Client ID and Domain, the user has to manually set the values.

The Android configuration file is [this](https://github.com/auth0-samples/auth0-android-sample/blob/master/01-Login/app/src/main/res/values/strings.xml). 

``` xml
<string name="auth0_client_id">ADD YOUR APPs CLIENT ID</string>
<string name="auth0_domain">ADD YOU APPs DOMAIN</string>
```

I think the fix is to change the above to:

``` xml
<string name="auth0_client_id">AUTH0_CLIENT_ID</string>
<string name="auth0_domain">AUTH0_DOMAIN</string>
```

and the seed to:

```
 <%= include('../../_includes/_package', {
  githubUrl: 'https://github.com/auth0-samples/auth0-android-sample/tree/master/01-Login',
  pkgOrg: 'auth0-samples',
  pkgRepo: 'auth0-android-sample',
  pkgBranch: 'master',
  pkgPath: '01-Login',
  pkgFilePath: '01-Login/app/src/main/res/values/strings.xml',
  pkgType: 'replace'
}) %>
```

**Comment by mpaktiti** [comment]
@chenkie @tenmaster 
Since the samples are not updated yet, I'm reopening this issue.

**Comment by vmartynets** [comment]
@mpaktiti looks like it fixed now.
