### ISSUE TITLE
Document how to reset the tenant admin password

### ISSUE THREAD

**Issue by jgelsey** [auth0/docs#2138]
IE so guys like this are not confused: https://auth0.zendesk.com/agent/tickets/12697

Just a paragraph somewhere that says "log out and then hit password reset in Lock" is what I am thinking would be enough.

**Comment by chenkie** [comment]
@ntotten

**Comment by mpaktiti** [comment]
Documentation update request registered at Docs trello board.

**Comment by khorne3** [comment]
https://github.com/auth0/docs/pull/3622

**Comment by mpaktiti** [comment]
Fixed: [Reset Your Auth0 Account Password](https://auth0.com/docs/tutorials/reset-account-password)
