### ISSUE TITLE
paragraphs titles transforms to links

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2165]
When you looking to Ionic tutorial from client manager (i mean from https://manage.auth0.com/#/applications/.../quickstart) paragraphs titles transforms to links that points to not existing pages. When you looking from [documentation](https://auth0.com/docs/quickstart/native/ionic) it's alright. Maybe related issue https://github.com/auth0/docs/issues/1528
![image](https://cloud.githubusercontent.com/assets/1114365/17937407/a892a110-6a2a-11e6-9037-d39a9a827fa5.png)

**Comment by vmartynets** [comment]
same on [UWP javascript tutorial](https://auth0.com/docs/quickstart/native/windows-uwp-javascript). Screenshot from dashboard with UWP javascript tutorial.
![image](https://cloud.githubusercontent.com/assets/1114365/17976297/863b2e68-6af5-11e6-8641-3fe98b1da23b.png)

**Comment by vmartynets** [comment]
Same on [java tutorial](https://auth0.com/docs/quickstart/webapp/java)
![image](https://cloud.githubusercontent.com/assets/1114365/18014250/b615906c-6bca-11e6-896c-6abe27834cb7.png)

**Comment by mpaktiti** [comment]
Fixed
