### ISSUE TITLE
UWP tutorials wrong links

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2173]
Link in [UWP JS tutorial](https://auth0.com/docs/quickstart/native/windows-uwp-javascript#access-user-information) point to xamarin components website instead of [this](http://www.newtonsoft.com/json).
![image](https://cloud.githubusercontent.com/assets/1114365/17978775/48f3b614-6b00-11e6-92a2-03777668255b.png)

**Comment by vmartynets** [comment]
Same for [UWP C# tutorial](https://auth0.com/docs/quickstart/native/windows-uwp-csharp).

**Comment by chenkie** [comment]
Fixed by #2229 and #2230
