### ISSUE TITLE
UWP C# no system requirements

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2177]
There is no system requirements for [UWP C# tutorial](https://auth0.com/docs/quickstart/native/windows-uwp-csharp).
![image](https://cloud.githubusercontent.com/assets/1114365/17982367/3225fb76-6b10-11e6-8058-5ab41f1701e4.png)

**Comment by mpaktiti** [comment]
Fixed https://github.com/auth0/docs/pull/2631
