### ISSUE TITLE
Java tutorial broken links

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2179]
Link called `seed project` points [here](https://github.com/auth0-samples/auth0-servlet-sample/tree/master/00-Start) which is missing page.
![image](https://cloud.githubusercontent.com/assets/1114365/18014686/ba3fd83a-6bcc-11e6-975e-079ae06d5235.png)

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/2217
