### ISSUE TITLE
Java tutorial missing credentials

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2181]
[Java tutorial](https://auth0.com/docs/quickstart/webapp/java#configure-your-java-app) can be enhanced, credentials stubs can be replaced with user credentials.
![image](https://cloud.githubusercontent.com/assets/1114365/18016285/320c580a-6bd4-11e6-9a5a-796990a171d6.png)

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/2217
