### ISSUE TITLE
Java spring mvc tutorial outdated lock

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2183]
[Step 1](https://auth0.com/docs/quickstart/webapp/java-spring-mvc/01-login#display-lock-widget) of java spring mvc tutorial contains outdated lock, but lock is initialized as v10.
![image](https://cloud.githubusercontent.com/assets/1114365/18028863/39c0a0c0-6c91-11e6-910d-2b182f40a0b9.png)

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/2217
