### ISSUE TITLE
java spring mvc tutorial unknown reference

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2184]
[Java spring mvc tutorial](https://auth0.com/docs/quickstart/webapp/java-spring-mvc/01-login) contains reference of `xyz` which is not explained.
![image](https://cloud.githubusercontent.com/assets/1114365/18028899/b84df690-6c91-11e6-97fc-41f15f1498cf.png)

**Comment by vmartynets** [comment]
Same on [java spring security tutorial](https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc/01-login#display-lock-widget)
![image](https://cloud.githubusercontent.com/assets/1114365/18087755/6314d22c-6ebf-11e6-9f10-ddd002fffb25.png)

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/2217
