### ISSUE TITLE
Logging into docs page redirects to dashboard

### ISSUE THREAD

**Issue by BRVNDXN** [auth0/docs#2188]
When logged into management dashboard, when I click "documentation" I am redirected to the docs page. However, it indicates that I am not logged in (login box present), and does say "open dashboard" like it has in the past. When I click log in, I go through the usual login process, but am redirected back to the manage dashboard. The only way I can get to actual docs is by clicking one of the categories below "curated content to fully understand our platform", then that opens the docs page.

**Comment by thameera** [comment]
The Management API page always showed the "Log In" button even when the user is logged in. But this has become more apparent with the new design (orange in white background). A customer has filed a ticket today as well.

Would be great if this could get fixed.

**Comment by mpaktiti** [comment]
@thameera Actually I see it even when I go to the docs main page (go to dashboard > log in > click Documentation link at the top right > navigated to auth0.com/docs with the Log In button displayed.

@ntotten Was this a deliberate change or should I report this issue to another repo?

**Comment by ntotten** [comment]
This is by design. The assumption is that in most cases when somebody wants to "Login" they want to login to the management portal, not login to docs.

This isnt a new thing, it has always done this. I can see how in some cases the behavior might be confusing, but for most people i think the behavior is what they expect.

**Comment by thameera** [comment]
@ntotten I think there has been a request to show the currently logged in Auth0 tenant name in the Management API docs page for some time. Is this related to the above or a separate case?
