### ISSUE TITLE
java spring security missing credentials

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2192]
[Java spring security tutorial](https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc#configure-your-spring-security-app) can be enhanced, credentials stubs can be replaced with user credentials.
![image](https://cloud.githubusercontent.com/assets/1114365/18087530/5de95350-6ebe-11e6-83d6-dcfc764541c6.png)

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/2217
