### ISSUE TITLE
java spring security outdated instructions

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2193]
[This step](https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc/01-login#display-lock-widget) of Java spring security contains outdated instructions. `showSignin` method was removed in lock v10.
![image](https://cloud.githubusercontent.com/assets/1114365/18087651/e9c9e7b8-6ebe-11e6-9bb0-bf8c14eef5b4.png)

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/2217
