### ISSUE TITLE
PHP api snippet formatting

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2198]
Snippet from [2nd step](https://auth0.com/docs/quickstart/backend/php#2-create-the-jwt-validation-filter) of php api tutorial have extra tabulation and extra slashes.
![image](https://cloud.githubusercontent.com/assets/1114365/18101964/7c068d04-6ef9-11e6-8ec1-b56a6e83b9db.png)

**Comment by mehreencs87** [comment]
fix  https://github.com/auth0/docs/pull/2226

**Comment by mpaktiti** [comment]
Fix merged.

**Comment by camimonse** [comment]
Sanity failed, extra Tabulation is not fixed
