### ISSUE TITLE
php api outdated auth0-php

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2199]
[PHP api tutorial](https://auth0.com/docs/quickstart/backend/php) suggests to install auth0/auth0-php:~3.1 when up-to-date version is 4.0.0
![image](https://cloud.githubusercontent.com/assets/1114365/18102087/033e8966-6efa-11e6-8087-30a2556ecd4a.png)

**Comment by mpaktiti** [comment]
Fix deployed
