### ISSUE TITLE
Possibly wrong graphic in Mobile-API docs

### ISSUE THREAD

**Issue by sebadoom** [auth0/docs#2234]
Hi, the first graphic in this page: https://auth0.com/docs/architecture-scenarios/application/mobile-api shows the resource server as taking the access token rather than the id_token. This is most likely not what is expected. The resource server usually takes the id_token (or any other signed JWT) as a credential.

For further discussion see the comments in this post: https://auth0.com/blog/stateless-auth-for-stateful-minds/

Thanks!

**Comment by mpaktiti** [comment]
Hi @sebadoom ! You are correct, with the current implementation the `id_token` is used. I will update the doc.

Thank you! 👍

**Comment by mpaktiti** [comment]
Fixed https://github.com/auth0/docs/pull/2258
