### ISSUE TITLE
Troubleshooting section of SAML page contains a non existing link.

### ISSUE THREAD

**Issue by mefarazath** [auth0/docs#2382]
The Troubleshooting section of [SAML page](https://auth0.com/docs/saml-configuration) contains the below bullet point
### 

> "SAML responses from Auth0's logs can be pasted directly into this debugger"

which links to a page that does not have the tool it tries to point to (screenshot of redirected page attached)

![selection_014](https://cloud.githubusercontent.com/assets/5237653/18809576/f89dee46-829c-11e6-85fb-eb4ac184ddd6.png)

**Comment by mpaktiti** [comment]
Nice catch! Thanks for reporting this @mefarazath 👍

**Comment by mpaktiti** [comment]
The correct link is `http://openidtest.uninett.no/samldebug` but it doesn't work any longer. The link was removed from the doc.
