### ISSUE TITLE
id_token singing algorithm for different types of clients

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/docs#2390]
If you're building a traditional web app, id_tokens will be signed using RS256/RS512. The quickstarts/docs/SDKs should make this clear and not use H256

**Comment by mpaktiti** [comment]
^ @chenkie

**Comment by mpaktiti** [comment]
Hey @sandrinodimattia does this mean that each web app quickstart should have something like this? https://auth0.com/docs/quickstart/webapp/aspnet-core#configure-json-web-token-signature-algorithm
