### ISSUE TITLE
Update Protocols document

### ISSUE THREAD

**Issue by cabralmartin** [auth0/docs#2409]
[https://auth0.com/docs/protocols](https://auth0.com/docs/protocols)
- Remove mentions of sending the `id_token` to APIs
- Explain available `response_types` and `response_modes`

**Comment by mpaktiti** [comment]
[The OAuth protocol doc](https://auth0.com/docs/protocols/oauth2) was updated to use [access tokens](https://auth0.com/docs/protocols/oauth2#access-token). ID Tokens are now part of the [OIDC protocol doc](https://auth0.com/docs/protocols/oidc).

Adding info on the available `response_types` and `response_modes` is pending.
