### ISSUE TITLE
ASP NET regular web app tutorial links doesn't open in a new tab.

### ISSUE THREAD

**Issue by fiannolo** [auth0/docs#2429]
All the links in the tutorial open in the same tab, redirecting the user out of the tutorial.
After checking the readme.md file all the links are created this way:

![readme](https://cloud.githubusercontent.com/assets/18537446/19061614/35e57916-89c0-11e6-9e29-b5b692427125.png)

To solve this problem should be used HTML tags inside the markdown syntax and define the target to _blank like this:

```
<a href="http://example.com/" target="_blank">example</a>
```

**Comment by mpaktiti** [comment]
^ @jerriep

**Comment by jerriep** [comment]
@chenkie Can you please comment on our approach on how to open links? I would prefer consistency, so I would not want to update just one to open in a new tab.

**Comment by mpaktiti** [comment]
Thank you @fiannolo . It’s expected behaviour to stay in the same tab so I'm going to close this issue.

**Comment by camimonse** [comment]
Sanity passed
