### ISSUE TITLE
ASP NET Regular Web App Lock Version outdated

### ISSUE THREAD

**Issue by fiannolo** [auth0/docs#2431]
The Lock version displayed in the tutorial points to Lock 10.2 and the seed project points to Lock 10.0

![image](https://cloud.githubusercontent.com/assets/18537446/19062353/5bc576b6-89c7-11e6-97c8-df4c494c63b3.png)

the image above refers to the `Triggering Login Manually or Integrating Lock` section and the newer version of Lock is the 10.4.0

Additionally in the seed project, specifically in the _Layout.cshtml file, the cdn link points to the 10.0 version of Lock.

![image](https://cloud.githubusercontent.com/assets/18537446/19062440/397ded4e-89c8-11e6-9528-68da97080f6e.png)

**Comment by mpaktiti** [comment]
^ @jerriep

**Comment by jerriep** [comment]
@chenkie What is the approach to keep Lock updated in seed projects? Is one of the vendors still taking care of this, or must we do it? Also, must it be kept in step with every single point release?

**Comment by chenkie** [comment]
@jerriep I'd like it to be kept up with every major.minor at least.

@fiannolo is the seed project tested with 10.4? if so, can you please post a PR to update the version?

**Comment by jerriep** [comment]
Adding it to my list of thing to work on :)

**Comment by jerriep** [comment]
I have updated seed project

The Lock embed code generator also needs updating across the board

**Comment by camimonse** [comment]
Sanity passed
