### ISSUE TITLE
Question on Scope

### ISSUE THREAD

**Issue by faysal515** [auth0/docs#2432]
How can I add an extra attribute in scope of authentication. 

lets say i want to include `role` in scope. and role is in `user/app metadata`. and as far as I've seen the API, auth0 doesn't allow me to add any extra property in user object. all my additional data will be stored in user_meta or app_meta. then how can `favorite_food`  can be claimed in scope

https://github.com/auth0/docs/blob/master/articles/scopes/index.md

https://auth0.com/docs/scopes#requesting-specific-claims

**Comment by mpaktiti** [comment]
Hello @faysal515 ! I'm not sure I understand the problem you are facing. You can update the metadata with the additional user information you want. Then, you set the `scope` parameter accordingly and when you retrieve the `id_token` you can parse the JSON to retrieve that additional information. Is any of this not working for you or is the documentation not clear?

[Updating Metadata](https://auth0.com/docs/rules/metadata-in-rules#updating-metadata)
[Reading Metadata](https://auth0.com/docs/rules/metadata-in-rules#reading-metadata)
[Scopes: request specific claims](https://auth0.com/docs/scopes#requesting-specific-claims)

**Comment by faysal515** [comment]
okay, let me re describe my situation again. I can update `app metadata` & `user metadata`. lets say it's something like this

`{
    roles:['something','cool'],
    permission: ['add','read'],
    extra: {/*an object*/}
}`

now I want to sign/claim the permission attribute of my `app metadata` or `user metadata` along with `openid email name ...`. What would I write specifically in scope (in that 3 dots) then? because my information are nested into either `app metadata` or `user metadata`

**Comment by mpaktiti** [comment]
You should authenticate using `openid email name permission` so you can get the `permission` part back. If you wanted all of the above you should use `openid email name permission roles extra`.

If you added `permission` in the `app_metadata` you should use: `user.app_metadata.permission` to retrieve the value.

If you added `permission` in the `user_metadata` you should use: `user.user_metadata.permission` to retrieve the value.

If you used the `app_metadata` and you want to check if the user has the `add` permission you should use:

```
function(user, context, callback){
  user.app_metadata = user.app_metadata || {};
  if (user.app_metadata.permission.indexOf('add')){
    // code to be executed
  }
  ...
}
```

This snippet uses [rules to read metadata](https://auth0.com/docs/rules/metadata-in-rules#reading-metadata) so if you want to do this check in your app you should translate the above to the language you are using. The process is that you authenticate your user, get the `id_token` (using `openid email name permission`), parse it, and get the values you need from the JSON object returned.

Makes sense?

**Comment by faysal515** [comment]
i have this raw JSON in auth0.

![screen shot 2016-10-04 at 5 04 13 pm](https://cloud.githubusercontent.com/assets/10289348/19071986/a65964f2-8a54-11e6-9380-6044cb042db0.png)

can i just set my scope to `openid email name permission`  this?

**Comment by mpaktiti** [comment]
If `permission` exists in your JSON then yes, that's all you would have to do. But I cannot see such a property in your JSON. If you wanted to retrieve the `roles` instead you would have to set the scope to `openid roles`. Then once you decoded your JWT you could get the values.

For example, my user has this metadata:

![image](https://cloud.githubusercontent.com/assets/11715799/19073582/6d5fb3dc-8a44-11e6-9335-0aa55702135a.png)

If I authenticate using only openid (`GET https://my.account.auth0.com/authorize?response_type=token&client_id=MY_CLIENT_ID&connection=CONNECTION_NAME&redirect_uri=REDIRECT_URL&state=&scope=openid`) I get back an id_token, which payload includes only these claims:
![image](https://cloud.githubusercontent.com/assets/11715799/19073708/1ae57aaa-8a45-11e6-8325-d6e05dffbdee.png)

If I authenticate using roles as well (`GET https://my.account.auth0.com/authorize?response_type=token&client_id=MY_CLIENT_ID&connection=CONNECTION_NAME&redirect_uri=REDIRECT_URL&state=&scope=openid%20roles`), then my JWT's payload includes also the roles I want:

![image](https://cloud.githubusercontent.com/assets/11715799/19073746/50cee584-8a45-11e6-90e7-453fc0545754.png)

You can try it yourself using the `/authorize` endpoint and https://jwt.io/ to decode the `id_token` you will get as response.

Let me know if this explains things.

**Comment by faysal515** [comment]
thanks for clarification
