### ISSUE TITLE
Bold text not displaying as bold

### ISSUE THREAD

**Issue by jerriep** [auth0/docs#2448]
Bold text, i.e. inside a `<strong>` does not display as bold. See https://auth0.com/docs/user-profile for an example

![image](https://cloud.githubusercontent.com/assets/1006420/19102364/ed388e16-8af9-11e6-94a8-98108a20736d.png)

**Comment by ntotten** [comment]
Wrong repo, moved: https://github.com/auth0/auth0-docs/issues/1170
