### ISSUE TITLE
laravel and laravel api wrong packager option

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2458]
When i'm tried to load 00-Starter-Seed laravel project got nothing. Added `APP_DEBUG=true` to `.env` file and get this error:
![image](https://cloud.githubusercontent.com/assets/1114365/19130667/d4f8e124-8b54-11e6-8719-8efe597b1793.png)
Seems like project won't work with current packager setting, which is `server` need to change setting to `replace` credentials

**Comment by mpaktiti** [comment]
Hi @Amialc . You tried to download a seed project and got this error? If so can you tell me which quickstart you used? Laravel seems to be working for me.

**Comment by vmartynets** [comment]
Hello, @mpaktiti . I have downloaded seed project from [here](https://auth0.com/docs/quickstart/webapp/laravel). Run command `composer install && php artisan serve` to install dependencies and run server and got this error:
![image](https://cloud.githubusercontent.com/assets/1114365/19150498/cbdde4ce-8bcf-11e6-84f1-f46a93dcca48.png)
To see what is the error, i've added `APP_DEBUG=true` to `.env` file and got error about supported ciphers. To solve this error, i've added `APP_DEBUG=true` and `APP_KEY=` to `.env` file and run `php artisan key:generate` to generate key, after this app works:
![image](https://cloud.githubusercontent.com/assets/1114365/19150596/58b9e6fe-8bd0-11e6-8594-8b1c80b5fb44.png)
So problem is that laravel requires `APP_KEY=` to be set in `.env` file.

**Comment by mpaktiti** [comment]
Great, @Amialc thanks for the details! We will look into this.

**Comment by mpaktiti** [comment]
@chenkie @glena ^^

**Comment by glena** [comment]
The packager must be ignoring the .env file

**Comment by vmartynets** [comment]
Same error with [laravel api](https://auth0.com/docs/quickstart/backend/php-laravel)

**Comment by chenkie** [comment]
putting in a fix now with the new packager

**Comment by chenkie** [comment]
Fixes with the new packager
