### ISSUE TITLE
Angular.js Single Page App Lock Version outdated

### ISSUE THREAD

**Issue by rafanog** [auth0/docs#2459]
The lock version on the tutorial points to Lock version 10.2

![screenshot](https://cloud.githubusercontent.com/assets/15782359/19135774/34f67d4a-8b35-11e6-8bb1-016e52e5d757.PNG)

The image above refers to the `Step1: Install the Dependencies` section and the latest version of the lock is 10.4.0

**Comment by chenkie** [comment]
Fixes with #2505
