### ISSUE TITLE
Grammatical errors found

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2471]
in https://auth0.com/docs/quickstart/native/android have been grammar typos found:

Login:
- in deph --> in-deph
- No comma
- in --> on
  ![typos](https://cloud.githubusercontent.com/assets/18585436/19164778/5b90ce66-8bcf-11e6-91e9-354f9fa9fd1e.PNG)

Session Handling:
- by --> of
  ![image](https://cloud.githubusercontent.com/assets/18585436/19165175/d5ad556a-8bd0-11e6-92a1-c9270b688e48.png)

User Profile:
- is instantiate --> is to instantiate
  ![image](https://cloud.githubusercontent.com/assets/18585436/19165517/0f6ebc3e-8bd2-11e6-8301-ec0a13447c05.png)

Linking Accounts:
- link with --> link to
  ![image](https://cloud.githubusercontent.com/assets/18585436/19165706/defc8ab2-8bd2-11e6-9df4-e97f63dc5f36.png)

-needs comma:
![image](https://cloud.githubusercontent.com/assets/18585436/19165743/0be37a4a-8bd3-11e6-9f49-c64fe5102803.png)

Authorization:
- users --> user's
  ![image](https://cloud.githubusercontent.com/assets/18585436/19165955/d2391736-8bd3-11e6-9172-024772b62523.png)

Calling APIs:
-add commas
![image](https://cloud.githubusercontent.com/assets/18585436/19166132/68eb4cb2-8bd4-11e6-88d8-8baaa63b6f53.png)

**Comment by chenkie** [comment]
Fixes with #2505

**Comment by camimonse** [comment]
**Sanity failed**. two typos still need to be fixed:
- in --> on   in the login (see above)
- users --> user's   in Authorization (see above)
