### ISSUE TITLE
ASP NET Regular Web App Logout Call endpoint error

### ISSUE THREAD

**Issue by fiannolo** [auth0/docs#2474]
In the Logout section of the tutorial is suggested to call the Logout Endpoint encoding the logout URL (see the image below)

![image](https://cloud.githubusercontent.com/assets/18537446/19176375/1daaac00-8c0d-11e6-8bdf-0569e26a7fbe.png)

Having as a result, this url:

```
https://tutorials.auth0.com/v2/logout?returnTo=http%3a%2f%2flocalhost%3a36283%2f
```

After checking in the documentation of the logout endpoint, must be called sending as a parameter the logout URL without being encoded:

![image](https://cloud.githubusercontent.com/assets/18537446/19176434/b41da1f6-8c0d-11e6-90ae-55b254af6cb6.png)

https://auth0.com/docs/logout#redirecting-users-after-logout

To solve this problem, the URLEncode function should be removed.

**Comment by mpaktiti** [comment]
@jerriep Can you have a look please?

**Comment by jerriep** [comment]
@fiannolo Please add a URL to the tutorial step on the Docs website when you open an issue

**Comment by jerriep** [comment]
@fiannolo I tested it and it works 100% with the encoded url.

I also do not believe that sending an unencoded URL as a querystring parameter is correct. If the sample shows an unencoded URL, then I believe that sample should be fixed.

I will raise this on the internal Auth0 Slack channel and will revert back to you

**Comment by jerriep** [comment]
The `returnTo` URL should be URL Encoded, which means the sample is correct. I updated the docs instead to indicate that URL encoding is preferable
