### ISSUE TITLE
grammatical error found

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2476]
in https://auth0.com/docs/quickstart/native/android is a grammatical error found

Introduction:
- can found --> can BE found (see photo below)

![image](https://cloud.githubusercontent.com/assets/18585436/19197123/42c8b5ee-8c86-11e6-9db6-688287e3656a.png)

**Comment by mpaktiti** [comment]
Thank you @camimonse ! 👍

**Comment by camimonse** [comment]
Sanity passed
