### ISSUE TITLE
Ruby on Rails web app Auth0-omniauth version outdated.

### ISSUE THREAD

**Issue by fiannolo** [auth0/docs#2480]
The tutorial and the seed project points to an older version of the auth0 gem package file.

![image](https://cloud.githubusercontent.com/assets/18537446/19207316/b4d2aa32-8cbd-11e6-8b8e-e99d7379e94c.png)

After checking in the GEM package repository the newer version of this package is the 1.4.2

![image](https://cloud.githubusercontent.com/assets/18537446/19207334/f2d1f018-8cbd-11e6-90ce-74ffb2058913.png)

Also, the gem file in the seed project points to the same old version 1.4.1

![image](https://cloud.githubusercontent.com/assets/18537446/19207352/191501ac-8cbe-11e6-8f92-bc7af25f7972.png)

**Comment by chenkie** [comment]
Fixes with #2505

**Comment by camimonse** [comment]
Sanity failed, it still need to be updated in https://github.com/auth0/omniauth-auth0/blob/master/examples/ruby-on-rails-webapp/Gemfile#L34
