### ISSUE TITLE
Ruby on rail Lock Version Outdated

### ISSUE THREAD

**Issue by fiannolo** [auth0/docs#2482]
According to the Github Repo, the newer version of lock is the 10.4.0.

Gihub:
![image](https://cloud.githubusercontent.com/assets/18537446/19207530/cdb14822-8cbf-11e6-96ec-5693ef8820ca.png)

Tutorial (Lock Modal) (Lock 10.2)
![image](https://cloud.githubusercontent.com/assets/18537446/19207518/b67e5a96-8cbf-11e6-8d83-39ee29fb2823.png)

Tutorial (Lock Inline)(Lock 10.2)
![image](https://cloud.githubusercontent.com/assets/18537446/19207575/12aecec2-8cc0-11e6-80e7-b103ece57a2b.png)

Seed project: (Lock 10.0)
![image](https://cloud.githubusercontent.com/assets/18537446/19207649/ae93c8ec-8cc0-11e6-8c0e-605e8f7429d7.png)

**Comment by chenkie** [comment]
Fixes with #2505

**Comment by camimonse** [comment]
Sanity passed
