### ISSUE TITLE
Jquery Tutorial : Spelling mistake

### ISSUE THREAD

**Issue by mehreencs87** [auth0/docs#2487]
![logout](https://cloud.githubusercontent.com/assets/14890513/19231138/3c0bb1bc-8e8d-11e6-8a4a-b06e0e6fa80b.PNG)

**Comment by mpaktiti** [comment]
Fixed https://github.com/auth0/docs/blob/master/articles/client-platforms/jquery/01-login.md#5-log-out

Thank you @mehreencs87 ! 👍

**Comment by camimonse** [comment]
Sanity passed
