### ISSUE TITLE
Add location

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2494]
in https://auth0.com/docs/quickstart/native/android/00-introduction at the bottom, it is not described where that snippet is located, and where we can find it in our files. 

**For example, one step before it does say (see photo bellow):**

![image](https://cloud.githubusercontent.com/assets/18585436/19245869/7cac6176-8ef1-11e6-92d9-8894383ada30.png)

**but in the last step of this page doesn't indicate the location of the snippet, and takes more time to the user to find the correct file:**

![image](https://cloud.githubusercontent.com/assets/18585436/19245786/00754c44-8ef1-11e6-806a-9585939ca16f.png)

what it should say is:  "The data path for Lock **located in your _AndroidManifest.xml_ file**, also needs to be set.

**Comment by chenkie** [comment]
Fixes with #2505

**Comment by camimonse** [comment]
Sanity passed
