### ISSUE TITLE
symphony api tutorial invalid reference

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2499]
[PHP (Symfony) API](https://auth0.com/docs/quickstart/backend/php-symfony) tutorial reference that you have asp.net web api project, which is typo, should be `... to configure your existing symphony API app ..`
![image](https://cloud.githubusercontent.com/assets/1114365/19274999/d8f5bace-8fda-11e6-8f9e-56458d797074.png)

**Comment by mpaktiti** [comment]
Thank you @Amialc ! I just fixed this https://github.com/auth0/docs/commit/fcbda717c0492204bc71d7c7b4b4725a5d1dc8a8#diff-98ab08f1d1c5fc9ae1b1541498e0f17f

**Comment by camimonse** [comment]
Sanity passed
