### ISSUE TITLE
Ruby on Rails tutorial snippet with wrong user_info call

### ISSUE THREAD

**Issue by fiannolo** [auth0/docs#2506]
AUTH-3371
Testing the tutorial, after using the code snippet to access the user information (Image below) 

![image](https://cloud.githubusercontent.com/assets/18537446/19292516/9919967c-8fea-11e6-8e65-e064c4a93345.png)

It generates the error below, showing that is not possible to access the user info array:
![image](https://cloud.githubusercontent.com/assets/18537446/19292485/6e96543a-8fea-11e6-8ee1-bac9e999723c.png)

I have debugged it and after replacing the code for the snippet below it started working.

```
<div>
  <img class="avatar" src="<%= @user['info']['image'] %>"/>
  <h2>Welcome <%= @user['info']['name'] %></h2>
</div>
```

Working:
![image](https://cloud.githubusercontent.com/assets/18537446/19292574/0e892616-8feb-11e6-8c70-c9fc3bc33e0f.png)

Tutorial URL: https://auth0.com/docs/quickstart/webapp/rails

**Comment by camimonse** [comment]
Sanity Passed
