### ISSUE TITLE
Mob App Electron Quick Start contains a non existing link

### ISSUE THREAD

**Issue by mehreencs87** [auth0/docs#2509]
Auth#3442 on tutorial step #3
![bad link](https://cloud.githubusercontent.com/assets/14890513/19306017/14e73514-908d-11e6-94ac-16495c9b8850.JPG)
 Directs to page not found 404 error.
![eror](https://cloud.githubusercontent.com/assets/14890513/19306120/98ca8ff2-908d-11e6-919c-09942f691841.JPG)

**Comment by camimonse** [comment]
@chenkie I noticed that after doing the changes you forgot to adjust the numbering, now there are three steps to follow but the numbering goes 1, 2, 4 in https://auth0.com/docs/quickstart/native/electron 
You might take a look on that
