### ISSUE TITLE
go lang api tutorial no system requirements

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2511]
[Go lang api tutorial](https://auth0.com/docs/quickstart/backend/golang) have no system requirements.
![image](https://cloud.githubusercontent.com/assets/1114365/19321562/38d89e50-90be-11e6-9c5f-7ba22d09f580.png)

**Comment by camimonse** [comment]
Sanity failed. The System requirements still not being shown

**Comment by vmartynets** [comment]
@chenkie this issue was related to go lang API tutorial and you added to go lang webapp tutorial.
