### ISSUE TITLE
hapi api tutorial no system requirements

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2512]
[Hapi api tutorial](https://auth0.com/docs/quickstart/backend/hapi) have no system requirements.
![image](https://cloud.githubusercontent.com/assets/1114365/19322011/f6f70970-90bf-11e6-9a45-e308d500f1c9.png)

**Comment by chenkie** [comment]
Fixed by #2546

**Comment by camimonse** [comment]
Sanity passed
