### ISSUE TITLE
python tutorial unused code in snippet

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2521]
(AUTH-3451)
[Snippet](https://auth0.com/docs/quickstart/webapp/python#add-the-auth0-callback-handler) in python tutorial contains unused code, variable `env` is not being used everywhere, so this variable and `import os` could be deleted:
![image](https://cloud.githubusercontent.com/assets/1114365/19364441/ea6cf9a8-9196-11e6-8fab-b00a8402732a.png)

**Comment by camimonse** [comment]
Sanity passed
