### ISSUE TITLE
ionic 2 tutorial hardcoded libraries versions

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2522]
[Ionic 2 tutorial](https://auth0.com/docs/quickstart/native/ionic2#add-the-lock-widget) have snippet which consist of hardcoded links to outdated versions of libraries. (AUTH-3452)
![image](https://cloud.githubusercontent.com/assets/1114365/19365922/a4d742d4-919d-11e6-9064-060bc5152429.png)

**Comment by camimonse** [comment]
Sanity passed
