### ISSUE TITLE
Node.js Regular Webapp Tutorial lock version outdated

### ISSUE THREAD

**Issue by rafanog** [auth0/docs#2525]
[Node.js tutorial](https://auth0.com/docs/quickstart/webapp/nodejs/00-intro#dependencies) makes reference to the outdated version of the lock library:

![step 5 issue](https://cloud.githubusercontent.com/assets/15782359/19374891/4a26489e-919d-11e6-8d2e-cc7b28b536a2.PNG)

![step 5 issue 2](https://cloud.githubusercontent.com/assets/15782359/19375272/6884beee-91a0-11e6-8f11-12c2b76cf00a.PNG)

**Comment by mpaktiti** [comment]
@chenkie docs should be updated to use these variables https://github.com/auth0/docs/blob/master/config/vars.yml

**Comment by chenkie** [comment]
Fixed by #2546

**Comment by camimonse** [comment]
Sanity passed
