### ISSUE TITLE
Grammatical error and typo in PHP quickstart

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2532]
in https://auth0.com/docs/quickstart/webapp/symfony is a Typo found:

db --> it is better written as "DB" (in capital letters):

![image](https://cloud.githubusercontent.com/assets/18585436/19393438/bbfb9388-9202-11e6-84f7-e69da50bd5da.png)

At the bottom of the page is a grammatical error found:
in --> on

![image](https://cloud.githubusercontent.com/assets/18585436/19393328/4b093518-9202-11e6-8e80-6f4a0a8dc342.png)

this make reference to the auth0 ticket N. 3359

**Comment by chenkie** [comment]
Fixed by #2544

**Comment by camimonse** [comment]
Sanity passed
