### ISSUE TITLE
ruby api tutorial incorrect seed

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2551]
`Download sample` at [ruby api](https://auth0.com/docs/quickstart/backend/ruby) tutorial [downloads](https://github.com/auth0/docs/blob/master/articles/server-apis/ruby/authenticate.md) ruby on rails web app project, not ruby api seed project (AUTH-3458)

**Comment by chenkie** [comment]
Fixed

**Comment by camimonse** [comment]
Sanity passed
