### ISSUE TITLE
Missing Instruction Cordova Readme.md

### ISSUE THREAD

**Issue by mehreencs87** [auth0/docs#2552]
In order to run the project, you need to have node, cordova and ios-sim installed. Once you have that, just clone the project and run the following:
1. cordova platform add ios
2. cordova build ios
3. cordova emulate ios

Enjoy your Cordova app now :).

![cordova](https://cloud.githubusercontent.com/assets/14890513/19442267/365d882e-94a2-11e6-844f-ce0c26ba8a62.PNG)

**Comment by mehreencs87** [comment]
AUTH-3457

**Comment by camimonse** [comment]
this fixes #3457

**Comment by chenkie** [comment]
Merged PR in the sample 👍
