### ISSUE TITLE
Jquery tutorial hardcoded lock library url 

### ISSUE THREAD

**Issue by mehreencs87** [auth0/docs#2554]
[Jquery](https://auth0.com/docs/quickstart/spa/jquery#2-dependencies) tutorial contains [hardcoded](https://github.com/auth0/docs/blob/master/articles/client-platforms/jquery/00-intro.md) url to cdn instead of using variable `${lockURL}` (AUTH-3459)

![jquery](https://cloud.githubusercontent.com/assets/14890513/19443012/ce2cf912-94a4-11e6-916a-ab93bfff2187.PNG)

**Comment by camimonse** [comment]
Sanity passed
