### ISSUE TITLE
VanillaJS tutorial hardcoded lock library url

### ISSUE THREAD

**Issue by mehreencs87** [auth0/docs#2555]
[VanillaJS tutorial](https://auth0.com/docs/quickstart/spa/vanillajs#2-dependencies) contains [hardcoded](https://github.com/auth0/docs/blob/master/articles/client-platforms/vanillajs/00-intro.md) url to cdn instead of using variable `${lockURL}`(AUTH-3460)
![vanilla](https://cloud.githubusercontent.com/assets/14890513/19444481/1187c250-94aa-11e6-8130-c8f13d90c96d.PNG)

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/2566

**Comment by camimonse** [comment]
Sanity passed
