### ISSUE TITLE
Typo On VanillaJS Tutorial

### ISSUE THREAD

**Issue by mehreencs87** [auth0/docs#2556]
On [VanillaJS Tutorial](https://auth0.com/docs/quickstart/spa/vanillajs#2-dependencies)![vanilla](https://cloud.githubusercontent.com/assets/14890513/19444813/701511c8-94ab-11e6-82bb-745c094e2c77.PNG)
(AUTH-3461)

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/2566

**Comment by camimonse** [comment]
Sanity passed
