### ISSUE TITLE
react tutorial not visible links

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2558]
[React tutorial](https://auth0.com/docs/quickstart/spa/react/08-calling-apis#2-create-a-simple-server) contains links that are not different from the embed code. (AUTH-3464)
![image](https://cloud.githubusercontent.com/assets/1114365/19446030/a2594778-949f-11e6-8bb6-f1180d5f5fe7.png)

**Comment by camimonse** [comment]
Sanity passed
