### ISSUE TITLE
Angular 2 Single Page App Typo Found

### ISSUE THREAD

**Issue by rafanog** [auth0/docs#2582]
In the [Angular 2 Single Page App](https://auth0.com/docs/quickstart/spa/angular2/04-user-profile#update-the-user-s-profile) tutorial, in the "update user's profile" part of the "user's profile" section, says that in order to use the `AuthHttp` helper from `angular2-jwt`, the first thing you need to do is to add `AUTH-PROVIDERS` from the **`angular-jwt`** library, this is wrong, it should make reference to **`angular2-jwt`** as shown on the code snippet.
![typo-making reference to an angular-jwt library](https://cloud.githubusercontent.com/assets/15782359/19505481/c351aea6-9590-11e6-8370-fbffd3c2c3d8.PNG)

This issue refers to the Auth0 ticket number 3348

**Comment by mpaktiti** [comment]
Thank you @rafanog ! It's fixed now. 👍

**Comment by camimonse** [comment]
sanity passed
