### ISSUE TITLE
Angular 2 Single Page App Lock version referenced is outdated

### ISSUE THREAD

**Issue by rafanog** [auth0/docs#2584]
In the [Angular 2 Single Page App](https://auth0.com/docs/quickstart/spa/angular2/00-intro) the lock version referenced is outdated.
![captura1](https://cloud.githubusercontent.com/assets/15782359/19878872/c9ecd7c6-9fc3-11e6-8062-905f786d6be2.JPG)

And also in the seed project, at the `README.md` file included: 
![captura2](https://cloud.githubusercontent.com/assets/15782359/19878873/cf628ad4-9fc3-11e6-9ba0-8f624ec26f44.PNG)

This issue refers to the Auth0 ticket number 3348

**Comment by vmartynets** [comment]
Up-to-date version is 10.6 and tutorial alread [updated](https://auth0.com/docs/quickstart/spa/angular2/00-intro#add-the-dependencies). Issue can be closed.
