### ISSUE TITLE
java tutorial outdated lock

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2600]
(AUTH-3493)
Snippet in [java tutorial](https://auth0.com/docs/quickstart/webapp/java/01-login#display-lock-widget) contains outdated lock library.
![image](https://cloud.githubusercontent.com/assets/1114365/19603233/09e01d06-97b9-11e6-8169-973da45129fc.png)

**Comment by camimonse** [comment]
Sanity Passed
