### ISSUE TITLE
vue.js logout not displayed properly 

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2611]
Issue https://github.com/auth0-samples/auth0-vue-samples/issues/9 also affects tutorial. (AUTH-3501)

**Comment by mpaktiti** [comment]
Hello @Amialc Is this the same issue as reported here https://github.com/auth0-samples/auth0-vue-samples/issues/9 or something else on the tutorial?

**Comment by vmartynets** [comment]
Hi, @mpaktiti, same. I've created app following tutorial steps and it also have this problem.
