### ISSUE TITLE
java spring security + API seeds projects missing parameter

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2640]
Seed projects [Java spring security tutorial](https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc) comes without parameter. (AUTH-3508)
![image](https://cloud.githubusercontent.com/assets/1114365/19738201/2cb9c782-9bbf-11e6-9c1c-b73876f5be05.png)

**Comment by vmartynets** [comment]
Same for seed projects from [Java spring security API tutorial](https://auth0.com/docs/quickstart/backend/java-spring-security)

**Comment by vmartynets** [comment]
Same for [spring mvc seed projects](https://github.com/auth0-samples/auth0-spring-mvc-sample)

**Comment by chenkie** [comment]
Fixed all seeds
