### ISSUE TITLE
java spring security no system requirements

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2642]
[Java spring security tutorial](https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc/00-intro) have no system requirements. (AUTH-3510)
![image](https://cloud.githubusercontent.com/assets/1114365/19738376/dab0a176-9bbf-11e6-9a4c-2e9a72dc7980.png)

**Comment by mpaktiti** [comment]
Fixed https://github.com/auth0/docs/pull/2650
