### ISSUE TITLE
Format discrepancy in the quickstarts

### ISSUE THREAD

**Issue by iannyanes** [auth0/docs#2644]
Any user can access a quickstart from 2 sites:
1. Going to auth0.com/docs and selecting the quickstart they want to read, i.e.: iOS swift
   https://auth0.com/docs/quickstart/native/ios-swift/01-login
2. From the client list in the dashboard to have all the seed projects configured with the specific client id and client secret keys
   https://manage.auth0.com/#/clients/CLIENT_ID/quickstart

these 2 presentations of the same document have different formats when dealing with the seed project download button. Please see the screenshots for option 1:

<img width="1440" alt="discrepancyerror1" src="https://cloud.githubusercontent.com/assets/2512171/19743165/331c1aa4-9b96-11e6-8123-3c909a5d8424.png">

and the difference from the option 2:

<img width="1440" alt="discrepancyerror2" src="https://cloud.githubusercontent.com/assets/2512171/19743173/422b2396-9b96-11e6-84b2-db8eddef0c1a.png">

It should present in the same format or an ordered and predefined format for each presentation.

**Comment by iannyanes** [comment]
Techaid Ticket https://techaid.atlassian.net/browse/AUTH-3511

**Comment by chenkie** [comment]
Caching issue
