### ISSUE TITLE
Unclear instruction in the PHP Symfony tutorial

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2651]
In https://auth0.com/docs/quickstart/webapp/symfony at the bottom of the tutorial, as final note, it says: _"There is an issue with CAs database on your computer. Need to download this CAs database..."_

Problem:
It doesn't say whether I have to do it, or I just have to considerate it, or if somehow Auth0 knows that I actually have that problem and that is why is telling me.

Improve:
To add **"If"** at the beginning:

![image](https://cloud.githubusercontent.com/assets/18585436/19772517/7f9fd7fa-9c34-11e6-8f0a-9de6bda4d0b9.png)

**Comment by camimonse** [comment]
this refers to GitHub ticket number 3518

**Comment by camimonse** [comment]
Sanity passed

**Comment by camimonse** [comment]
@mpaktiti This issue should be closed, cause it is been already merged. The issue is fixed :)

**Comment by mpaktiti** [comment]
Thanks @camimonse ! 👍
