### ISSUE TITLE
Firebase outdated instructions

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2653]
Firebase secrets are now located in Settings -> Database, not on dashboard. Url for database secrets `https://console.firebase.google.com/project/<project-name>/settings/database`. Screenshot must be updated too. (AUTH-3519)
![image](https://cloud.githubusercontent.com/assets/1114365/19775365/dbec644e-9c78-11e6-98e5-1f5d5d462bec.png)

**Comment by angelaLazar** [comment]
@Amialc This page is part of the manage site (https://github.com/auth0/manage), not the docs site. Please submit a request with crew-2

I have updated the docs site relevant instructions: https://github.com/auth0/docs/pull/2936
