### ISSUE TITLE
Different version of same quickstart on Chrome and Firefox

### ISSUE THREAD

**Issue by iannyanes** [auth0/docs#2666]
Some of the quickstarts have been migrated to the new template where the user is able to download several seed projects, one per action (Login, Linking accounts, etc)

If you access the following quickstart from the dashboard:

https://manage.auth0.com/#/clients/CLIENT_ID/quickstart

and select the iOS Swift quickstart, the following will happen:

On firefox, the user will see the new template with all the seed projects:
<img width="1435" alt="firefoxcorrectdisplay" src="https://cloud.githubusercontent.com/assets/2512171/19839077/ec009502-9ea9-11e6-98ba-12cfeb09c201.png">

BUT

In Google Chrome, the user will only see the old version of the tutorial. With one seed project.

<img width="1438" alt="chromeincorrectdisplay" src="https://cloud.githubusercontent.com/assets/2512171/19839081/040693cc-9eaa-11e6-9b1d-7f0114b2e3a8.png">

The quickstart presented should be the same on any browser.

**Comment by iannyanes** [comment]
Techaid Ticket: https://techaid.atlassian.net/browse/AUTH-3524

**Comment by chenkie** [comment]
@iannyanes can you try clearing the cache in Firefox? We recently changed rendering in manage.

**Comment by chenkie** [comment]
Checked on mine and it was fine. Likely a caching issue.
