### ISSUE TITLE
Ember.js Single Page App ember-simple-auth outdated on tutorial

### ISSUE THREAD

**Issue by rafanog** [auth0/docs#2670]
In the [Ember.js Single Page App](https://auth0.com/docs/quickstart/spa/emberjs) tutorial, the ember-simple-auth dependency mentioned is oudated, as shown here:

![system requirements outdated](https://cloud.githubusercontent.com/assets/15782359/19843466/0d525322-9ef9-11e6-83dc-c652e569f596.JPG)

The last version of this dependency is V 1.1.0

TechAid Ticket: AUTH-3357

**Comment by vmartynets** [comment]
Same in the [ember.js 2 tutorial](https://auth0.com/docs/quickstart/spa/ember2js)
![image](https://cloud.githubusercontent.com/assets/1114365/19856596/d7ad30cc-9f82-11e6-9044-1e2fc5608ffc.png)
