### ISSUE TITLE
Ember.js Single Page App missing ellipses at code snippets

### ISSUE THREAD

**Issue by rafanog** [auth0/docs#2671]
There are some missing ellipses in the code snippets of the [Ember.js Single Page App](https://auth0.com/docs/quickstart/spa/emberjs) tutorial.

1) At the "[Configure the add on](https://auth0.com/docs/quickstart/spa/emberjs#2-configure-the-add-on)" section, on the first snippet:
![missing ellipses](https://cloud.githubusercontent.com/assets/15782359/19843882/017ff528-9efd-11e6-97f0-b32f06ce25f3.JPG)

2) Second snippet, also at the "Configure the add on" section
![missing ellipses 2](https://cloud.githubusercontent.com/assets/15782359/19843858/c0815fbc-9efc-11e6-9c2c-59c884ab78f3.JPG)

TechAid ticket: AUTH-3357

**Comment by vmartynets** [comment]
Same in the [ember.js 2 tutorial](https://auth0.com/docs/quickstart/spa/ember2js)
![image](https://cloud.githubusercontent.com/assets/1114365/19856645/0ec277e8-9f83-11e6-9e26-cb5c60b23965.png)
