### ISSUE TITLE
Azure addons outdated links and screenshots

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#2679]
(AUTH-3536)
Link in step 1 points to [old dashboard](https://manage.windowsazure.com/), when new dashboard is [portal.azure.com](https://portal.azure.com)
![image](https://cloud.githubusercontent.com/assets/1114365/19862357/9e57925c-9f98-11e6-9a99-a15680b4ae20.png)

**Comment by vmartynets** [comment]
Same for Azure Service Bus addon
![image](https://cloud.githubusercontent.com/assets/1114365/19862454/118f8b12-9f99-11e6-835b-64f1758218e0.png)

**Comment by vmartynets** [comment]
Same for Azure Mobile Services addon
![image](https://cloud.githubusercontent.com/assets/1114365/21316509/c00a97f4-c609-11e6-9699-d5ef6fdd90cc.png)

**Comment by vmartynets** [comment]
also screenshots from addons are outdated, they show outdated dashboard.

**Comment by mpaktiti** [comment]
Hey, these docs are part of the manage repo, I moved the issue over there https://github.com/auth0/manage/issues/3137
