### ISSUE TITLE
Rule for Authorization Extension sets empty user.roles

### ISSUE THREAD

**Issue by FreeWillaert** [auth0/docs#2695]
The rule that comes with the Authorization Extension sets not only groups, but also users and permissions on the user:

```
// Update the outgoing token.
user.groups = data.groups;
user.roles = data.roles;
user.permissions = data.permissions;
```

However, roles seems to be always empty. In my case, it overwrites a 'roles' field that is set in another rule...
(and I think the same goes for permissions.)

Should this extension set user.roles? 
If no, please adjust the rule.
If yes, please tell me where those roles can be configured - I'd be interested.

**Comment by ntotten** [comment]
Unfortunately, we cannot provide support via github issues. Please post your question on our [forums](https://auth0.com/forum) or if you have a paid Auth0 account by opening a [support ticket](https://support.auth0.com).
