### ISSUE TITLE
Fix docs for Lock Dict options

### ISSUE THREAD

**Issue by cristiandouce** [auth0/docs#270]
The **etc...** is not a good way of pointing to the full i18n Document:
https://auth0.com/docs/libraries/lock/customization#4

Also make sure all the options are documented or at least pointed to the JSON file somehow in here:
https://auth0.com/docs/libraries/lock/i18n

There is no clear way for our users to find all the customizable string from the docs page.

**Comment by iannyanes** [comment]
Solved
