### ISSUE TITLE
Need to update picture to auth0 user

### ISSUE THREAD

**Issue by bishopedd** [auth0/docs#2757]
Hi,

I need to update a picture to a user in auth0 administration panel.
By default its Gravatar.
I see that i can modify metadata user, but when i try to update, that not works.

Can you help me please ?

**Comment by ntotten** [comment]
Unfortunately, we cannot provide support via github issues. Please post your question on our [forums](https://auth0.com/forum) or if you have a paid Auth0 account by opening a [support ticket](https://support.auth0.com).
