### ISSUE TITLE
Documentation for creating users in management api v2 is missing fields

### ISSUE THREAD

**Issue by ryanwalls** [auth0/docs#2801]
https://auth0.com/docs/api/management/v2#!/Users/post_users

Example body given in documentation:
```
{
  "connection": "Initial-Connection",
  "email": "john.doe@gmail.com",
  "username": "johndoe",
  "password": "secret",
  "phone_number": "+199999999999999",
  "user_metadata": {},
  "email_verified": false,
  "phone_verified": false,
  "app_metadata": {}
}
```

Note that it does not include fields like, `name`, `given_name`, `family_name`, etc that can be sent when creating a user.

**Comment by angelaLazar** [comment]
Hi @ryanwalls these fields are hidden fields in post user available because they cannot be patched. But I will add a note about these fields in the User Docs.
