### ISSUE TITLE
Improve documentation on Nonce

### ISSUE THREAD

**Issue by fredguth** [auth0/docs#2823]
The [nonce documentation](https://github.com/auth0/docs/edit/master/articles/api-auth/tutorials/nonce.md) helps us to understand why nonce is important and how to generate a nonce string, but it lacks an important part: how do I send the nonce string?

I am sure there is an explanation in Auth0 documentation, but it should be linked in the  [nonce documentation](https://github.com/auth0/docs/edit/master/articles/api-auth/tutorials/nonce.md) .

**Comment by rolodato** [comment]
It's sent as part of the authorization request. This is the [same example that the OIDC spec uses](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest):

```
  GET /authorize?
    response_type=id_token%20token
    &client_id=s6BhdRkqt3
    &redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb
    &scope=openid%20profile
    &state=af0ifjsldkj
    &nonce=n-0S6_WzA2Mj HTTP/1.1
  Host: server.example.com
```

This is also mentioned in the current doc:

> The nonce is generated by the client, sent as a `nonce` query string parameter in the authentication request, and included in the ID token response from Auth0.

**Comment by mpaktiti** [comment]
Hello @fredguth Looks like the doc includes this info so I'm going to close this issue. Thanks!
