### ISSUE TITLE
Update Architecture Scenarios

### ISSUE THREAD

**Issue by cabralmartin** [auth0/docs#2826]
For SPA + API and Mobile + API

- Update images (instead of sending `id_tokens` to APIs we send the `access_token`)
- Review and Update wording (e.g. `The id_token is used to securely call the API on behalf of the user. ` -> `the access_token is used to ..)
- Remove link to `Auth0 Access Token` as it describe the legacy token (we will re introduce this link later after we merge the update to Access Token document)

**Comment by mpaktiti** [comment]
Fixed https://github.com/auth0/docs/pull/2828
