### ISSUE TITLE
Advice usage of a single audience

### ISSUE THREAD

**Issue by cabralmartin** [auth0/docs#2827]
- We recommend as a best practice to have a single API defined in the dashboard that will represent all your existing APIs.
- The message we want to convey is: `99.99% of the times you can use a single API to represent all of your existing real life APIs`. 
- Explore the feasibility of doing this thru a case study on Microservices or any other viable alternative.

**Comment by mpaktiti** [comment]
https://github.com/auth0/docs/pull/3777

**Comment by mpaktiti** [comment]
Hey Martin, I merged the PR and I'm going to close this issue. If you think it's not fully covered please reopen this. Thanks.
