### ISSUE TITLE
Link name deprecated in PHP Web App

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2847]
In https://auth0.com/docs/quickstart/webapp/php there is a link with a deprecated name:

Change:

**Application --> Client** here:

![image](https://cloud.githubusercontent.com/assets/18585436/20632866/ef2bd76a-b316-11e6-8dc7-d7422b8034fe.png)

Reason:

 - Better UX: We don't call "apps" or "applications" anymore. Now those are called "Client" and the user may confuse
 - Integrity of the Auth0 page: Is good to handle the same concepts and name for everything Auth0 develops

Refers to the Auth0 Ticket number: 3369

**Comment by chenkie** [comment]
Merged PR
