### ISSUE TITLE
Log in rejected testing the custom UI from the PHP Web App tutorial

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2865]
Steps to reproduce the error:

1. go to https://auth0.com/docs/quickstart/webapp/php and follow the steps in the tutorial
2. when you are in the 4th step "Triggering Login Manually or Integrating Lock" copy the snippet from the **custom UI tab** and paste it on your own project.
3. test it out. Three options will appear, (sign in with google redirect, pop up or sign in with your email and password)
4. Choose the third option. Put your credentials and click "sign in with email/password"

Expected result: 
 - That the redirect URL opens in a new window

Real result:
 - The new window seems to be opening for 2 seconds and then it closes suddenly without charging the redirect URL
 

This refers to the Auth0 ticket number 3369

**Comment by vmartynets** [comment]
Related issue: https://github.com/auth0/docs/issues/3094
But particularly it expected behavior, you can update ui in callback function either delete callback function and use it like this:
```
auth0.signin({
   connection: 'Username-Password-Authentication',
   username: $('.username').val(),
   password: $('.password').val(),
});
```
Then it signin user and redirect after to callback url
