### ISSUE TITLE
URL does not sent magic link nor email with code

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2866]
In order to reproduce this error:
 
1. Go to https://auth0.com/docs/quickstart/webapp/php and follow the steps of the tutorial
2.  In the "Triggering Login Manually or Integrating Lock" copy the snippet from the passwordless tab (this error occurs with the magic link AND email code)
3. paste it on your own project and test it (you will need to provide a mail contact)

Expected result:

- That you receive an email with the respective information (eighter Code or magic link).

Real result:

- No mail is being sent (it's been a day now)

This issue refers to the Auth0 ticket number 3548

**Comment by vmartynets** [comment]
@camimonse this is caused by custom email provider. You can check it [here](https://manage.auth0.com/#/emails/provider).
