### ISSUE TITLE
Single Page App Vanilla.js Quickstart lock version outdated

### ISSUE THREAD

**Issue by rafanog** [auth0/docs#2868]
In the [Vanilla.js Single Page App quickstart](https://auth0.com/docs/quickstart/spa/vanillajs), the lock version is outdated on some parts of the tutorial:

 - At the [login section](https://auth0.com/docs/quickstart/spa/vanillajs/01-login#1-add-the-auth0-scripts-and-set-the-viewport), in the first step, the lock version referenced in the snippet is outdated:
![lock version is outdated on the login section](https://cloud.githubusercontent.com/assets/15782359/20739144/963bcab8-b68e-11e6-8fae-6de74b97fcbf.JPG)

 - At the seed project's README.md at the "Important snippets" section.
![lock version is outdated on the readme](https://cloud.githubusercontent.com/assets/15782359/20739178/eab97d2e-b68e-11e6-90e5-ff305aed7e26.JPG)

 - The version referenced on the seed project's at the index.html file.
![lock version is outdated on the index page of the sp](https://cloud.githubusercontent.com/assets/15782359/20739249/783b62de-b68f-11e6-8697-f5a5dab70b58.JPG)

Techaid Ticket: AUTH-3356

**Comment by rafanog** [comment]
The issue is still present on the README.md's file:
![lock version is outdated on sp s readme](https://cloud.githubusercontent.com/assets/15782359/22349812/c37f49a6-e3e7-11e6-9456-60628a6407b6.JPG)

**Comment by Annyv2** [comment]
For the README.md file issue, please create the issue on the sample's repository if it still applies
