### ISSUE TITLE
PHP Web App tutorial failed, ambiguity in the instructions

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2875]
Context:

- We go to https://auth0.com/docs/quickstart/webapp/php and start following the steps in the tutorial in our own project
-  We have in our folder the dependencies (vendor file, composer.json and composer.lock), besides, we have:

   * plugin.php: with the code on the first snippet 
   * callback.php: with the code on the second snippet
   * index.php: with the 'Lock' code on the third snippet.
   * info.php: with the code on the fourth snippet in the tutorial.

- We put the respective redirect URL in the auth0 dashboard, and we are all set to test the login button in our project.

Expected result:

- That after entering credentials in the Auth0 Lock we go to the redirect URL that we set before

Real result: 

- We have the following bug:
![image](https://cloud.githubusercontent.com/assets/18585436/20765237/d441e9ea-b707-11e6-938d-710487b7b057.png)

The "Line 4" refers to:
![image](https://cloud.githubusercontent.com/assets/18585436/20765255/ee62a350-b707-11e6-8268-d809620df1cd.png)

Problem:

- The tutorial instructions are ambiguous. 
- Even though we are following as the tutorials says, it displays an error. 
- Information is missing. If anything has to be added, the respective explanation must be in the tutorial.

**Comment by camimonse** [comment]
This refers to Auth0 ticket number 3552

**Comment by vmartynets** [comment]
Part of #3095. The problem is that tutorial is not adapted to the new version of auth0-php
