### ISSUE TITLE
Misspellings and grammatical errors found in the PHP lavarel Web App tutorial

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2881]
In the PHP lavarel Web App tutorial: https://auth0.com/docs/quickstart/webapp/laravel are Misspellings and grammatical errors found.

1. 
 - lastest --> latest
![image](https://cloud.githubusercontent.com/assets/18585436/20807166/316ee63c-b7d4-11e6-8512-6faf16688623.png)

2.
 - in --> to
![image](https://cloud.githubusercontent.com/assets/18585436/20806610/0287f1ee-b7d2-11e6-99d8-8be3441d0509.png)

3. 
 - hookup --> hook up
 - a --> an
![image](https://cloud.githubusercontent.com/assets/18585436/20806760/87cea7c6-b7d2-11e6-9bd3-4004d90f2791.png)

4. 
 - event --> even
 - advaced --> advanced
![image](https://cloud.githubusercontent.com/assets/18585436/20807061/d10c0f0e-b7d3-11e6-889a-64793a306c48.png)

**Comment by camimonse** [comment]
This refers to Auth0 ticket number 3553

**Comment by ofhope** [comment]
In this case _a URI_ correct. As URI is an abbreviation, it's pronounced with a Yew sound, witch is not a vowel sound.  _A unicorn_ or _an herb_ are both correct in American English.

**Comment by chenkie** [comment]
Merged

**Comment by camimonse** [comment]
right! @bambii7 thanks!
