### ISSUE TITLE
Passwordless SMS has broken links

### ISSUE THREAD

**Issue by fiddur** [auth0/docs#2886]
In https://auth0.com/docs/connections/passwordless/sms there's two links to Web Tutorials.  Both links are broken:

* [Single-page Applications](https://auth0.com/docs/spa-sms)
* [Regular Web Applications](https://auth0.com/docs/regular-web-app-sms)

**Comment by mpaktiti** [comment]
Fixed https://github.com/auth0/docs/pull/2891
