### ISSUE TITLE
Grammatical errors found in JAVA Web App 

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2926]
In https://auth0.com/docs/quickstart/webapp/java are some grammatical errors found

## **Introduction:**
1.
- following --> follow
- take out the first two "along" 

![image](https://cloud.githubusercontent.com/assets/18585436/21014219/8b9791b8-bd33-11e6-8d9f-3f1a619f73ba.png)

2.
add commas
![image](https://cloud.githubusercontent.com/assets/18585436/21014302/d77282e6-bd33-11e6-9905-1e488b937fa6.png)

![image](https://cloud.githubusercontent.com/assets/18585436/21014347/074f5728-bd34-11e6-95d8-b8d5fcee6874.png)

![image](https://cloud.githubusercontent.com/assets/18585436/21014403/4609582e-bd34-11e6-8ed0-27ff3dd65148.png)

3.
- add "the" --> "according to **the** configuration
![image](https://cloud.githubusercontent.com/assets/18585436/21014475/999d4fc2-bd34-11e6-83c7-5e2d3726f023.png)

## **Login**

1.
- add comma
![image](https://cloud.githubusercontent.com/assets/18585436/21015238/9f8542d4-bd37-11e6-8882-f2e57f445d64.png)

2.
- setup --> set up
![image](https://cloud.githubusercontent.com/assets/18585436/21016244/504a6240-bd3b-11e6-8da3-ecb818623f6d.png)

3.
- Logout --> Log out
![image](https://cloud.githubusercontent.com/assets/18585436/21015939/2a64ca3a-bd3a-11e6-9ccb-fd9267f1fef5.png)

## **Multifactor Authentication**

1.
- add comma
- erase ":"

![image](https://cloud.githubusercontent.com/assets/18585436/21017379/902d69f8-bd3f-11e6-9b48-b9fc1e7d8c03.png)

**Comment by camimonse** [comment]
Auth0 ticket 3561

**Comment by mpaktiti** [comment]
Fixed
