### ISSUE TITLE
Angular2 Single Page App Lock version outdated on seed project's README.md

### ISSUE THREAD

**Issue by rafanog** [auth0/docs#2937]
In the [Angular2 Single Page App quickstart](https://auth0.com/docs/quickstart/spa/angular2) the lock version shown on the seed project's README.md's **Important snippets** section is outdated:

 
![lock version outdated on readme](https://cloud.githubusercontent.com/assets/15782359/21029634/1bc08618-bd71-11e6-856c-7f1e2e3b1363.JPG)

Ticket AUTH - 3348

**Comment by chenkie** [comment]
Fixed
