### ISSUE TITLE
typo found

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2943]
In  https://auth0.com/docs/quickstart/backend/rails there is a typo found:

Informations --> information
![image](https://cloud.githubusercontent.com/assets/18585436/21054906/cb35729a-be05-11e6-8dfc-e6ba33db36a6.png)

Auth0 ticket: 3564

**Comment by chenkie** [comment]
Merged the PR. @camimonse for future ones like this, can you put "Fix #xx" in the PR title? So it will self close on merge :)

**Comment by camimonse** [comment]
@chenkie ok 👍
