### ISSUE TITLE
Wrong link in PHP Laravel API

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2961]
In https://auth0.com/docs/quickstart/backend/php-laravel the following links does not redirect to where it supposed to:

![image](https://cloud.githubusercontent.com/assets/18585436/21110319/27a110b0-c073-11e6-8be8-ad9b33137548.png)

- Expected result:
that it takes you to: https://auth0.com/docs/user-profile/normalized

- Real result:
It takes you to: https://auth0.com/docs/user-profile

Auth0 Ticket: 3572

**Comment by mpaktiti** [comment]
Fixed
