### ISSUE TITLE
Grammatical errors and typos found in ASP.NET Core Web API tutorial

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2972]
In https://auth0.com/docs/quickstart/backend/aspnet-core-webapi/03-authentication-hs256 there are some errors found:

## Authentication with HS256
- your --> you 
![image](https://cloud.githubusercontent.com/assets/18585436/21148358/5366797c-c12e-11e6-831d-4bf954fef07f.png)

- add comma
![image](https://cloud.githubusercontent.com/assets/18585436/21148450/a8641740-c12e-11e6-8116-2ae91a111ebb.png)

Auth0 ticket 3579

**Comment by mpaktiti** [comment]
Merged
