### ISSUE TITLE
Three depracated links in the ASP.NET Core Web API Authentication tutorial

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2974]
In https://auth0.com/docs/quickstart/backend/aspnet-core-webapi/01-authentication

Problem:

We find links to deprecated tutorials, see photo below:

![image](https://cloud.githubusercontent.com/assets/18585436/21152318/25a52caa-c13c-11e6-9785-7476d13877a6.png)

Auth0 ticket: 3581

**Comment by mpaktiti** [comment]
@camimonse I think that's the way it's supposed to be for the time being.

@chenkie Is that an issue? By the way a panel, on the top of these pages, with some details on the deprecation might be useful.
