### ISSUE TITLE
Unnecessary capitalized letters in the Python API tutorial

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2984]
In https://auth0.com/docs/quickstart/backend/python are Unnecessary capitalized letters, see photo below:

![image](https://cloud.githubusercontent.com/assets/18585436/21187290/c827e1dc-c1ed-11e6-805e-31ff8b6fd9a4.png)

Auth ticket: 3582

**Comment by mpaktiti** [comment]
Merged
