### ISSUE TITLE
Grammatical error found in the Backend PHP API tutorial

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2988]
In https://auth0.com/docs/quickstart/backend/php#define-apache_request_headers-if-not-available 
is a grammatical error found

- in --> on

![image](https://cloud.githubusercontent.com/assets/18585436/21192439/f4964dec-c1fe-11e6-9b20-47447e05f10d.png)

- FrontEnd ... Backend --> frontend ... backend 
![image](https://cloud.githubusercontent.com/assets/18585436/21193458/be623494-c202-11e6-8ccf-927dcf045643.png)

Auth ticket: 3583

**Comment by mpaktiti** [comment]
Merged
