### ISSUE TITLE
Insctruction not understandable

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2989]
In https://auth0.com/docs/quickstart/backend/php#define-apache_request_headers-if-not-available
tutorial the 3rd step is not understandable without "/secured" indicating is part of the code

![image](https://cloud.githubusercontent.com/assets/18585436/21193079/51ad45ce-c201-11e6-8123-858262f168a6.png)

It has to be like this photo below:
![image](https://cloud.githubusercontent.com/assets/18585436/21193343/5b91a408-c202-11e6-8365-44b828ddfde3.png)

Auth0 ticket 3584

**Comment by mpaktiti** [comment]
Merged
