### ISSUE TITLE
Grammatical errors in the GO tutorial

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2993]
In https://auth0.com/docs/quickstart/backend/golang are some errors found 

- add article (so we do the instruction more understandable)

![image](https://cloud.githubusercontent.com/assets/18585436/21194219/814d8eca-c205-11e6-9cd7-f8d04107b06e.png)

- Add the either / or clause:
 "You can do so using net/http handlers or using negroni middlewares as well." --> "You can do so using **either** net/http handlers **or** negroni middlewares."

![image](https://cloud.githubusercontent.com/assets/18585436/21194547/bf82a580-c206-11e6-9069-2512b05ff998.png)

- unnecessary capital letters:

![image](https://cloud.githubusercontent.com/assets/18585436/21194713/48133360-c207-11e6-9d09-d185490d0e9f.png)

Auth0 ticket: 3585

**Comment by mpaktiti** [comment]
Merged
