### ISSUE TITLE
Improving the instructions' grammar

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2995]
In https://auth0.com/docs/quickstart/backend/aspnet-webapi there are some improvements we can do for a better understanding.
- for --> with

![image](https://cloud.githubusercontent.com/assets/18585436/21195895/1507ee84-c20c-11e6-984c-7d8a955cfac0.png)

- that --> if
![image](https://cloud.githubusercontent.com/assets/18585436/21196306/8bfb0192-c20d-11e6-9139-5eaa96333503.png)

- Change the capital letters to small letters 
![image](https://cloud.githubusercontent.com/assets/18585436/21197004/3adfceb6-c210-11e6-99d3-53848c4d556f.png)
 
Auth0 ticket 3586

**Comment by mpaktiti** [comment]
Merged
