### ISSUE TITLE
Words missing in Spring Security Java API

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#2999]
In https://auth0.com/docs/quickstart/backend/java-spring-security are some words missing for a better understanding, and also a grammatical error.

## Introduction

- add article: "the"

![image](https://cloud.githubusercontent.com/assets/18585436/21228487/527a7cfc-c2b4-11e6-9a5c-e618b121fa15.png)

- on this --> about it
![image](https://cloud.githubusercontent.com/assets/18585436/21229064/ad6d8a6c-c2b6-11e6-841d-2e857abf5ed0.png)

- add "project" 
![image](https://cloud.githubusercontent.com/assets/18585436/21229009/8688cd3a-c2b6-11e6-8d9f-3f23a39acb46.png)

- add commas
![image](https://cloud.githubusercontent.com/assets/18585436/21229403/dab07cea-c2b7-11e6-8a8a-8a9143c250c2.png)

Auth0 ticket: 3587

**Comment by mpaktiti** [comment]
Fixed https://github.com/auth0/docs/pull/3002
