### ISSUE TITLE
Ember generate simple-lock fails

### ISSUE THREAD

**Issue by thijsvdanker** [auth0/docs#300]
The [Ember.js documentation](https://github.com/auth0/docs/blob/master/articles/client-platforms/emberjs.md) says you need to run

```
ember generate simple-lock
```

This returns

```
Unknown blueprint: simple-lock
```

I've checked the available generators for auth0-ember-simple-auth and they are:
- auth0-ember-simple-auth <name>
- authenticator <name>
  - Create a new authenticator based on auth0-ember-simple-auth
- authorizer <name>
  - Create a new authenticator based on auth0-ember-simple-auth
- scaffold-auth0 <name>

**Comment by tehsis** [comment]
Hi @thijsvdanker! The docs were updated. We've just fix them. 
Thanks for noticing.
