### ISSUE TITLE
Grammatical errors Spring Security Java API

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#3000]
In https://auth0.com/docs/quickstart/backend/java-spring-security/01-authentication are some words missing for the best understanding, and also a grammatical error.

**Authentication:**

- add commas
![image](https://cloud.githubusercontent.com/assets/18585436/21229706/dff7e17e-c2b8-11e6-9850-f01186385d04.png)
![image](https://cloud.githubusercontent.com/assets/18585436/21229744/fd925a84-c2b8-11e6-81e8-5bfbf08f9a92.png)

- add article: "a"
![image](https://cloud.githubusercontent.com/assets/18585436/21229940/aeb892a6-c2b9-11e6-9999-18bec377293a.png)

- add "project"
![image](https://cloud.githubusercontent.com/assets/18585436/21230206/8b815510-c2ba-11e6-9e89-6d65f6d3f455.png)

- property --> attribute (Cause in the _introduction page_ it is called so in the table)
![image](https://cloud.githubusercontent.com/assets/18585436/21230361/1928f544-c2bb-11e6-8b07-81da1756e099.png)

Auth ticket 3588

**Comment by mpaktiti** [comment]
Merged
