### ISSUE TITLE
Grammatical errors in the Spring Security Java API tutorial

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#3001]
In https://auth0.com/docs/quickstart/backend/java-spring-security/02-authorization are some errors found:

## Authorization:
- role based --> role-based 
![image](https://cloud.githubusercontent.com/assets/18585436/21230994/1f364ac0-c2bd-11e6-934f-c41fb678dc21.png)

- add commas:
![image](https://cloud.githubusercontent.com/assets/18585436/21231113/7c3df66e-c2bd-11e6-801d-52b6bfa3da16.png)

![image](https://cloud.githubusercontent.com/assets/18585436/21231620/4f64ba90-c2bf-11e6-846c-a68ee80288e8.png)

Auth0 ticket 3589

**Comment by mpaktiti** [comment]
Fixed https://github.com/auth0/docs/pull/3004
