### ISSUE TITLE
Errors in ASP.NET Web API (OWIN)  found

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#3005]
In https://auth0.com/docs/quickstart/backend/webapi-owin/ are some errors found

 ## Authentication:

- erase "r" --> you are
![image](https://cloud.githubusercontent.com/assets/18585436/21234910/011beeb0-c2cb-11e6-9dc8-5abf8830e3c4.png)

- add comma
![image](https://cloud.githubusercontent.com/assets/18585436/21235015/6918d2bc-c2cb-11e6-8805-39a7ee31c602.png)

## API Authorization:

- add hyphen
![image](https://cloud.githubusercontent.com/assets/18585436/21235268/778eda2a-c2cc-11e6-85f9-2aa74a2b11c5.png)
![image](https://cloud.githubusercontent.com/assets/18585436/21235320/a8bd0298-c2cc-11e6-9b6f-7d9391913f52.png)

- add comma
![image](https://cloud.githubusercontent.com/assets/18585436/21235291/8d940642-c2cc-11e6-96fa-0871585a3a14.png)

- configure --> configured
![image](https://cloud.githubusercontent.com/assets/18585436/21235357/c8222028-c2cc-11e6-8c45-d2859a98b620.png)

- the --> to
![image](https://cloud.githubusercontent.com/assets/18585436/21235642/feb57a08-c2cd-11e6-8cf2-4ae2fa8b3c75.png)

Auth0 ticket 3590

**Comment by mpaktiti** [comment]
All merged
