### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#3009]
In https://auth0.com/docs/quickstart/backend/webapi-owin/02-authorization

the folllowing link doesn't work: 

![image](https://cloud.githubusercontent.com/assets/18585436/21236795/cedfe340-c2d2-11e6-841a-817f0a7316e1.png)
(https://auth0.com/docs/%22https:/manage.auth0.com#/apis)

Solution:
 - It should redirect to: https://manage.auth0.com/#/apis

Auth0 ticket 3591

**Comment by mpaktiti** [comment]
Merged
