### ISSUE TITLE
Errors and typo found in the Java Spring Security tutorial

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#3024]
In https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc there are some errors and a typo found:

## Introduction:
- add "with"
- erase "along"
- add "project"
- add commas

![image](https://cloud.githubusercontent.com/assets/18585436/21269263/7423f1e2-c388-11e6-88ac-0e1c4ac83688.png)

- logout --> log out
![image](https://cloud.githubusercontent.com/assets/18585436/21269588/a227e53e-c389-11e6-8fdb-e11bd6561944.png)

- add article
![image](https://cloud.githubusercontent.com/assets/18585436/21269527/6578cfd6-c389-11e6-8d4f-95194f14437b.png)
![image](https://cloud.githubusercontent.com/assets/18585436/21269913/fb7f8f50-c38a-11e6-9995-d372d5d3cc5f.png)
![image](https://cloud.githubusercontent.com/assets/18585436/21270001/35eaefae-c38b-11e6-986a-5030f16f9fae.png)

## Custom Login

- Add commas
![image](https://cloud.githubusercontent.com/assets/18585436/21270988/5bd6fa92-c38f-11e6-8934-8e3e931aea33.png)
![image](https://cloud.githubusercontent.com/assets/18585436/21271001/6efd5ecc-c38f-11e6-8d15-eca8bd2fdfe6.png)
![image](https://cloud.githubusercontent.com/assets/18585436/21271019/8d9afbdc-c38f-11e6-99ab-e54619d03dd4.png)

- login --> log in (cause is a verb)
![image](https://cloud.githubusercontent.com/assets/18585436/21271055/b71cda5c-c38f-11e6-8b67-016b7d8f300b.png)

- change order of the sentence 
![image](https://cloud.githubusercontent.com/assets/18585436/21270947/2a239488-c38f-11e6-94c7-1b48007953af.png)

## Rules:

- add comma
- add article "the" 
![image](https://cloud.githubusercontent.com/assets/18585436/21271206/6babd716-c390-11e6-8dc1-c418e06a906c.png)

- login --> log in
![image](https://cloud.githubusercontent.com/assets/18585436/21271265/a9921342-c390-11e6-9f1b-c94e4bb3a81d.png)

- thi --> this
![image](https://cloud.githubusercontent.com/assets/18585436/21271528/b43efd2c-c391-11e6-9849-59683dbc5e0f.png)

## Multifactor Authentication

- add comma
![image](https://cloud.githubusercontent.com/assets/18585436/21271358/1716fd92-c391-11e6-87af-f8775afe9dd0.png)

- erase spaces
![image](https://cloud.githubusercontent.com/assets/18585436/21271396/3d822a56-c391-11e6-81f3-578332c21539.png)

Auth0 ticket 3594

**Comment by mpaktiti** [comment]
All merged.
