### ISSUE TITLE
salesforce addons broken links

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#3053]
(AUTH-3605)
Links `this article` in salesforce addons page are broken. You get redirected to blank page.
![image](https://cloud.githubusercontent.com/assets/1114365/21358173/8b5fffe4-c6e0-11e6-85e8-48de968b3561.png)
![image](https://cloud.githubusercontent.com/assets/1114365/21358256/cd7940fc-c6e0-11e6-8f9d-bca3fbf28c25.png)
![image](https://cloud.githubusercontent.com/assets/1114365/21358374/2f3b4826-c6e1-11e6-85cc-899d322ccc99.png)

**Comment by mpaktiti** [comment]
Hey, these docs are part of the `manage` repo, I moved the issue over there https://github.com/auth0/manage/issues/3136
