### ISSUE TITLE
React API demo throwing unauthorized

### ISSUE THREAD

**Issue by bmmathe** [auth0/docs#3075]
I'm downloaded the API example: https://auth0.com/docs/quickstart/spa/react/08-calling-apis
After fixing an issue with the packages npm start script to get it running in WINDOWS I get an Unauthorized "invalid signature" error when hitting the private api endpoint.
I followed another thread's advice to change port from 3000 to something else but that also didn't work.
Is this a Windows only issue?

**Comment by bmmathe** [comment]
https://github.com/auth0/node-jsonwebtoken/issues/208

@mgkeen solution in the above thread fixed my issue for this example.

`var authenticate = jwt({
  secret: new Buffer(process.env.AUTH0_SECRET, 'base64'),
  audience: process.env.AUTH0_CLIENT_ID
});`

**Comment by miro-ur** [comment]
Having the same issue on Win10. Deployed on Ubuntu is fine. Could not figure out a fix for NodeJS on win ? What is the solution here ?

**Comment by bmmathe** [comment]
Locate package.json in the root folder.
In the "scripts" section change the dev-server line to the following:
`"dev-server": "cross-env NODE_ENV=development hjs-dev-server"`
