### ISSUE TITLE
Missing redirection in native subdirectory

### ISSUE THREAD

**Issue by ggonzaleza** [auth0/docs#3099]
There are URLs returning 404 errors that should be redirected to the new subdirectory.

For example:
https://auth0.com/docs/quickstart/native-mobile/android/ruby should redirect to
https://auth0.com/docs/quickstart/native/android/ruby
<img width="974" alt="screen shot 2016-12-26 at 4 01 48 pm" src="https://cloud.githubusercontent.com/assets/6827996/21485676/463ca198-cb85-11e6-9ca2-bced34704545.png">

**Comment by mpaktiti** [comment]
This PR fixes it https://github.com/auth0/docs/pull/3115

Note that this URL https://auth0.com/docs/quickstart/native/android/ruby does not exist, so https://auth0.com/docs/quickstart/native-mobile/android/ruby redirects to
https://auth0.com/docs/quickstart/native/android

The fix should be live in a couple of hours.

@nkohari
