### ISSUE TITLE
SAML Identity Provider Configuration: fix "Entity ID" value

### ISSUE THREAD

**Issue by siacomuzzi** [auth0/docs#3147]
Currently, we are showing only the default value:

```
urn:auth0:${account.tenant}:${connectionName}
```

We should also use `connection.options.entityId` (if exists):

```
connection.options.entityId || urn:auth0:${account.tenant}:${connectionName}
```

Affected document: https://github.com/auth0/docs/blob/master/articles/protocols/saml/samlp.md

**Comment by khorne3** [comment]
https://github.com/auth0/docs/pull/3585
