### ISSUE TITLE
Auth0.js [v8] README / Docs - Migration and passwordless

### ISSUE THREAD

**Issue by jonashaefele** [auth0/docs#3156]
I reported this on another repo, but the issue got prematurely closed:
See https://github.com/auth0/auth0.js/issues/287

I just tried to migrate from auth0.js v7.x to v 8.0.1 but got stuck even after reading through the code examples and some of the source code.

The docs are very patchy and inconsistent.

https://auth0.com/docs/libraries/auth0js uses v7.4 without explicitly mentioning it.

NPM/Github Readmes refer to v8, but omit any hints on how to migrate from v 7.x to v8.x
Readme.md for v8 lacks any reference to passwordless logins which were supported in v7.x

Helpful additions to the v8 README.md (at https://github.com/auth0/auth0.js/blob/master/README.md) would be:

- basic migration guide
- documentation on how passwordless works in v8

Helpful for the docs (this repo) would be:

- basic migration guide
- update examples to use v8

**Comment by mpaktiti** [comment]
Hello @jonashaefele ! Thanks for your input. We apologise for the confusion, v8 was released some days before we updated the docs. 

Yesterday we released an updated version of the [Auth0.js doc](https://auth0.com/docs/libraries/auth0js), using v8, and the migration guide is in progress this week. 

@jeffreylees can update you as soon as the migration guide is released so you can try your migration again, but in the meanwhile if we can help with something specific let us know.

**Comment by jeffreylees** [comment]
Just a quick update here - a basic migration guide for v8 will be published today or tomorrow. Passwordless information is not in there, as it needed a little more information due to the version changes, but it will be added within the next few days if all goes well (and added to the reference documentation). I'll update this ticket when the Passwordless info is added, before we close it.

**Comment by jonashaefele** [comment]
That's great, thanks! Will try to update again as soon as the docs are up.

**Comment by jeffreylees** [comment]
https://auth0.com/docs/libraries/auth0js/migration-guide also contains Passwordless info now, as does the main reference doc.

**Comment by jonashaefele** [comment]
Great, thanks @jeffreylees !
