### ISSUE TITLE
SAML instructions have fixed request binding type

### ISSUE THREAD

**Issue by nicosabena** [auth0/docs#3189]
In https://github.com/auth0/docs/blob/e6e16be3efab96ccd57d6df866b573d7119b1f8a/articles/protocols/saml/samlp.md, it says:

> The SAML Request Binding (sent to the IdP from Auth0): `HTTP-Redirect`

The `HTTP-Redirect` value is currently hard-coded, but it should take the value from `connection.options.protocolBinding`.

options.protocolBinding value | show
--------------------------------|------
"" or not present | HTTP-Redirect
urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect | HTTP-Redirect
urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST | HTTP-POST

If it's not possible to change the value dynamically, it should read something like this:

> The SAML Request Binding (sent to the IdP from Auth0): `HTTP-Redirect` (default) or `HTTP-POST` if this option was selected in **Protocol Binding**

**Comment by khorne3** [comment]
https://github.com/auth0/docs/pull/4725
