### ISSUE TITLE
Register user with CLI

### ISSUE THREAD

**Issue by srossross** [auth0/docs#3190]
After reading this doc https://github.com/auth0/docs/blob/master/articles/tutorials/using-auth0-to-secure-an-api.md I am curious if there is a way to register the user with a cli as well.

**Comment by jerriep** [comment]
@srossross Yes, you can register a user with a CLI by making use of the the [Auth0 Management API](https://auth0.com/docs/api/management/v2).

You will first need to generate an `access_token` to call the Management API (see https://auth0.com/docs/api/management/v2/tokens), and then you can call the [Create User](https://auth0.com/docs/api/management/v2#!/Users/post_users) endpoint of the API.

Depending on the platform you use, we may already have a SDK available which will make your life a bit easier, as you will not have to make the HTTP calls directly. Please see the [SDKs section of our Support Matrix](https://auth0.com/docs/support/matrix#sdks) for a list of SDKs.
