### ISSUE TITLE
Code snippets grammatical error found in Mobile App Android

### ISSUE THREAD

**Issue by nnats** [auth0/docs#3212]
On this 3 code snippets the double quotation marks for the parameters are missing:

https://auth0.com/docs/quickstart/native/android/01-login
![image](https://cloud.githubusercontent.com/assets/20141842/21970883/de1ef236-db89-11e6-89a7-5d1f937f62fc.png)

https://auth0.com/docs/quickstart/native/android/02-custom-login
![image](https://cloud.githubusercontent.com/assets/20141842/21970895/ee18ab1e-db89-11e6-8300-a10314977a08.png)

https://auth0.com/docs/quickstart/native/android/04-user-profile
![image](https://cloud.githubusercontent.com/assets/20141842/21970898/fc0c0392-db89-11e6-8a9c-ea0b10e071d5.png)

**Comment by lobo** [comment]
Will be fixed when those PRs are merged. Ideally in less than 24hs. Thanks so much for reporting!

**Comment by mpaktiti** [comment]
PRs merged, thanks guys 👍
