### ISSUE TITLE
Node API QuickStart doesn't work with Base64 encoded client secrets

### ISSUE THREAD

**Issue by chanoch** [auth0/docs#3328]
The application doesn't work if you use an existing, Base64 encoded client secret. Rotating the secret to a non encoded secret makes the express app work.

**Comment by chenkie** [comment]
It's a change that happened back in December. Since quickstarts show the latest integration steps, and since newly created clients don't have their secrets Base64 encoded, no decoding is done in the quickstart.

**Comment by chanoch** [comment]
Sorry - I was suggesting that the article be updated to mention that in case someone else like me is starting a new app with an old secret...
