### ISSUE TITLE
Suggested modification to ionic2 quickstart application

### ISSUE THREAD

**Issue by chanoch** [auth0/docs#3329]
The current ionic2 quickstart application gives an example of a secured API. This is hidden is the user is not logged in. It may be worth adding in a third option to illustrate what happens when you attempt to access a secure API with an unauthorised user. e.g.  You could add:

  <button ion-button block (click)="securedPing()" *ngIf="!auth.authenticated()">Unauthorized Ping</button>

**Comment by chenkie** [comment]
Thanks, the Ionic quickstart has been updated.
