### ISSUE TITLE
Quick Start Page - Page jump to "Backend Platform" leaves behind "Skip" button

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#333]
_This test was executed on Chrome, Firefox and IE11_

In the Quick Start page, after selecting an Application Type, selecting a native SDK makes a page jump to the Backend Platform section. It should jump to the message that shows the message "Will you use an API with your mobile application?" and the "NO, SKIP THIS" button.

![2015-09-02_2030](https://cloud.githubusercontent.com/assets/12707130/9648246/61d25278-51b4-11e5-8d12-5cb5612999cd.png)

![2015-09-02_2032](https://cloud.githubusercontent.com/assets/12707130/9648245/61d0014e-51b4-11e5-96cb-435fca6e291c.png)

See in the image bellow that the "NO, SKIP THIS" button is left behind when the page jump is triggered and the Backend Platform section is activated.

![2015-09-02_2033](https://cloud.githubusercontent.com/assets/12707130/9648247/61d4701c-51b4-11e5-9476-bfc90024ddde.png)

![2015-09-02_2035](https://cloud.githubusercontent.com/assets/12707130/9648244/61ce9de0-51b4-11e5-8e0f-2bf30a5b1b71.png)

**Comment by ntotten** [comment]
Outdated.
