### ISSUE TITLE
Suggested modification to node js quickstart to fit in with ionic2 quickstart

### ISSUE THREAD

**Issue by chanoch** [auth0/docs#3330]
The nodejs-api express app, has two end points which match the ones which the ionic2 quickstart refers to:

localhost:3001/ping
localhost:3001/secured/ping 

These two routes, however, send back text responses rather than json. the ionic2 quickstart app then barfs on these as it attempts to map them in line 20 of ping.ts.

It might be better to have the API quickstart return JSON?

**Comment by chenkie** [comment]
The quickstarts have since been updated. I'll close this issue but please feel free to open a new one if problems persist.

Thanks
