### ISSUE TITLE
Two different links to "Azure Active Directory" in "Identity Providers supported by Auth0" page

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#334]
In the "Identity Providers supported by Auth0" page there are two links to "Azure Active Directory". 

One sends to the "Native Azure Active Directory applications with Auth0 (Resource Owner flow)" page (https://auth0.com/docs/connections/enterprise/azure-active-directory-native).

The other sends to the "Obtain a ClientId and Client Secret for a Microsoft Azure Active Directory" page (https://auth0.com/docs/connections/enterprise/azure-active-directory).

They should be called in a way that allows user to identify each page without having to enter.

![2015-09-02_2109](https://cloud.githubusercontent.com/assets/12707130/9648534/bc7aaa2e-51b7-11e5-86c2-3986f948f795.png)

**Comment by ntotten** [comment]
One was renamed.
