### ISSUE TITLE
Grammatical error in the ASP Classic SDK quickstart

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#3366]
In https://auth0.com/docs/quickstart/webapp/asp-classic there is one grammatical error:

- change sentence: "...have to be tested..."
![image](https://cloud.githubusercontent.com/assets/18585436/22373383/ba9cc722-e488-11e6-9a7e-5aba789c63b3.png)

- this because we want to give instructions of what to do and not tell how has been done.
- The system requirements are supposed to be always updated, therefore should always work.

AUTH - 3366

**Comment by mpaktiti** [comment]
Personally I don't see the point of this sentence at all, I would remove it and leave only the bullets listing the system requirements. Similar to how we display it here, I think it looks cleaner:

![image](https://cloud.githubusercontent.com/assets/11715799/22461624/a9dda06e-e7b2-11e6-9383-52f0ab26c600.png)

cc @chenkie

**Comment by mpaktiti** [comment]
@chenkie What do you think?
- `have been tested`,
- `have to be tested`, or
-  remove the sentence altogether and just list the system requirements?

**Comment by chenkie** [comment]
That's the old system requirements message, let's update it with the new one and leave out that sentence :) I'll do that now.
