### ISSUE TITLE
Troll link

### ISSUE THREAD

**Issue by msteckyefantis** [auth0/docs#3376]
in the following page:

[https://auth0.com/docs/libraries/lock](https://auth0.com/docs/libraries/lock)

near the bottom of the page the "see the documentation" link:
![troll link](https://cloud.githubusercontent.com/assets/13184324/22391622/45020418-e4c0-11e6-9c0a-405839a273e2.png)

links to the exact same page ([https://auth0.com/docs/libraries/lock](https://auth0.com/docs/libraries/lock))

**Comment by jeffreylees** [comment]
Hey! Yeah, thanks for pointing that out. That line of copy is attached to the little preview widget, which we use in several places, unfortunately when in the Lock reference page it makes a bit less sense, as it is then linking to itself :) 

Will look at changing that, thanks again for the feedback.
