### ISSUE TITLE
Wrong url linked to the sample project

### ISSUE THREAD

**Issue by iannyanes** [auth0/docs#3380]
At the end of the Obj-C quickstart there is a link to the sample project, this link is pointing to the wrong link: 

- The link shown below points to a location that does not exist in the docs repo: 

![image](https://cloud.githubusercontent.com/assets/2512171/22400859/8a048922-e58e-11e6-9cde-17301c393062.png)

- It should be pointing to https://github.com/auth0-samples/auth0-ios-objc-sample

**Comment by mpaktiti** [comment]
It looks like the sample is there: [Auth0 + iOS + Profile Seed](https://github.com/auth0/native-mobile-samples/tree/master/iOS/profile-sample-swift)

The link configuration must be wrong. You should either replace the link with a direct link to the repo (so no archive download) or troubleshoot the URL configuration to fix it.

cc @chenkie
