### ISSUE TITLE
I don't have a name claim in .net core User Profile code. 

### ISSUE THREAD

**Issue by aniltan** [auth0/docs#3382]
I've been following the sample for .net core, but in User Profile step, I don't have name in the claim, so I can't show it on the UI. Am I missing anything?

**Comment by chenkie** [comment]
We've updated the [.NET Core quickstart](https://auth0.com/docs/quickstart/webapp/aspnet-core) so I'll close this issue but please feel free to open a new one if you're still running into problems.

Thanks
