### ISSUE TITLE
Larvel expose CRUD operations

### ISSUE THREAD

**Issue by pduangchalomnin** [auth0/docs#3383]
According to [https://manage.auth0.com/#/clients/vkAYdxw31NEK0v2tCWP9yEGu16L8V8H9/quickstart]
with fresh Laravel5.3 install, I found that there is some documentation fault.
On `MyCustomUserRepository `section seem to have 2 problems so far
`$auth0User` seem not to be defined in this class or function itself.
On `upsertUser `function the received parameter `$profile` expected to be object (You are using `$profile->name` to get name), Therefore, The variable is sending in array instead.

**Comment by chenkie** [comment]
We've got some new documentation up for Laravel [APIs](https://auth0.com/docs/quickstart/backend/laravel) and [regular web apps](https://auth0.com/docs/quickstart/webapp/laravel). I'll close this issue but please feel free to open a new one if there are any more problems with the new docs.

Thanks
