### ISSUE TITLE
wrong links in the Java Spring Security quickstart

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#3395]
In https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc/09-mfa there are some mistakes related to the links of the quickstarts 

## Introduction
- wrong link
![image](https://cloud.githubusercontent.com/assets/18585436/22425954/a79e854e-e6e4-11e6-9465-0da18f5666d3.png)

the same here:
![image](https://cloud.githubusercontent.com/assets/18585436/22426616/18c08626-e6e7-11e6-9341-883693c41417.png)

it is: https://github.com/auth0-samples/auth0-spring-security-mvc-sample/tree/master/00-Starter-Seed
It should be: https://github.com/auth0-samples/auth0-spring-security-mvc-sample

Since it says in the quickstart that the developer can eighter download the "seed project" or the samples provided on each page, then the folder in the repository link for the whole project is the one that has all the steps. ( 00..., 01..., 02...)

AUTH - 3365

**Comment by mpaktiti** [comment]
Hey @camimonse , to my knowledge this is not an issue. The "seed project" is a blank canvas that the user can use to go step by step and apply the changes. So when we say "seed project" we mean the "00-Started-Seed" folder. 

I will close this issue and the PR.

cc @chenkie
