### ISSUE TITLE
 Grammatical errors in the ASP.NET (OWIN) quickstart

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#3398]
In https://auth0.com/docs/quickstart/webapp/aspnet-owin/04-user-profile there are some grammatical errors found that need to be fixed or improve 

## Custom login
- add comma
- in to --> into
![image](https://cloud.githubusercontent.com/assets/18585436/22429449/c8910576-e6f1-11e6-9c8e-fd8087d3cf64.png)

## User profile
- dectorate --> decorate
![image](https://cloud.githubusercontent.com/assets/18585436/22430408/427a7216-e6f5-11e6-9cb1-0d5e9c1ed0f8.png)

- add comma
- add article "a"
![image](https://cloud.githubusercontent.com/assets/18585436/22430037/e4e68168-e6f3-11e6-9958-d6dba71464f7.png)

## Authoriation
- add comma
![image](https://cloud.githubusercontent.com/assets/18585436/22430347/1d872d50-e6f5-11e6-8998-e0d6d160f410.png)

AUTH - 3362

**Comment by mpaktiti** [comment]
I reverted one of the changes. We do not use "sign into"/"log into". Google's ngram viewer agrees with that https://books.google.com/ngrams/graph?content=sign%20in%2C%20sign%20into&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Csign%20in%3B%2Cc0%3B.t1%3B%2Csign%20into%3B%2Cc0
