### ISSUE TITLE
Third Party vs First Party

### ISSUE THREAD

**Issue by cabralmartin** [auth0/docs#3407]
Docs describing `Third Party` clients vs `First Party` clients.

Diff,

- Cannot skip Consent screen.
- Send access tokens to API2 instead of id_tokens.
- Tenant level connection vs Client level connections.
- Created by Dyna Reg or demoted by tenant admins

**Comment by mpaktiti** [comment]
Hey @cabralmartin , Rodrigo wrote this doc https://auth0.com/docs/api-auth/user-consent Can you check and let me know if it covers what you had in mind? Thanks.

**Comment by mpaktiti** [comment]
We also have this one now https://auth0.com/docs/api-auth/client-types I'm closing this issue, please re-open it if it's still valid.
