### ISSUE TITLE
emberjs tutorial and seed discrepancy

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#3411]
(AUTH-3776)
Emberjs seed project [include](https://github.com/auth0-community/auth0-emberjs-spa/blob/master/00-Starter-Seed/app/index.html#L18) lock from cdn, but [tutorial](https://auth0.com/docs/quickstart/spa/emberjs) only rely on outdated auth0-ember-simple-auth addon.

**Comment by sheriffderek** [comment]
There are also differences between the scaffold code and the code provided in the tutorial.
