### ISSUE TITLE
Errors in the links in the ASP.NET Core Web API quickstart

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#3420]
in https://auth0.com/docs/quickstart/backend/aspnet-core-webapi/05-authentication-hs256-deprecated

## Authentication (HS256)
- error link: 404 error
![image](https://cloud.githubusercontent.com/assets/18585436/22506558/39d6b812-e868-11e6-8c87-df79242f1ba3.png)

Another error link: 404 error
![image](https://cloud.githubusercontent.com/assets/18585436/22506623/9ee12a80-e868-11e6-910a-42272465c6a2.png)

It should be: https://auth0.com/docs/quickstart/backend/aspnet-core-webapi/06-authorization-deprecated

AUTH 3375

**Comment by camimonse** [comment]
@mpaktiti  the first link described in this issue, where it says "Authentication using RS256" redirects to a 404 error, and I don't know which one should be the right link, if you can help me here, please.

**Comment by mpaktiti** [comment]
Sure! That's the one https://github.com/auth0/docs/pull/3483
