### ISSUE TITLE
Ember 2 quickstart: Generally doesn't get things 'started'

### ISSUE THREAD

**Issue by sheriffderek** [auth0/docs#3438]
Ember 2 quickstart: Generally doesn't get things 'started.'

About a year ago I spent a notable amount of time trying to integrate auth0 into an ember app. I was super excited about auth0... but I couldn't get anything to work. Here I am - a year later, but I haven't been able to get anything hooked up this time around either.

There are two roads offered concerning Ember 2.

1. Download a demo starter app (in my case, I already have authentication - but built out a branch to switch to auth0)

2. Follow a set of instructions to integrate auth0 to your existing app

I first followed the walkthrough with my current app that is already mostly built out. Things didn't go very well, so to make sure I was not the culprit - and to keep some documentation, I started a fresh Ember app at 2.10.0. There is mismatched code between the demo, the addon generated blueprints and the walkthrough (example #3436)- and in all cases, I've been unable to get anything to work.

After feeling a bit burnt out on the walk-through, I downloaded the demo (completely untouched except npm and bower install) - I guess the demo is built based on my userId etc. / so it's all set up?

fill this in...
<img width="1172" alt="screen shot 2017-02-01 at 5 00 15 pm" src="https://cloud.githubusercontent.com/assets/2066617/22533251/b69ebf0a-e8a1-11e6-8c59-9fc71492f30a.png">

// get this
<img width="1172" alt="screen shot 2017-02-01 at 4 59 58 pm" src="https://cloud.githubusercontent.com/assets/2066617/22533262/c1eb4a5e-e8a1-11e6-9b3c-4a250b1ee261.png">

My git repo with the steps may have been useful, but I was documenting the experience in the template / which is not visible because the app is broken.

What can I do to help? Is there anyone out there who wants to go over this guide on screen-hero or something? Is there anyone who has had nothing but roses? I would love to use auth0 for some projects, but so far I am discouraged - but I'm willing to put in some time to help figure out a guide that gets things going for new users.

There are very few unique packages for this setup - so we should be able to get things sorted - but I'm at the end of my wits on this.

This outcome may very well be because of me - but then that means people like me - and anyone with less experience than me, isn't going to use auth0... and that is a shame!

How can I help?

**Comment by sheriffderek** [comment]
At some later time, I did receive an email showing that the above (images) sign-in DID work / despite the error - and sent me an email.
<img width="400" alt="screen shot 2017-02-01 at 9 39 04 pm" src="https://cloud.githubusercontent.com/assets/2066617/22559484/1880fa9c-e926-11e6-82be-18c48013813e.png">

**Comment by chenkie** [comment]
Hi there, we've got a revamp to our [Ember quickstart](https://auth0.com/docs/quickstart/spa/ember). I'll close this issue but please open a new one if there are any more difficulties.

Thanks

**Comment by sheriffderek** [comment]
Thanks, Ryan. I look forward to checking out the revamp.
