### ISSUE TITLE
Errors related to the links in the ASP.NET Web API

### ISSUE THREAD

**Issue by camimonse** [auth0/docs#3464]
there are some broken links in https://auth0.com/docs/quickstart/backend/webapi-owin/04-authentication-rs256-deprecated

## Authentication

- 1. error 404 in a link
![image](https://cloud.githubusercontent.com/assets/18585436/22597755/11fa3330-ea18-11e6-906f-86f35830eef4.png)

It should be: https://auth0.com/docs/quickstart/backend/webapi-owin/05-authentication-hs256-deprecated

- 2. also here:
![image](https://cloud.githubusercontent.com/assets/18585436/22597959/e33cd394-ea18-11e6-9b3c-3f71fddaf55c.png)

It should be: https://auth0.com/docs/quickstart/backend/webapi-owin/06-authorization-deprecated

## Authentication (HS256)

- 3. Broken Link
![image](https://cloud.githubusercontent.com/assets/18585436/22598082/598365e0-ea19-11e6-9847-8a2c90e0dc7c.png)

- 4. 404 error
![image](https://cloud.githubusercontent.com/assets/18585436/22598297/1a9c1010-ea1a-11e6-9119-a896e970d184.png)

AUTH 3376

**Comment by camimonse** [comment]
@mpaktiti the third link redirects me to a 404 error page, and I don't know which one is the correct one, can you help me with that, please?

**Comment by mpaktiti** [comment]
Sure! That's the one https://github.com/auth0/docs/pull/3483
