### ISSUE TITLE
delegated admin 2.3: How to use the "departments"

### ISSUE THREAD

**Issue by retorquere** [auth0/docs#3469]
I'm trying to follow https://auth0.com/docs/extensions/delegated-admin but I can't figure out:

1. Where I would execute the code shown under the "Caching" or "Custom Data" sections
2. How I would add the "Departments" field to the "create user" form
3. Whether I would be able to edit a field such as "departments" for non-database (e.g. Google Oauth) users

**Comment by jerriep** [comment]
The actual document in question seems to be this one:
https://auth0.com/docs/extensions/delegated-admin/hooks

**Comment by jerriep** [comment]
Hi @retorquere, here is some feedback:

> 1. Where I would execute the code shown under the "Caching" or "Custom Data" sections

This code can be placed inside the source code block for one of your hooks.

> 2. How I would add the "Departments" field to the "create user" form

You can see this page for adding custom fields during signup:
https://auth0.com/docs/libraries/custom-signup

You can also use the [Management API](https://auth0.com/docs/api/management/v2) to updated the user's `user_metadata` structure which may contain this field.

> 3. Whether I would be able to edit a field such as "departments" for non-database (e.g. Google Oauth) users

You can store `user_metadata` for any user - not just a database user. See https://auth0.com/docs/metadata

**Comment by jerriep** [comment]
@mpaktiti Can you please un-assign me from this issue? :)

**Comment by jerriep** [comment]
Oh. It seems commenting on it somehow unassigned me. No worries.
