### ISSUE TITLE
Clarify CORS setting and wildcards

### ISSUE THREAD

**Issue by fiddur** [auth0/docs#3514]
For the client, the `Allowed Origin (CORS)` setting should be described as a host only.  Right now, it is possible to set `https://my.domain/*`.  Both having a path, and using a wildcard in the path, is wrong, and the requests from `https://my.domain` won't work.

**Comment by khorne3** [comment]
@fiddur Can you please clarify where you're seeing this? I'm having some trouble following, so perhaps an example would help? Thanks!

**Comment by fiddur** [comment]
In `articles/clients/index.md`, about `Allowed Origins (CORS)`, it says `Notice that querystrings and hash information are not taking into account when validating these URLs.`.

The fact is that `path` is not taken into account, and will even make the match fail.  So somehow it should be made clear that the origin should only be like `https://my.domain`, never with path, query, or hash.

**Comment by khorne3** [comment]
https://github.com/auth0/docs/pull/4614
