### ISSUE TITLE
No seed project for Windows Store Application in C#

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#353]
There should be a seed application for the Windows Store (C#) Tutorial:
https://auth0.com/docs/quickstart/native-mobile/windows-store-csharp/no-api/

**Comment by iannyanes** [comment]
https://auth0.com/docs/quickstart/native-mobile/windows-store-csharp/no-api

**Comment by iannyanes** [comment]
New URL  https://auth0.com/docs/quickstart/native-mobile/windows-uwp-csharp/no-api

**Comment by jerriep** [comment]
@iannyanes Yes, @ntotten and myself spoke about this and decided that a seed project does not make sense in this case, as developers are more likely to use a pre-existing template application from something like https://github.com/Windows-XAML/Template10 .

Adding the Auth0 login client for Windows 10 is also an extremely trivial task.

**Comment by iannyanes** [comment]
Closing. See previous comment
