### ISSUE TITLE
base64 secret encoding breaks python quickstart

### ISSUE THREAD

**Issue by Nesciosquid** [auth0/docs#3612]
Was working through the Python quickstart documentation at https://auth0.com/docs/quickstart/backend/python.

In the example, the client secret is encoded in the `.env` file, read as an environment variable, and used for decoding. However, I found that (in Python 2.7, Windows), the `jwt` library you recommend assumes that the client secret has not already been base64 encoded, as the secrets provided by Auth0 are.

It took me a long time to realize that I needed to do...

```
import jwt
import base64

encoded=[JWT from auth0]
secret = [client secret from auth0]
decoded = jwt.decode(encoded, base64.urlsafe_b64decode(secret), audience='T5l1DBsw0Of8ViJvFGouPa59SUhJdmjQ', algorithms=['HS256'])
print decoded
```

If you try to use the pre-encoded secret, signature verification fails.
If you try to use `base64.b64decode()` instead of `base64.urlsafe_b64decode`, you get an incorrect padding error.

Can anyone else verify this? I'd be happy to update the docs, but I want to make sure I'm not missing something important.

**Comment by Annyv2** [comment]
Hi! Thank you for your feedback! We changed our secrets to not be Base 64 encoded some time ago so we updated our quick starts to explain that. There should be a notification explaining that in the support center under `https://support.auth0.com/notifications/` and we also sent an email. You can rotate the secret to obtain a non encoded one. We are sorry for the inconvenience
