### ISSUE TITLE
Pages with 4XX errors

### ISSUE THREAD

**Issue by plaurino** [auth0/docs#363]
Here's a list of them
https://auth0.com/docs/quickstart/spa/angular/no-api
https://auth0.com/docshttps:/auth0.com/blog/2015/03/10/blacklist-json-web-token-api-keys
https://auth0.com/docs/quickstart/native-mobile/wpf-winforms/aspnetweb-api
https://auth0.com/docs/quickstart/spa/javascript/no-api
https://auth0.com/docs/quickstart/native-mobile/ionic/php-api
https://auth0.com/docs/quickstart/spa/angular/node-api
https://login.auth0.com/docs/api/v2/

You can see on the excel where they're linked from

More info in this spreadsheet -> https://docs.google.com/a/auth10.com/spreadsheets/d/1O0aZlORVTLTtUPeXeceiEIgClZuvAOwrcm64_28gy2s/edit?usp=sharing

**Comment by cristiandouce** [comment]
@vctrfrnndz @ntotten 
Routes broke when released the new docs page since either the router or the hash identifier changed.

We need to redirect those changed like this:
1. `spa/angular/:anything` -> `spa/angularjs/:same-anything`
2. `spa/:anything/node-api` -> `spa/:same-anything/nodejs`

And all the rest modified.
@plaurino please check if there are more. They'll fail like this too.

**Comment by plaurino** [comment]
4 more 404 indexed by Google

https://auth0.com/docs/connections/enterprise/sharepoint-online
https://auth0.com/docs/client-platforms/vinillajs
https://auth0.com/docs/quickstart/native-mobile/windows-store-csharp/:client
https://auth0.com/docs/quickstart/native-mobile/windows-store-javascript/:client

**Comment by cristiandouce** [comment]
`vanillajs` should have a redirect to `javascript`

the ones with `:client` is a bug as you can see. Where are those linked from?

**Comment by plaurino** [comment]
Well, this is awkard: The crawler tells those URLs are linked from URLs that are returning 404 too...

https://gist.github.com/plaurino/342f4d6fc683c638bf82

<script src="https://gist.github.com/plaurino/342f4d6fc683c638bf82.js"></script>

**Comment by ntotten** [comment]
It must be something with the way it is following links in the react
QuickStart.
