### ISSUE TITLE
Backend API PHP Error 401 Unauthorized.

### ISSUE THREAD

**Issue by nnats** [auth0/docs#3644]
The Sample project is resulting in a 401 error even though all the code snippets suggestions are followed trough, a recent change to the code sample was made and needs to be specified in the documentation how to handle it.

Steps to reproduce:

- Download sample project.
- Adjust .env file as requested.
- Start the server.
- Make a request from postman adding Authorization -IDTOKEN- as Headers.

Expected result: Shh, it's secret message.

Actual Result: Invalid Token message.

**Comment by Annyv2** [comment]
Hi! access tokens should be used instead of id tokens to call the API, we have updated the [tutorial](https://auth0.com/docs/quickstart/backend/php/01-authentication) to explain this
