### ISSUE TITLE
Management API docs does not display full endpoint

### ISSUE THREAD

**Issue by jerriep** [auth0/docs#3696]
The Management API docs (https://auth0.com/docs/api/management/v2) does not display the full endpoint address:

![pasted image at 2017_03_14 10_46 am](https://cloud.githubusercontent.com/assets/1006420/23903377/efcf7bdc-08f6-11e7-9454-1abfbe9b2365.png)

The `overflow` and `text-overflow` styles are the 2 culprits:

![pasted image at 2017_03_14 10_48 am](https://cloud.githubusercontent.com/assets/1006420/23903414/086a705c-08f7-11e7-9137-308524a12c38.png)

Removing those fixes the problem:

![pasted image at 2017_03_14 10_47 am](https://cloud.githubusercontent.com/assets/1006420/23903440/1e0af47c-08f7-11e7-96d7-881815e203f0.png)

**Comment by khorne3** [comment]
Moved to https://github.com/auth0/api2/issues/1542
