### ISSUE TITLE
Wrong Format - Refresh token word in text

### ISSUE THREAD

**Issue by iannyanes** [auth0/docs#3734]
In the iOS swift Quickstart on Step 3:

https://auth0.com/docs/quickstart/native/ios-swift/03-user-sessions

There is a mention of the refreshToken that is not in the correct format. Below you can see the screenshot of the error and one occurrence with the correct format

<img width="1438" alt="refreshtokenwrongformat" src="https://cloud.githubusercontent.com/assets/2512171/24085675/f623d818-0ccd-11e7-8821-b05b04760a3a.png">

**Comment by vmartynets** [comment]
Already fixed in https://github.com/auth0/docs/commit/7aa9d142a5a53519cdc461b5207ee25bc9b7ceb3#diff-13183f75ca97f28e2c08098378483df4
