### ISSUE TITLE
Single Page App Angular.js 2 Testing - Lock

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#3787]
In [Angular 2 SPA](https://auth0.com/docs/quickstart/spa/angular2):

- In the Readme.md file, Lock version is outdated (should be v10.13.0)
![3348_3](https://cloud.githubusercontent.com/assets/15818783/24362925/420de3ae-12dc-11e7-8956-d16d13d6d385.png)

Ticket AUTH - 3348

**Comment by Annyv2** [comment]
This is an issue with the README file, not with the quick start. Please recreate the issue here https://github.com/auth0-samples/auth0-angularjs2-systemjs-sample/issues
