### ISSUE TITLE
Mobile App Windows Phone Testing - Seed Project show error

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#3793]
In the [Windows Phone](https://auth0.com/docs/quickstart/native/windowsphone):

- When download seed project and run `Install-Package Auth0.WindowsPhone` , I get the following errors with NuGet Packages and with several missing namespaces:

![3345_3](https://cloud.githubusercontent.com/assets/15818783/24418466/15042a24-13ba-11e7-968b-0026e699ecc3.png)

Ticket AUTH - 3345

**Comment by Annyv2** [comment]
Hi! Can you please provide the proper picture? it seems to be a picture from another issue. Thanks!

**Comment by paulioceano** [comment]
Hello, yes, I'm sorry.

I've updated the image.

**Comment by cocojoe** [comment]
QS no longer exists.
