### ISSUE TITLE
Windows Store JS - No seed project

### ISSUE THREAD

**Issue by aguerere** [auth0/docs#380]
The Windows Store JS Tutorial here https://auth0.com/docs/quickstart/native-mobile/windows-uwp-javascript/no-api has no seed project.

A seed project should be created and made available through the tutorial.

**Comment by iannyanes** [comment]
https://auth0.com/docs/quickstart/native-mobile/windows-store-javascript/no-api

**Comment by iannyanes** [comment]
New url https://auth0.com/docs/quickstart/native-mobile/windows-uwp-javascript/no-api

**Comment by jerriep** [comment]
@iannyanes Yes, @ntotten and myself spoke about this and decided that a seed project does not make sense in this case, as developers are more likely to use a pre-existing template application from something like https://github.com/Windows-XAML/Template10 .

Adding the Auth0 login client for Windows 10 is also an extremely trivial task.

**Comment by iannyanes** [comment]
Closing. See previous comment
