### ISSUE TITLE
Errors in the Articles menu

### ISSUE THREAD

**Issue by mpaktiti** [auth0/docs#3884]
The errors are related to the use of hashed to go to some part of the same document. Something like this:

```
- title: "SMS"
        url: "/multifactor-authentication#mfa-with-sms"
```

## Error 1

![image](https://cloud.githubusercontent.com/assets/11715799/24860161/fb3bae2c-1dfb-11e7-95d8-5fada9128653.png)

To reproduce go to https://auth0.com/docs/extensions/authorization-extension

---

## Error 2

![image](https://cloud.githubusercontent.com/assets/11715799/24860184/19d05fd6-1dfc-11e7-8a58-2bf4e88ed542.png)

To reproduce go to https://auth0.com/docs/multifactor-authentication

---

## Error 3

The `Multifactor Authentication > For Users` gives `404` https://auth0.com/docs/multifactor-authentication/user-guide

**Comment by khorne3** [comment]
https://github.com/auth0/docs/pull/3889

**Comment by mpaktiti** [comment]
Fixed
