### ISSUE TITLE
Document global variables available in Rules

### ISSUE THREAD

**Issue by AmaanC** [auth0/docs#3936]
Rules have variables such as `auth0` available globally. Should we consider documenting all of them?

**Comment by madorb** [comment]
Just for more context, i opened: https://github.com/auth0/rules/issues/108 against the rules project - I think it's _really_ important that as a user you at the very least document all the variables that are used in your examples... it's a big time sink for folks trying to use your product if they have to drop to the forums to get answers to things that would be easily solved with documentation. 

While @AmaanC  closed my issue against the rules - I'd also argue that while this should definitely be documented in the user docs on the website - it's arguably more important on the Readme.md on the rules repo as this is where developers are going for the detailed dev-level documentation

**Comment by AmaanC** [comment]
@madorb Yep, I definitely know what you mean. Once the docs team has something in place, we'll cross-link to it from the `auth0/rules` repo's README.md too.

**Comment by mpaktiti** [comment]
Following discussions with DSE, we will be closing this issue. Users should use require instead of these modules. The variables that exist in the rules examples, should be explained inside those samples or as a part of a README on the rules examples repo.

**Comment by tommedema** [comment]
@mpaktiti you closed this in 2017 saying people shouldn't use the auth0 global variable, yet almost all of your official examples use this object. How are users supposed to understand what is best practice now? And how do we migrate away from using the auth0 object if your examples use it, e.g. at https://github.com/auth0/rules/blob/master/src/rules/roles-creation.js#L33?
