### ISSUE TITLE
Revoke a token without the Client Secret is not correct

### ISSUE THREAD

**Issue by dctoon** [auth0/docs#3949]
On the page https://auth0.com/docs/tokens/preview/refresh-token#use-the-api in the section _Revoke a token without the Client Secret_ the parameter `tokenEndpointAuthMethod: none` is not a payload value but a setting on the client. 

The setting on the client is _Token Endpoint Authentication Method_, once that is set to `none` following payload is sufficient to revoke a token without the `client_secret`.

```
{
	"token":"YOUR_REFRESH_TOKEN",
	"client_id":"YOUR_CLIENT_ID"
}
```

**Comment by mpaktiti** [comment]
Fixed https://github.com/auth0/docs/pull/3996
