### ISSUE TITLE
WPF/Winforms seed 404 error

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4001]
(AUTH-3917)
[WPF/WinForms tutorial](https://auth0.com/docs/quickstart/native/wpf-winforms) seed project link points nowhere, I've received 404 error when clicked on the `fork on github` 
![image](https://cloud.githubusercontent.com/assets/1114365/25483821/15de6cd0-2b60-11e7-95b4-0d5427a81de4.png)

**Comment by mpaktiti** [comment]
Works now
