### ISSUE TITLE
Badly formated note on PHP API Tutorial

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#402]
In step 1 of PHP API Tutorial (https://auth0.com/docs/quickstart/native-mobile/android/php) the note that contains the text bellow is badly formated and takes a lot of needless space.

_Extracted snippets from tutorials This sample uses Composer, a tool for dependency management in PHP. It allows you to declare the dependent libraries your project needs and it will install them in your project for you._

This is accentuated when viewing the tutorial from the documentation page, when viewed from the dashboard it doesn't take the same space (see images bellow):

From the documentation page:
![2015-09-17_1943](https://cloud.githubusercontent.com/assets/12707130/9948889/33e43d82-5d75-11e5-8268-b92a4fdfba65.png)

From inside the dashboad:
![2015-09-17_1941](https://cloud.githubusercontent.com/assets/12707130/9948890/340249f8-5d75-11e5-8216-147374b2d8ec.png)

**Comment by iannyanes** [comment]
Issue Fixed  https://auth0.com/docs/quickstart/native-mobile/android/php
