### ISSUE TITLE
python tutorial no snippet location

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4067]
(AUTH-3944)
[Python tutorial](https://auth0.com/docs/quickstart/webapp/python#2-add-the-auth0-callback-handler) snippets have no a file path/name is placed in the first line.
![image](https://cloud.githubusercontent.com/assets/1114365/25779440/9a9f5c28-3320-11e7-9048-d1beadea2158.png)

**Comment by Annyv2** [comment]
https://github.com/auth0/docs/pull/4237
