### ISSUE TITLE
python tutorial and seed project discrepancy

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4068]
(AUTH-3945)
[Python tutorial](https://auth0.com/docs/quickstart/webapp/python#4-trigger-login-manually-or-integrate-lock) suggest to use auth0-lock, when [python seed project](https://github.com/auth0-samples/auth0-python-web-app/blob/master/00-Starter-Seed/templates/home.html#L4) is using auth0.js.

**Comment by Annyv2** [comment]
https://github.com/auth0/docs/pull/4237
