### ISSUE TITLE
asp.net tutorial broken link

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4078]
(AUTH-3957)
[ASP.NET tutorial](https://auth0.com/docs/quickstart/webapp/aspnet#redirect-to-a-login-page) contains link that point to anchor that doesn't exist.
![image](https://cloud.githubusercontent.com/assets/1114365/25807509/c13fccc4-340f-11e7-8f57-70cf7ece0145.png)

**Comment by mpaktiti** [comment]
Works now
