### ISSUE TITLE
No Hello World app and sample project under Getting Started section

### ISSUE THREAD

**Issue by mikearias3** [auth0/docs#4103]
**Environment Information**
Browser: Google Chrome v58.0.3029.96 (64-bit)
URL: https://auth0.com/docs/quickstart/native/ios-swift/00-getting-started

**Description**
There's no seed, Hello World app or sample project under https://auth0.com/docs/quickstart/native/ios-swift/00-getting-started

**Screenshot**
<img width="1085" alt="screen shot 2017-05-10 at 9 26 36 am" src="https://cloud.githubusercontent.com/assets/5594487/25900885/f82043c8-3562-11e7-92cb-b0a7f19bac60.png">

**Comment by chenkie** [comment]
Thanks @mikearias3. It's actually intentional that there isn't a sample in the getting started section. The part about the sample applications refers to the samples available in the subsequent sections. I think the wording can be improved here as it's a bit ambiguous :) Fixing that now.
