### ISSUE TITLE
Regular Web App asp Classic Testing - Seed Project missing

### ISSUE THREAD

**Issue by SwapnaDixit** [auth0/docs#4114]
seed project in the quickstart https://auth0.com/docs/quickstart/webapp/asp-classic is missing

**Comment by jerriep** [comment]
@SwapnaDixit Do you actually need this?

ASP is absolutely ancient technology,

**Comment by jerriep** [comment]
@mpaktiti or @aaguiarz  Can either of you please close this issue? The quickstart referenced is no longer there
