### ISSUE TITLE
(Native - Android) Add doc on how to customize Lock UI

### ISSUE THREAD

**Issue by glena** [auth0/docs#415]
Probably also for iOS, we need a doc on how to customize the Lock UI

**Comment by mpaktiti** [comment]
iOS Swift: https://auth0.com/docs/quickstart/native/ios-swift/10-customizing-lock
iOS Android: https://auth0.com/docs/quickstart/native/android/10-customizing-lock

iOS Objective-C pending.

**Comment by mpaktiti** [comment]
New doc request registered at Quickstarts & SDKs trello board.
