### ISSUE TITLE
socket.io tutorial no oidcConformant and audience parameters

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4155]
(AUTH-4017)
[Socket.io tutorial](https://auth0.com/docs/quickstart/spa/socket-io#4-configure-auth0lock) doesn't use oidcConformant and audience parameters.
![image](https://cloud.githubusercontent.com/assets/1114365/26160415/e5d750ae-3b29-11e7-8b37-28246d2668a3.png)

**Comment by albertoperdomo** [comment]
Quickstart no longer in portfolio. Closing.
