### ISSUE TITLE
Socket.io tutorial have no seed project

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4157]
(AUTH-4019)
[Socket.io tutorial](https://auth0.com/docs/quickstart/spa/socket-io) have no seed project.
![image](https://cloud.githubusercontent.com/assets/1114365/26160527/2637ea14-3b2a-11e7-906b-1c35610f9618.png)

**Comment by albertoperdomo** [comment]
Quickstart no longer in portfolio. Closing.
