### ISSUE TITLE
Create doc on how device credentials works

### ISSUE THREAD

**Issue by glena** [auth0/docs#416]
https://auth0.com/docs/api/v2#!/Device_Credentials/post_device_credentials

**Comment by ntotten** [comment]
What is missing?

**Comment by glena** [comment]
there is any doc about it, just the api which is not enough.

**Comment by ntotten** [comment]
Gotcha. Thanks!

**Comment by calmera** [comment]
+1. We could really use some information on this as well. For example, is it possible to authenticate the device with this? How would something like that be done?

I was planning to implement some authentication scheme based on jwt tokens for my devices, but then I came across this endpoint in the api. No information to be found except for some issue reports.

Would really appreciate some guidance here.

Thanks again for a great product!

**Comment by mpaktiti** [comment]
Thank you @glena ! I moved this issue at our Docs trello board and someone will look into this shortly.

**Comment by dhayalakumarc** [comment]
Hsa this been addressed yet?

**Comment by johnlim** [comment]
Any updates on this? :)
