### ISSUE TITLE
angular tutorial broken seed project link

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4235]
(AUTH-4044)
Link `Fork on Github` in [angular tutorial](https://auth0.com/docs/quickstart/spa/angularjs/03-calling-an-api) is broken.
![image](https://cloud.githubusercontent.com/assets/1114365/26410464/0a44ecf8-40ac-11e7-8517-8ef11a0a5463.png)

**Comment by mpaktiti** [comment]
Works now
