### ISSUE TITLE
not declared variables at spring security api tutorial

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4315]
(AUTH-4055)
[Spring security api tutorial](https://auth0.com/docs/quickstart/backend/java-spring-security/01-authorization#configure-the-protected-endpoints) snippet use `apiAudience` and `issuer` variables which is not declared. That variables could be changed to `https://${account.namespace}/userinfo` and `${account.clientId}` according.
![image](https://cloud.githubusercontent.com/assets/1114365/26627140/19b58aa2-4602-11e7-91b7-2928ffc4fe1a.png)

**Comment by albertoperdomo** [comment]
Fixed. Closing.
