### ISSUE TITLE
Redaction errors in Xamarin Tutorial

### ISSUE THREAD

**Issue by mikearias3** [auth0/docs#4333]
*Device Information*
Browser: Google Chrome v58 for Mac.
Env: https://auth0.com/docs/quickstart/native/xamarin

*Description*
Found the following redaction errors across the tutorial:
<img width="1117" alt="screen shot 2017-05-31 at 1 18 39 pm" src="https://cloud.githubusercontent.com/assets/5594487/26646741/ccd5a254-460a-11e7-8d60-19f172542c0f.png">
<img width="1108" alt="screen shot 2017-05-31 at 1 18 54 pm" src="https://cloud.githubusercontent.com/assets/5594487/26646742/cceaf1c2-460a-11e7-9252-469f6d9f7206.png">
<img width="1105" alt="screen shot 2017-05-31 at 1 19 09 pm" src="https://cloud.githubusercontent.com/assets/5594487/26646745/ccf1193a-460a-11e7-9c47-0d6bad635070.png">
<img width="1100" alt="screen shot 2017-05-31 at 1 19 21 pm" src="https://cloud.githubusercontent.com/assets/5594487/26646743/ccef06d6-460a-11e7-8fed-92bb1e0a5dff.png">
<img width="1103" alt="screen shot 2017-05-31 at 1 19 34 pm" src="https://cloud.githubusercontent.com/assets/5594487/26646748/cd2ee292-460a-11e7-8a07-4ef190cec9d1.png">
<img width="1101" alt="screen shot 2017-05-31 at 1 19 44 pm" src="https://cloud.githubusercontent.com/assets/5594487/26646746/ccf73d7e-460a-11e7-91eb-edcef4716c49.png">
<img width="811" alt="screen shot 2017-05-31 at 1 20 15 pm" src="https://cloud.githubusercontent.com/assets/5594487/26646744/cceef72c-460a-11e7-8927-251de4535911.png">
<img width="1101" alt="screen shot 2017-05-31 at 1 20 41 pm" src="https://cloud.githubusercontent.com/assets/5594487/26646747/ccfcedb4-460a-11e7-9489-090119cd8d26.png">

**Comment by mpaktiti** [comment]
Thank you @mikearias3 ! 👍
