### ISSUE TITLE
state parameter for `authorize()` is documented as recommended but auth0.js seems to provide a state by default

### ISSUE THREAD

**Issue by thedavidmeister** [auth0/docs#4341]
I saw this in the docs:

https://auth0.com/docs/libraries/auth0js/v8#webauth-client-login-

> 	(String) An opaque value the client adds to the initial request that Auth0 includes when redirecting back to the client. This value must be used by the client to prevent CSRF attacks.

and

> NOTE: The state parameter, is not required, but it is recommended. It is an opaque value that Auth0 will send back to you. This method helps prevent CSRF attacks.

but actually in my testing it seems that auth0 generates a state, puts it in the URL for me and also into localStorage if i don't BYO state.

I don't understand why BYO state would be "recommended" when surely the token provided by auth0 is already secure enough?

**Comment by jeffreylees** [comment]
Thanks for noticing this! Some of the parameter descriptions are similar or the same to those of the actual API endpoint - you're right, this is handled. I'll close this issue and create a PR to clear up the confusing reference doc.
