### ISSUE TITLE
Broken Link at api article in postman.md

### ISSUE THREAD

**Issue by dongido001** [auth0/docs#4408]
The link leads to 404 page
![404](https://user-images.githubusercontent.com/18917158/26999430-4c95c946-4d91-11e7-9021-6c67c08886f4.PNG)

**Comment by mpaktiti** [comment]
Hey @dongido001 I just tried and the link works. I'm closing this issue, please reopen it if you still see a problem. Thanks for reporting this!

**Comment by dongido001** [comment]
@mpaktiti here is the direct link to the page. I sitll get 404 when i click on it.
https://github.com/auth0/docs/blob/master/articles/api/postman.md

Here is the link I tried to click and got a 404 page - 
[Api Landing Page](https://github.com/auth0/docs/blob/master/api/info)

Don't know if I'm missing something.

**Comment by mpaktiti** [comment]
@dongido001 Do you get a 404 at our docs site https://auth0.com/docs/api/postman or through the github file https://github.com/auth0/docs/blob/master/articles/api/postman.md ?

**Comment by dongido001** [comment]
Through github.

**Comment by mpaktiti** [comment]
Cool, that's normal! We configure our links in a specific way so they can be correctly formatted during the build process. Copying from our [contributing guidelines](https://github.com/auth0/docs/blob/master/CONTRIBUTING.md):

```
Always use relative URLs for internal `auth0.com/docs` links. 
For example, if the absolute path to the document is 
`https://auth0.com/docs/identityproviders`, use `/identityproviders`. 
These links will be correctly formatted in the build process.
```

As a result the links appear broken on github, but they are not at our site. I can see how that can be confusing.

Thanks for taking the time to report this and follow up! 👍

**Comment by dongido001** [comment]
Oh,  alright.
