### ISSUE TITLE
No file path/name as a comment in most objc/swift snippets

### ISSUE THREAD

**Issue by mikearias3** [auth0/docs#4432]
*Environment Information*
Browser: Google Chrome v58.0.3029.96 (64-bit)
URL: All tutorials under https://auth0.com/docs/quickstart/native/ios-objc and https://github.com/auth0-samples/auth0-ios-swift-v2-sample/

*Description*
Most of the snippets presented in these tutorials don't have the name of the file and the path commented in the first line. The ones that do only have the name of the file in the comment

*Screenshot*

<img width="774" alt="screen shot 2017-06-13 at 11 01 16 pm" src="https://user-images.githubusercontent.com/5594487/27113722-a75b09ce-508c-11e7-944c-63ff50f5c662.png">

**Comment by albertoperdomo** [comment]
Fixed. Closing.
