### ISSUE TITLE
webAuth.authorize() does not explain how to get JWT tokens

### ISSUE THREAD

**Issue by thedavidmeister** [auth0/docs#4477]
https://auth0.com/docs/libraries/auth0js/v8#webauth-authorize-

> (String) The value must be 'token' or 'code'. It defaults to 'token', unless a redirectUri is provided, then it defaults to 'code'.

Actually, there is a third option `id_token` that can be used with scope like `openid`.

This seems to be the only way to get a JWT token to be returned IIRC.

**Comment by thedavidmeister** [comment]
example: `{"responseType": "id_token", "scope": "openid"}`

**Comment by mpaktiti** [comment]
The params descriptions were updated https://github.com/auth0/docs/pull/4539

Thank you @thedavidmeister ! 👍
