### ISSUE TITLE
missing info on 3rd party clients

### ISSUE THREAD

**Issue by ebarault** [auth0/docs#4498]
I was looking to implement an Implicit Grant Authorization with a 3rd party Client, and had to navigate through multiple pages to find the correct information, as well as to guess some missing information.

ATM 3 pages refer to 3rd party clients: 
1. [Client and Application Types](https://auth0.com/docs/api-auth/client-types)
2. [User consent and third-party clients](https://auth0.com/docs/api-auth/user-consent)
3. [Dynamic Client Registration](https://auth0.com/docs/api-auth/dynamic-client-registration)

- 1 & 2 indicate how to create a third-party client with `is_first_party : false`
- Only 3 indicates that 
  - 3rd party client **"can use only tenant level connections (domain connections)"**
  - connections can be promoted to _tenant level_ with `is_domain_connection`

No further information on tenant level connections can be found.

Furthermore I found that it's not possible to explicitly add a connection to a 3rd party client, which makes sense actually but is presented in a very confusing way in the website): A first the dashboard allows you to add the connection to the client (or the other way around) but the choice is not persisted when reloading the page.

Likewise, the management API lets you add the client to the connection but when fetching the given connection the 3rd party client is not persisted in the `enabled_clients` lists.
Whether it's dashboard based or management API based, adding a 3rd party to a client should raise an error.

I also noticed that when fetching a given _tenant level_ connection with the management API, the `is_domain_connection` is missing, which is confusing.

(i didn't find a proper place to post an issue related to the management API)

As part of the missing docs on tenant level connections, it should be indicated that 
- only one tenant level connection can exist for a given strategy
- promoting a connection to tenant level is only supported with the management API as of now
 
Last but not least, if you do not have a tenant level connection and you try to perform and OAuth2 grant with a 3rd party client without specifying a connection you only get a very vague error message is displayed and no log is traced in Auth0 logs:

![image](https://user-images.githubusercontent.com/12000935/27376119-7a5a97ba-5671-11e7-9291-bd88a7000231.png)

**Comment by jerriep** [comment]
@ebarault I have communicated the discrepancies to the relevant engineering teams, and will look into updating the documentation as appropriate

**Comment by jerriep** [comment]
@ebarault I have communicate your issues to the engineering team.

1. The issue with enabling a connection for a dynamic client in the Auth0 Dashboard will be addressed in the future. 

2. The fact that the `is_domain_connection` returns `false` when you get the details for a connection which has previously been set to a domain level connections is an issue. The team will look into fixing this. Please note however that the connection is indeed set correctly as a domain level connection, it just seems to be a case of the GET api endpoint not returning the correct result

The [Dynamic Client Registration](https://auth0.com/docs/api-auth/dynamic-client-registration) is correct, so if you follow along with that, like you did, then you should be okay (barring the issue with `is_domain_connection` mentioned above).
