### ISSUE TITLE
react native android tutorial deprecated rnpm

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4510]
(AUTH-4106)
[React native android tutorial](https://auth0.com/docs/quickstart/native/react-native-android) suggest to use [rnpm which already deprecated and merged into react-native core](https://github.com/rnpm/rnpm)
![image](https://user-images.githubusercontent.com/1114365/27433771-bcaca3ae-575e-11e7-9eb3-7ac1f62654d7.png)

**Comment by albertoperdomo** [comment]
Non longer relevant. Fixed.
