### ISSUE TITLE
react native android no snippets location

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4511]
(AUTH-4107)
[React native android tutorial](https://auth0.com/docs/quickstart/native/react-native-android#implement-the-login) snippets have no file path/name is placed in the first line.
![image](https://user-images.githubusercontent.com/1114365/27433984-9cd24f24-575f-11e7-959e-c6b40ac191b8.png)

**Comment by albertoperdomo** [comment]
Not a priority at this time. Closing.
