### ISSUE TITLE
AWS integration page has non-working example

### ISSUE THREAD

**Issue by gene1wood** [auth0/docs#4519]
https://github.com/auth0/docs/blame/b4b35c7ecf92a0fe9f9356fbe07932a48bddc6ff/articles/integrations/aws.md#L88-L103

The example on the AWS integration page shows that you can assign values to the SAML mappings. It gives this code example

```
var awsRoles = {
  'DomainUser': 'arn:aws:iam::951887872838:role/TestSAML,arn:aws:iam::95123456838:saml-provider/MyAuth0',
  'DomainAdmins': 'arn:aws:iam::957483571234:role/SysAdmins,arn:aws:iam::95123456838:saml-provider/MyAuth0'
};

context.samlConfiguration.mappings = {
  'https://aws.amazon.com/SAML/Attributes/Role': awsRoles[user.group],
  'https://aws.amazon.com/SAML/Attributes/RoleSessionName': user.name,
};
```

However this isn't the case. If you use this approach of setting a value, in this case the value of `awsRoles[user.group]`, directly in the mapping, the resulting SAML assertion is missing the mappings.

You must set the value in the user object and reference that value in the mapping

Here's what this code block should look like

```
var awsRoles = {
  'DomainUser': 'arn:aws:iam::951887872838:role/TestSAML,arn:aws:iam::95123456838:saml-provider/MyAuth0',
  'DomainAdmins': 'arn:aws:iam::957483571234:role/SysAdmins,arn:aws:iam::95123456838:saml-provider/MyAuth0'
};
user.awsRole = awsRoles[user.group];
user.awsRoleSession = user.name;

context.samlConfiguration.mappings = {
  'https://aws.amazon.com/SAML/Attributes/Role': 'awsRole',
  'https://aws.amazon.com/SAML/Attributes/RoleSessionName': 'awsRoleSession',
};
```

Also, since Amazon doesn't allow <kbd>space</kbd> characters, [among others](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml_assertions.html) in the `RoleSessionName`, using `user.name` also fails if it contains a users full name. 

Amazon's docs say

> The value in the AttributeValue element must be between 2 and 64 characters long, can contain only alphanumeric characters, underscores, and the following characters: + (plus sign), = (equals sign), , (comma), . (period), @ (at symbol), and - (hyphen). It cannot contain spaces. The value is typically a user ID (bobsmith) or an email address (bobsmith@example.com). It should not be a value that includes a space, like a user's display name (Bob Smith). 

A better example would be to use something like

```
var awsRoles = {
  'DomainUser': 'arn:aws:iam::951887872838:role/TestSAML,arn:aws:iam::95123456838:saml-provider/MyAuth0',
  'DomainAdmins': 'arn:aws:iam::957483571234:role/SysAdmins,arn:aws:iam::95123456838:saml-provider/MyAuth0'
};
user.awsRole = awsRoles[user.group];
user.awsRoleSession = user.email;

context.samlConfiguration.mappings = {
  'https://aws.amazon.com/SAML/Attributes/Role': 'awsRole',
  'https://aws.amazon.com/SAML/Attributes/RoleSessionName': 'awsRoleSession',
};
```

**Comment by khorne3** [comment]
https://github.com/auth0/docs/pull/4734

**Comment by gene1wood** [comment]
These bugs were fixed in these locations

* [`awsRoles[user.group]` and `user.name` were changed to `'awsRole'` and `'awsRoleSession'`](https://github.com/auth0/docs/pull/4734/files#diff-fda7a54e877e1bdee7618a21e87f96c5R137)
* [`user.name` was changed to `user.email`](https://github.com/auth0/docs/pull/4734/files#diff-fda7a54e877e1bdee7618a21e87f96c5R134)

You're welcome.
