### ISSUE TITLE
Fork on Github link not working.

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#4547]
In the Sample Project section, when you click in the "Fork on Github" link, does not redirect you to github, instead, download the project.

This happen in all the cases of the [Angular 2 tutorial](https://auth0.com/docs/quickstart/spa/angular2):

- https://auth0.com/docs/quickstart/spa/angular2/00-login
- https://auth0.com/docs/quickstart/spa/angular2/03-user-profile
- https://auth0.com/docs/quickstart/spa/angular2/04-calling-an-api
- https://auth0.com/docs/quickstart/spa/angular2/05-authorization
- https://auth0.com/docs/quickstart/spa/angular2/06-token-renewal

AUTH-3348

**Comment by mpaktiti** [comment]
This is not content related, there is already an issue logged and an engineer is working on it https://github.com/auth0/auth0-docs/issues/1424
