### ISSUE TITLE
Callback url should not contain .php extension (PHP Doc: https://auth0.com/docs/quickstart/webapp/php)

### ISSUE THREAD

**Issue by masterpiece91** [auth0/docs#46]
The callback url example contains a .php extension. This should be removed. 

![2015-05-26_2031](https://cloud.githubusercontent.com/assets/3585303/7826937/79f77eee-03e6-11e5-8f27-3b7e8fb93cd1.png)

**Comment by masterpiece91** [comment]
Found the same issue in step 4/ Below is the screenshot:

![2015-05-26_2041](https://cloud.githubusercontent.com/assets/3585303/7827023/b97aa888-03e7-11e5-95b9-62c817c3c322.png)

**Comment by glena** [comment]
@ntotten why is that?

It is correct to add the `.php` to the url.

**Comment by iannyanes** [comment]
Bug Irreproducible. Closing it.
