### ISSUE TITLE
discrepancy auth0-spring-security-api versions

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4602]
(AUTH-4128)
[Java spring security API tutorial](https://auth0.com/docs/quickstart/backend/java-spring-security) uses auth0-spring-security-api version 1.0.0-rc.2 when [seed project uses](https://github.com/auth0-samples/auth0-spring-security-api-sample/blob/master/01-Authorization/pom.xml#L45) 1.0.0-rc.3 version.
![image](https://user-images.githubusercontent.com/1114365/27858850-74891726-617f-11e7-8945-936298b962dc.png)

**Comment by albertoperdomo** [comment]
Seems to have been addressed. Closing.
