### ISSUE TITLE
Seed Project link in Ruby on Rails Tutorial broken

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#466]
![2015-10-07_2241](https://cloud.githubusercontent.com/assets/12707130/10356396/c4e65c5a-6d44-11e5-9c6a-94733b3db61f.png)

Clicking on the Get Seed Project link shows the following error message:

![2015-10-07_2242](https://cloud.githubusercontent.com/assets/12707130/10356395/c4e62e74-6d44-11e5-9a2a-d6d315d44b33.png)

**Comment by ntotten** [comment]
Fixed: https://github.com/auth0/docs/commit/88ac7896884060b3186903effde0d135dc2bb71a
