### ISSUE TITLE
Passwordless connection - use your own implementation - discrepancies

### ISSUE THREAD

**Issue by ayastreb** [auth0/docs#4675]
Hi!

There is some confusion in passwordless connection docs, in [Use your own UI](https://auth0.com/docs/connections/passwordless/spa-email-code/v8#use-your-own-ui) section.
For SPA email code version, the `webAuth` instance construction sample does not include `redirectUri` and `responseType` params. However according to [auth0.js](https://auth0.com/docs/libraries/auth0js/v8#verify-passwordless):

> In order to use passwordlessVerify, the options redirectUri and responseType: 'token' must be specified when first initializing WebAuth.

The email code guide also does not mention that user will be redirected to auth0 and back to your app after code is verified. After that app needs to parse hash to get userInfo

**Comment by jeffreylees** [comment]
Thanks for the feedback! https://github.com/auth0/docs/pull/4805 introduced some updates to our Passwordless and Auth0.js documentation to bring them more in line with each other. Let us know if you run into any other issues!
