### ISSUE TITLE
How to use Refresh token with PKCE flow?

### ISSUE THREAD

**Issue by vimalprakashts** [auth0/docs#4682]
hi team, 

I was reading this document , 

https://auth0.com/docs/api-auth/grant/authorization-code-pkce

if some one got accesstoken, refreshtoken . next time how they will get accesstoken by refresh token. because the client secret is not there. 

I checked your refresh token section , https://auth0.com/docs/tokens/refresh-token/current I didnt find any answer for this. can you please suggest me, how to use refresh token in mobile apps?

**Comment by mpaktiti** [comment]
Hey @vimalprakashts, if you check out this section https://auth0.com/docs/tokens/refresh-token/current#use-a-refresh-token it says that the client secret is optional (required only for [confidential clients](https://auth0.com/docs/clients/client-types#confidential-clients)). So you don't have to send this from mobile apps.

If you think the doc is missing info or is wrong please let me know. If you are having problems specific to your implementation you can use our [Auth0 Community](https://community.auth0.com/) (if you use a free subscription) or our [Customer Support](https://support.auth0.com/) (if you are a paying customer or in the initial trial period of your subscription). 

Hope this helps!

**Comment by vimalprakashts** [comment]
Yes @mpaktiti , you are right , thank you for the clarification.

**Comment by IsraelDominguez** [comment]
But if you dont pass the client_secret to refresh token, is insecure, isnt it?
