### ISSUE TITLE
No file path/name as a comment in most snippets for react ios tutorial

### ISSUE THREAD

**Issue by mikearias3** [auth0/docs#4705]
**Environment Information**
Browser: Google Chrome v58.0.3029.96 (64-bit)
URL: https://auth0.com/docs/quickstart/native/react-native

**Description**
Most of the snippets presented in these tutorials don't have the name of the file and the path commented in the first line. The ones that do only have the name of the file in the comment

**Screenshot**
<img width="796" alt="screen shot 2017-07-19 at 10 10 30 pm" src="https://user-images.githubusercontent.com/5594487/28397398-49887ff2-6ccf-11e7-8843-b67863a28482.png">
![Uploading Screen Shot 2017-07-19 at 10.10.38 PM.png…]()

**Comment by albertoperdomo** [comment]
Fixed via #5749. Closing.
