### ISSUE TITLE
Missing steps in: Mobile / Native App > Xamarin > Login

### ISSUE THREAD

**Issue by floatas** [auth0/docs#4707]
Hello,

1. I had a website with "Client type = Regular web application"
2. Created Xamarin iOS application and fallowed https://auth0.com/docs/quickstart/native/xamarin/01-login
3. When I try to login from mobile app I always get error. Auth0 Dashboard shows that login was successful.

After some trial and error I found that I need to switch "Client type" to Native and now both mobile app and web app works.

Are there additional steps needed to make "Client type = Regular web application" work in Xamarin ?

**Comment by albertoperdomo** [comment]
Xamarin apps must be created as native in dashboard. Closing.
