### ISSUE TITLE
No information on how to setup Auth0 to create users in LDAP

### ISSUE THREAD

**Issue by deanpeterson** [auth0/docs#4719]
I have set up Auth0 to use our existing LDAP user repository. I can log in as existing users, but is there a way to create users in LDAP with Auth0? I do not see that information in the documentation.

**Comment by sylnsr** [comment]
No there is not. This is not what Auth0 is for.  Auth0 is an authentication broker and as such **references** other sources such as LDAP servers, for authentication purposes.  You need to find a way to manage your LDAP server with tools developed for that purpose.  This is not the purpose of Auth0.   If you need to manage an LDAP server, you might want to look at something along the lines of these programs:
 - [Apache Directory Studio](http://directory.apache.org/studio/)
 - [JXplorer](http://jxplorer.org/)

.. or checkout a longer list on [Wikipedia](https://en.wikipedia.org/wiki/List_of_LDAP_software) that has some clients that might be able to be used to manage users in the directory

If you are using AWS Simple AD, then you might be using it in conjunction with AWS WorkMail in which case adding or disabling (cannot remove) a WorkMail user will automatically update the AWS Simple AD directory.

If this answers your question, then please close the issue.

**Comment by dmark** [comment]
@deanpeterson: If you want to use an LDAP directory as your user DB, you should be able to use [custom database scripts](https://auth0.com/docs/connections/database/custom-db/templates) to do so. You just need to provide all 5 customs DB scripts.

If you are migrating your users from an LDAP directory to an Auth0 hosted database, you won't be able to create users in LDAP via Auth0. The migration is 1-way only.

**Comment by sylnsr** [comment]
@khorne3 this is not an issue. Can we vote to close?
