### ISSUE TITLE
System requirement section with wrong version in Symfony Doc

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#4746]
In the System Requirement section on https://auth0.com/docs/quickstart/webapp/symfony, show a requirement for Symfony 3.*, but the latest Symfony version is 3.3 and the Sample project uses version 2.8

![3359-1](https://user-images.githubusercontent.com/15818783/28762011-1ad17726-7581-11e7-97d0-e66c6bdab0c9.png)

![3359-2](https://user-images.githubusercontent.com/15818783/28762029-352fe40e-7581-11e7-80f0-3a6b49777e54.png)

AUTH-3359

**Comment by arnas** [comment]
I will take it

**Comment by albertoperdomo** [comment]
Closed via #6780.
