### ISSUE TITLE
asp.net tutorial client_secret usage

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4752]
(AUTH-4173)
[ASP.NET tutorial](https://auth0.com/docs/quickstart/webapp/aspnet) uses client_secret, instead of a stub
![image](https://user-images.githubusercontent.com/1114365/28798116-34c556ae-764c-11e7-80bb-22a8fa2dee92.png)

**Comment by jerriep** [comment]
It does not. It uses the variables: https://github.com/auth0/docs/blob/master/snippets/server-platforms/aspnet/setup.md
