### ISSUE TITLE
Java Spring MVC tutorial client_secret usage

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4754]
(AUTH-4176)
[Java Spring MVC tutorial](https://auth0.com/docs/quickstart/webapp/java-spring-mvc#configure-your-java-spring-app) uses client_secret instead of a stub.
![image](https://user-images.githubusercontent.com/1114365/28821323-ac8af92a-76bd-11e7-9f65-9561e31880ed.png)

**Comment by albertoperdomo** [comment]
Seems to have been addressed.
