### ISSUE TITLE
Update integrations pictures. Should images be hosted in the repo or in cloudup?

### ISSUE THREAD

**Issue by lobo** [auth0/docs#479]
https://github.com/auth0/docs/blob/master/articles/integrations/_template.md

Here's an updated screenshot for this docs page:
![screenshot from 2015-10-13 08 45 01](https://cloud.githubusercontent.com/assets/575750/10453986/786b9b32-7187-11e5-919a-15f99fc1adba.png)

Maybe's time to re structure this docs page? The second screenshot in this link does not correspond neither.

**Comment by Catografix** [comment]
@ntotten Is there something here for me?

**Comment by ntotten** [comment]
@Catografix you could move the image into the /media folder to be consistent.

**Comment by ntotten** [comment]
@Catografix I think this is complete.
