### ISSUE TITLE
Custom UI - where can i find list of connections (PHP Doc: https://auth0.com/docs/quickstart/webapp/php)

### ISSUE THREAD

**Issue by masterpiece91** [auth0/docs#48]
The code snippet that pops up shows me how to set up a custom ui and gives me an example with google but it does not point me to where i should go to find a list of connections.

![2015-05-26_2051](https://cloud.githubusercontent.com/assets/3585303/7827171/907cffc4-03e9-11e5-8392-b663052d3dd9.png)

**Comment by glena** [comment]
@ntotten this snippet is shared across all the quickstarts (and I think all has the same **note** after the snippet). Should I add there a link to https://manage.auth0.com/#/connections/social ? (I assume that this is what is missing there).

**Comment by iannyanes** [comment]
Not reproducible.
