### ISSUE TITLE
No explanation on how to use third party delegation

### ISSUE THREAD

**Issue by marcato15** [auth0/docs#4807]
The documentation explains that it is no longer possible to use legacy delegation. However, the docs don't list anything explaining how you should connect to third parties (like Firebase). Or is that because it's no longer possible?

**Comment by mpaktiti** [comment]
Hello @marcato15 and sorry for taking such a long time to get back to you. 

At the moment the only way to connect to third parties is using delegation. We are working on a replacement and will update the docs as soon as we have it shipped. When the solution is in place we will issue a migration notice and details on how to migrate to the new solution. When this migration is complete, the delegation will be disabled.

**Comment by nielsgl** [comment]
@mpaktiti any updates on how to set it up with a new flow?

**Comment by mpaktiti** [comment]
Hey @nielsgl  👋 Sorry for the delay. Our engineering team is working on this but we still do not have a shipping date. In which integration are you interested in? It might be better if you followed up with our support so they can try and assist you with what you want to implement.
