### ISSUE TITLE
Using Auth0 with Multi-Tenant Applications page term problem

### ISSUE THREAD

**Issue by serhatcan** [auth0/docs#4822]
Hi, in https://auth0.com/docs/tutorials/using-auth0-with-multi-tenant-apps#use-user-metadata page, you say 

> (each referred to as a tenant and represented in Auth0 as a Client).

tenants are equivalents of clients in Auth0. 
I don't this the case most of the time. For ex, Clients can be SPAs, a CLI app, or a server app etc. So, I don't think we can represent tenants as clients. Clients are not groups of users.

**Comment by mpaktiti** [comment]
You are absolutely right, we removed that part https://github.com/auth0/docs/pull/4838

Thank you for pointing that out! 👍
