### ISSUE TITLE
GO lang tutorial no environment configuration

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#4873]
(AUTH-4195)
[GO language tutorial](https://auth0.com/docs/quickstart/webapp/golang) doesn't describe how to set environment variables that can be received by `os.Getenv` function. We can either add step regarding `.env` file and how to load it either substitute `os.Getenv` call to string values with real credentials.
![image](https://user-images.githubusercontent.com/1114365/29665280-181af192-88dc-11e7-8215-459cb3bed32f.png)

**Comment by albertoperdomo** [comment]
Related to https://github.com/auth0/docs/issues/5933.
Addressed in https://github.com/auth0/docs/pull/6556.
