### ISSUE TITLE
Yubikey multifactor authentication article example not working

### ISSUE THREAD

**Issue by santiagoaguiar** [auth0/docs#4889]
I stumbled into a couple of roadblocks for completing [this example](https://github.com/auth0/docs/blob/master/articles/multifactor-authentication/yubikey.md):
1. Access to configuration variables `WEBTASK_URL` & `YUBIKEY_SECRET` (I've submitted a PR #4888 for that one).
2. The `otp` property was not available on `context.data`. Since the function signature is `function(context, req, res)`, and according to [this](https://webtask.io/docs/api_issue), it seems that, since `pb` is 2 by default, the request body is left unread and not added to `context.data`. 

To fix 2, I added an additional require for `body-parser`:
```js
var bodyParser = require('body-parser')
var urlencodedParser = bodyParser.urlencoded({ extended: false });
```
And a new function on the async series before calling `yubico_validate`:
```js
     /*
     * 2. Parse the form body
     */
        function(callback) {
            if (req.method === 'POST') {
                return urlencodedParser(req, res, callback);
            }            
            return callback();
        },
```

And use `req.body.otp` instead of `context.data.otp`.

I can submit it as a PR too, but I'm new to the platform, so maybe there is a better way to do it?.

Thanks!

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/4888/
