### ISSUE TITLE
Auth0 + NodeJS API Seed - README.md has outdated instructions

### ISSUE THREAD

**Issue by javlc** [auth0/docs#49]
If you review the _README.md_ file created with the _Auth0 + NodeJS API Seed_ project you will notice that there are two issues:
- does not specify the required command `npm install` 
- it asks the user to create the `.env` file and do a configuration that already exists in the project files.

Please see the attached image.

![image](https://cloud.githubusercontent.com/assets/3148402/7827730/d4a78408-03f8-11e5-9805-4545cf6e4ad1.png)

Javier
(in behalf of TechAID)

**Comment by javlc** [comment]
UPDATE: The issue above is not on this repo, but on:
Repo location: https://github.com/javilopezc/node-auth0/tree/master/examples/nodejs-api
The update is being applied on the README.md file there, as per this issue #49 in AUth0 docs repo.

**Comment by aguerere** [comment]
This is already fixed in the respective seed project repo here: https://github.com/auth0/node-auth0/blob/master/examples/nodejs-api/README.md
