### ISSUE TITLE
"Next Steps" links on "Lock for Android" page are 404s

### ISSUE THREAD

**Issue by d60402** [auth0/docs#4917]
Four of the five **Next Steps** links at the very bottom of the **Lock for Android** page (https://auth0.com/docs/libraries/lock-android) are 404s. The are...

- Customizing the Style of Lock
- Customizing the Behavior of Lock
- Adding Custom Signup Fields to Lock
- Lock Internationalization

**Comment by jeffreylees** [comment]
This will be fixed by https://github.com/auth0/docs/pull/4943

Thank you!
