### ISSUE TITLE
"Additional Documents" on Lock for Android page links to nothing

### ISSUE THREAD

**Issue by d60402** [auth0/docs#4918]
There is no **Additional Documents** anchor on the **Lock for Android** page that the following tries to link to...

> Get started using Lock for Android below, or if you're looking for a specific document, try the listing of [additional documents](https://auth0.com/docs/libraries/lock-android#additional-documents) related to Lock for Android.

**Comment by jeffreylees** [comment]
This will be fixed by https://github.com/auth0/docs/pull/4943

Thank you!
