### ISSUE TITLE
Navigation pane doesn't highlight current docs page

### ISSUE THREAD

**Issue by ghost** [auth0/docs#4938]
When navigating the docs pages, the left pane doesn't indicate which page is currently being viewed, which makes for a challenge in sequential reading of the docs. Also, it would be nice to have Next and Prev links at the bottom of docs pages to avoid having to scan the left navigation pane to figure out what the next docs page would be.

**Comment by mpaktiti** [comment]
Hello. Thank you for your input. I'm very sorry it took us so long to respond. We are currently running a big project to restructure our Information Architecture and the issues you are mentioning are part of the discussion so hopefully you'll soon see some good changes in our navigation. Thanks again for the feedback!
