### ISSUE TITLE
Code typo in example on Authentication docs page

### ISSUE THREAD

**Issue by ghost** [auth0/docs#4939]
On https://webtask.io/docs/auth (in 2 code snippets)

Currently:

res.end('Hello, world!');

Should be:

res.send('Hello, world!');

**Comment by Misara** [comment]
Does this still need to be fixed? I could take a look at it.

**Comment by ghost** [comment]
Yes, it does, at your earliest convenience, please.

**Comment by Misara** [comment]
Where is the source file for the page? I can't find it

**Comment by mpaktiti** [comment]
Hey, the webtask.io source file are not part of this repo, but of another private one.

I will send a fix for this. Thank you!
