### ISSUE TITLE
How to handle hash-location strategy in Angular 2

### ISSUE THREAD

**Issue by chriscurnow** [auth0/docs#4983]
In the Angular 2 quickstart you have a note:

> This example assumes you are using the default Angular path-based routing. If you are using hash-based routing with { useHash: true }, you will not be able to specify a dedicated callback route. The URL hash will be used to hold the user's authentication information.

Two things about this.

1. What DO you do if you have to use the hash location strategy? Does that mean you can't use Auth0? It would be really nice if you let us know what you suggest rather than just leaving us hanging.

1. It would be nice if you put this right up the top of the quick start. IE: 'This tutorial assumes you are NOT using the hash location strategy.' It's quite disappointing to be carefully following the tutorial and then come to an abrupt dead end.

I'm not being super critical here. Your documentation and tutorials are amongst the best I have seen. You have done a fantastic job on them. However, it does happen quite a bit that you can be following a tutorial and come to an abrupt dead end. Also I really like Auth0.

**Comment by albertoperdomo** [comment]
Hello,

this question might be a good fit for our community site at https://community.auth0.com/.
This is not an issue with docs. Closing.
