### ISSUE TITLE
Uncaught Error: Can't resolve all parameters for Router: (?, ?, ?, ?, ?, ?, ?, ?).

### ISSUE THREAD

**Issue by HasakiWMC** [auth0/docs#5108]
When I add "constructor(public router: Router) {}"  in src/app/auth/auth.service.ts, it showed "Error: No provider for Router!".

`src/app/auth/auth.service.ts`
```
  constructor(public router: Router) {}

  public login_in(): void {
    this.auth0.authorize();
  }

```
So I add Router in src/app/app.module.ts, it became "Uncaught Error: Can't resolve all parameters for Router: (?, ?, ?, ?, ?, ?, ?, ?)."

`src/app/app.module.ts`
```
providers: [
    StatusBar,
    SplashScreen,
    AuthService,
    Router,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
```

I use ionic version 3.12.0,  is it cased by version conflicts?

**Comment by amormason** [comment]
i have the same error in my testing file.

**Comment by cocojoe** [comment]
Please try the latest version and re-open if still an issue. thanks.
