### ISSUE TITLE
Wrong audience parameter in Angular2 docs.

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#5129]
In the Set the Audience and Scope in auth0.WebAuth section of the Angular 2- 03 Calling an API doc (https://auth0.com/docs/quickstart/spa/angular2/03-calling-an-api#set-the-audience-and-scope-in-auth0-webauth), the audience shown in the snippet is not the correct.

This also happens in the 05-token-renewal tutorial (https://auth0.com/docs/quickstart/spa/angular2/05-token-renewal#add-token-renewal)

For example, I'm logged in a tenant in Australia region, and no matter how many times I reload the page, clean the cookies, close and open the windows, the audience parameter still shows the audience from the European region tenant.

I've tried changing tenant within the same region and it appear to be ok, but when I try with my AU or US tenants, it is stuck with the EU URL.

AUTH-3348.

**Comment by albertoperdomo** [comment]
Just tried reproducing. If I switch tenants in the docs navigation menu (top right), the right audience is displayed.
Closing.
