### ISSUE TITLE
Wrong audience parameter in AngularJS docs

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#5133]
In the Set the Audience and Scope of the Angular 1.x - 03 Calling an API tutorial (https://auth0.com/docs/quickstart/spa/angularjs/03-calling-an-api#set-the-audience-and-scope), the audience shown in the snippet is not the correct.

It always show the URL of my EU tenant, while I'm logged in either my AU or US tenants.

AUTH-3812

**Comment by albertoperdomo** [comment]
Switching tenants in docs (as opposed to in manage) works. Closing.
