### ISSUE TITLE
Wrong audience parameter in Spring Security Java API doc.

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#5196]
In the Configure your Spring Security API section of the Spring Scurity Java API doc (https://auth0.com/docs/quickstart/backend/java-spring-security#configure-your-spring-security-api)

![3385doc](https://user-images.githubusercontent.com/15818783/31965671-0b1e8f2e-b8d6-11e7-96d4-5365ef8e9d3c.png)

As you can see in the `auth0.issuer` I'm logged with a AU account, but the `auth0.apiAudience` show my other account (EU)

AUTH-3385

**Comment by albertoperdomo** [comment]
Switching tenants in docs works. Closing.
