### ISSUE TITLE
Auth0 + JQuery Seed project - different auth0 cdn version in project file

### ISSUE THREAD

**Issue by javlc** [auth0/docs#52]
There is a discrepancy on the auth0 cdn version shown in the seed project and the one shown in the doc instructions. This may render different results when instructions are followed by users.

**Doc Instructions image**
![image](https://cloud.githubusercontent.com/assets/3148402/7828267/4f57f844-03ff-11e5-8a1e-8573927c7717.png)

**Seed project index.html file**
![image](https://cloud.githubusercontent.com/assets/3148402/7828279/717ba01a-03ff-11e5-80b4-567dd5a73724.png)

**Comment by iannyanes** [comment]
Please check 

https://github.com/auth0/auth0-jquery/blob/gh-pages/examples/pubnub-example/index.html
https://github.com/auth0/auth0-jquery-api-sample/blob/gh-pages/index.html
https://github.com/auth0/auth0-jquery/blob/gh-pages/examples/sso-multiple-apps/one/index.html
https://github.com/auth0/auth0-jquery/blob/gh-pages/examples/sso-multiple-apps/two/index.html
https://github.com/auth0/auth0-jquery/blob/gh-pages/examples/widget-with-api/index.html

Just an example. Please do a in depth check to look for more outdated lock references

**Comment by iannyanes** [comment]
Checking on https://techaid.atlassian.net/browse/AUTH-360

**Comment by mpaktiti** [comment]
[Assigned](https://techaid.atlassian.net/browse/AUTH-3257)

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/2224
