### ISSUE TITLE
undefined function checkJwt

### ISSUE THREAD

**Issue by amiram** [auth0/docs#5210]
In this docuement:
docs/articles/architecture-scenarios/implementations/spa-api/api-implementation-nodejs.md

There is a function checkJwt that appears in the arguments of app.post. This looks like a mistake since it is not defined anywhere.

**Comment by RaphaelSchein** [comment]
I Found this at another place in the docs
https://auth0.com/docs/quickstart/backend/nodejs/01-authorization

**Comment by mpaktiti** [comment]
Thank you @amiram, we fixed this 👍
