### ISSUE TITLE
Fix font color (dark grey on black) for apiv2 samples

### ISSUE THREAD

**Issue by yvonnewilson** [auth0/docs#523]
Code samples on apiv2 page show up with dark grey font on black background, making them almost impossible to read.
This happens on chrome, firefox and safari browsers.
Several refreshes in chrome did not fix the issue.
URL is auth0.com/docs/apiv2 - I was looking at update user api call.
![screen shot 2015-10-30 at 9 20 34 am](https://cloud.githubusercontent.com/assets/9997803/10851442/5e32f896-7ee8-11e5-9db6-2c1ae0a0ebca.png)

**Comment by ntotten** [comment]
Wrong repo. Fixed in https://github.com/auth0/auth0-docs/commit/1162694eb85ea02aff12667c6b78c8e52356baf1
