### ISSUE TITLE
User ID array listed in the Add Nested Groups doc should be Group ID array

### ISSUE THREAD

**Issue by binlabs** [auth0/docs#5257]
In the `docs/articles/api/authorization-extension/_groups.md` document under the Add Nested Groups section, the PATCH operation sample shows an Auth0 User ID in an array as part of the request body:
```
Content-Type:   'application/json'
Authorization:  'Bearer {access_token}'
[ "google-oauth2|113108011846505476166" ]
```
This should actually be an array of Group IDs, as it represents an array of groups that you'd like to nest under the group ID specified by the `{group_id}` parameter in the URL.

Also, in the table that this code sample accompanies is listed a `{member_id}` parameter and description.
```
{member_id} | List of members to add in a group
```

This should be updated to describe that it is in fact expecting Group IDs in that array.

**Comment by khorne3** [comment]
Fixed and closing.
