### ISSUE TITLE
VUE Quickstart: Difference between snippet and code from the sample project.

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0/docs#5286]
Vue.js quickstart: https://auth0.com/docs/quickstart/spa/vuejs

There's a difference between the quickstart project code and the snippet code in the tutorial page.
Specifically the import section in the files below:

- src/Auth/AuthService.js
- src/App.vue
- src/components/Callback.vue

![image](https://user-images.githubusercontent.com/26749061/32968845-21ded214-cbb9-11e7-9f8a-58226a6fed72.png)

![image](https://user-images.githubusercontent.com/26749061/32968867-324cd83a-cbb9-11e7-9275-bf24aca65f1b.png)

![image](https://user-images.githubusercontent.com/26749061/32968905-55e77728-cbb9-11e7-8e9c-8015f2d7645b.png)

**Comment by albertoperdomo** [comment]
Fixed via #5712.
