### ISSUE TITLE
Quickstart Vue:File location that contains the variables client ID and Domain is missing

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0/docs#5288]
A directory path description is missing, this will allow
the users verify the information regarding the clientID
and domain in the project directory 
(from the sample project downloaded)
For example, you can verify if the client ID and domain 
is set going to the following file in the project directory.
This will allow the users verify the set of this information in the project downloaded.

![image](https://user-images.githubusercontent.com/26749061/32969185-75b943a0-cbba-11e7-8d64-1d8349f92f7e.png)

**Comment by paulioceano** [comment]
@aaguiarz This situation is similar to #5317, even when in the "Get Your Application Keys" doesn't state where client ID and Domain values will be filled, this is shown in the [Create an Authentication Service section](https://auth0.com/docs/quickstart/spa/vuejs#create-an-authentication-service) and is explained in the Readme file of the sample project.

I consider that this is not an issue that should be fixed.
