### ISSUE TITLE
User impersonation: get an authorization code snippet is wrong

### ISSUE THREAD

**Issue by Pyrolistical** [auth0/docs#5312]
On https://auth0.com/docs/user-profile/user-impersonation#2-get-an-authorization-code we have
```
curl --request POST \
  --url 'https://battlefy.auth0.com/oauth/token' \
  --header 'content-type: application/json' \
  --data '{"client_id": "kEGLWJeVMqikskGZFnjBJKmVxDWEXsdA","client_secret": "2XbOZWMJoNuQOvL-ZWHMlBfZJDkEScKWhBylG_kVPQsVUeXjXXaYFUS5DSIV59KD","code": "AUTHORIZATION_CODE","grant_type": "authorization_code","callback_url": "https://YOUR_APP/callback"}'
```

But when I tried it, I got the error `redirected_uri` is expected to be a string, but was undefined.

I changed callback_url to redirect_uri and it worked. Docs confirm it is suppose to be redirect_uri: https://auth0.com/docs/api/authentication#get-token

**Comment by mpaktiti** [comment]
Thank you @Pyrolistical , we'll fix that.
