### ISSUE TITLE
Python webApp: missing file directory information in order to verify the filled correctly of the client ID and Domain variables in the tutorial page.

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0/docs#5317]
Can't see the directory in the tutorial page where the user can verify that the information of their client ID and domain were correctly filled As shown in the readme.md

![image](https://user-images.githubusercontent.com/26749061/33175808-4249f992-d033-11e7-83a9-40960dfa056b.png)

**Comment by paulioceano** [comment]
@alexisluque @aaguiarz  I checked python quickstart and in the [Initialize Flask-OAuthlib section](https://auth0.com/docs/quickstart/webapp/python#initialize-flask-oauthlib) show how to fill client ID and domain.

What it does not show is the part where the Application Keys can be found pre-filled in the .env file 
(But this is stated in the README.md file), I think that this is not an issue that should be fixed.

**Comment by albertoperdomo** [comment]
This is handled differently on sample code (use `.env`) vs tutorial (hardcoded in `server.py`.
