### ISSUE TITLE
ASP.NET Core backend: Missing methods in the snippet code sample.

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0/docs#5341]
There are missing methods in the code snippet, specifically in the file:
//Controllers/PingController.cs

![image](https://user-images.githubusercontent.com/26749061/33334863-c4889d34-d441-11e7-9270-ff3a9779d5cf.png)

**Comment by albertoperdomo** [comment]
Mentioned code no longer in sample. Closing.
