### ISSUE TITLE
WebApp Laravel Quickstart: There are some differences between the snippet code and the quickstart project.

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0/docs#5361]
There are some differences between the snippet code and the quickstart project.
Specifically in the file:
// config/app.php

![image](https://user-images.githubusercontent.com/26749061/33444068-9741e33c-d5cf-11e7-9f99-bcb9a06cd36f.png)

**Comment by fuzzyjared** [comment]
It looks like the snippets were taken from an earlier version of Laravel where they used the long format of array( instead of [.
