### ISSUE TITLE
Backend Java Spring Security: Prerequisites only have instructions for MacOS.

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#5391]
The instructions in the readme file, are only for MacOS and it doesn"t specify it.

https://github.com/auth0-samples/auth0-spring-security-api-sample/tree/master/01-Authorization

![capture-for-jira-screenshot-20171205-110521-202](https://user-images.githubusercontent.com/15818783/33671429-f3ce31e8-da7d-11e7-92d6-4dba6490b52f.png)

**Comment by cocojoe** [comment]
This appears to have been updated, thanks
