### ISSUE TITLE
Backend Java Spring Security: No filepath

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#5392]
In some code snippets of the tutorial, the filepath is missing
(https://auth0.com/docs/quickstart/backend/java-spring-security)

![capture-for-jira-screenshot-20171205-111303-476](https://user-images.githubusercontent.com/15818783/33671506-300e6132-da7e-11e7-9fa8-3fc0b7b26cc4.png)
![capture-for-jira-screenshot-20171205-111333-350](https://user-images.githubusercontent.com/15818783/33671507-303be7ec-da7e-11e7-85f9-d7a3e03c8ced.png)

**Comment by cocojoe** [comment]
These are config and not code snippets. The filename is clearly stated before the snippet for configuration.
