### ISSUE TITLE
Backend Java Spring Security: Outdated dependency.

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#5393]
The version for auth0-spring-securityapi dependency is outdated in the tutorial.

https://auth0.com/docs/quickstart/backend/java-spring-security#install-the-dependencies

![capture-for-jira-screenshot-20171205-112817-007](https://user-images.githubusercontent.com/15818783/33671587-62647d88-da7e-11e7-9d32-c4ce76d0ab7d.png)

**Comment by aaguiarz** [comment]
@lbalmaceda can we update this already, or should we keep using RC2?

**Comment by paulioceano** [comment]
@aaguiarz in the sample project the dependency used is:

```
  <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>auth0-spring-security-api</artifactId>
            <version>1.0.0-rc.3</version>
        </dependency>
```

**Comment by lbalmaceda** [comment]
Thanks for the report. This was already fixed. 🌮
