### ISSUE TITLE
Backend Java Spring Security: Client secret shown

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#5394]
In the example to obtain an access token in order to Use the API:

- https://auth0.com/docs/quickstart/backend/java-spring-security#use-the-api

The client secret of the client used is shown.

![capture-for-jira-screenshot-20171206-103123-254](https://user-images.githubusercontent.com/15818783/33671680-a774cd38-da7e-11e7-96ea-c4e23863097b.png)

**Comment by mpaktiti** [comment]
@aaguiarz This is a variable we use in several docs, so unless there was some decision not to use it any longer at docs, then this issue is invalid.
