### ISSUE TITLE
rails session hash keys accessed as symbols creates an error

### ISSUE THREAD

**Issue by pgainullin** [auth0/docs#5398]
accessing as strings works fine

**Comment by albertoperdomo** [comment]
Please review @joshcanhelp.

**Comment by joshcanhelp** [comment]
Do we have a link here? String access is fine, hash access would require converting it or using [`HashWithIndifferentAccess`](https://api.rubyonrails.org/v4.2/classes/ActiveSupport/HashWithIndifferentAccess.html), which can be slow. I'd rather address this throughout the SDK if deemed necessary.
