### ISSUE TITLE
WebApp Java Servlet: No instructions for windows.

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#5409]
In the section Run the Sample: https://auth0.com/docs/quickstart/webapp/java#run-the-sample
The instructions for run the project are not valid for Windows, this might confuse a new user that hasn't used Gradle before.

![capture-for-jira-screenshot-20171207-125255-793](https://user-images.githubusercontent.com/15818783/33771574-cec762f8-dc07-11e7-959b-4bbba6de5538.png)

**Comment by albertoperdomo** [comment]
Wont fix.
