### ISSUE TITLE
Hooks with grant_type password does not work

### ISSUE THREAD

**Issue by hidegh** [auth0/docs#5444]
I've tried to create a hook to get extra claims into an id_token.
It did not woked with grant_type password, but it worked with grant_type client credentials.
With rules ("old school") had no problems to achieve my goal.

**Comment by khorne3** [comment]
Hi @hidegh! I'm assuming you're using the Credentials Exchange Extensibility Point? If so, the behavior you're describing is correct -- we're rolling out Hooks-related features over time, so not everything that can be done with Rules can be done with Hooks...yet. :)

**Comment by hidegh** [comment]
Ok, so let's state it so:

**The HOOKS (credentials exchange extensibility point) has a bug.
If grant_type "password" is used, it does not get executed.**

It works when u use grant_type "client credentials". But that's not our use case. So I had to revert to old-school rules, because extending credentials even with grant_type "password" worked with it. This was a necessary step, due to the bug with HOOKS.
