### ISSUE TITLE
Scopes issue in backend Golang quickstart

### ISSUE THREAD

**Issue by edevil** [auth0/docs#5466]
I've completed the quickstart up until the point of scopes.

I've added the "read:messages" scope on the API dashboard, but I assume I need to obtain a new token with this scope? The test token does not have it.

I've tried to request a new token with this scope but obtain the error:

```
{"error":"access_denied","error_description":"Client has not been granted scopes: read:messages"}
```

What additional steps do I need to take?

**Comment by albertoperdomo** [comment]
If you can't find an answer to this question in our docs or Quickstarts, I would suggest posting on our community site at https://community.auth0.com/
