### ISSUE TITLE
Specify `leeway` unit of time

### ISSUE THREAD

**Issue by lorensr** [auth0/docs#5469]
seconds or ms?

![image](https://user-images.githubusercontent.com/251288/34231481-448e1184-e5aa-11e7-8068-bacdfffb9cd4.png)

**Comment by jeffreylees** [comment]
Hey @lorensr thanks for the feedback, we definitely should specify a unit there. 

In case you needed to know yourself, the value passed here should be in seconds.

Thanks again! https://github.com/auth0/docs/pull/5503 will resolve this.
