### ISSUE TITLE
Building docs locally

### ISSUE THREAD

**Issue by gidim** [auth0/docs#5524]
How do I build the docs locally with the UI? I'd like to make sure things look good before contributing. Thanks!

**Comment by jerdog** [comment]
The README file has the local test instructions
https://github.com/auth0/auth0-docs/blob/master/README.md

**Comment by gidim** [comment]
Maybe it's a private repo? URL returns 404

**Comment by jerdog** [comment]
Let me get to my laptop and I will review getting you test instructions

**Comment by jerdog** [comment]
Ok so we don't have a good way currently for you to test docs locally - I will check this with our Docs team to see if we can provide

**Comment by mpaktiti** [comment]
You cannot build this locally as that repository is private. We do use Heroku though so you can use that. When you have created your PR, ping me and I will trigger this so you can check your changes online. Thanks!
