### ISSUE TITLE
Mobile Android: No filepath in some snippets

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#5526]
Missing filepath in:

- Login
- User Profile

As shown in the images:

![capture-for-jira-screenshot-20171221-122717-166](https://user-images.githubusercontent.com/15818783/34488584-6e4d7e74-efaf-11e7-9bd0-3c6f7b923283.png)
![capture-for-jira-screenshot-20171221-122755-714](https://user-images.githubusercontent.com/15818783/34488585-6eb14648-efaf-11e7-9168-7822427bae7a.png)
![capture-for-jira-screenshot-20171221-123613-570](https://user-images.githubusercontent.com/15818783/34488587-6f18acca-efaf-11e7-96b0-c7a91612d4aa.png)

**Comment by arshadkazmi42** [comment]
What exactly is the file paths needed? path where respective file needs to be stored?

**Comment by albertoperdomo** [comment]
Hello @arshadkazmi42,

usually, in the code snippets, we add a comment at the very top pointing to the file that needs to be added or modified. See https://auth0.com/docs/quickstart/webapp/nodejs as an example.

![screen shot 2018-10-01 at 4 26 36 pm](https://user-images.githubusercontent.com/24216/46298379-d3900f00-c596-11e8-9e88-3d941a06f69b.png)

```
// app.js

[...]
```

**Comment by arshadkazmi42** [comment]
@albertoperdomo Thanks for the detailed info. I will look into it.

**Comment by arshadkazmi42** [comment]
In this, issue reported in third image is already fixed. Validated here.

https://auth0.com/docs/quickstart/native/android/04-user-profile#before-you-start

**Comment by albertoperdomo** [comment]
Hello @arshadkazmi42,

Thanks for the update.
If there are still some code blocks where the filename is missing you are still welcome to submit a PR for those.

Alberto.

**Comment by arshadkazmi42** [comment]
@albertoperdomo Should I update the same PR or should I create a new PR.

**Comment by albertoperdomo** [comment]
I would keep it to 1 PR per platform, i.e. 1 for Android, 1 for X... etc.
Feel free to update several tutorials (01-login, 04-user-profile) in the same or different PRs.
