### ISSUE TITLE
Request for Auth0 doc on Cognito integration

### ISSUE THREAD

**Issue by carlhunterroach** [auth0/docs#5553]
I'm using `auth0/Lock.swift` 2.4.2 & `auto0/Auth0.swift` 1.9.2 and am trying to integrate Auth0 code with AWS Cognito Federated Identities.

The main Auth0 page on [integrating with Cognito](https://github.com/auth0/docs/blob/master/articles/integrations/integrating-auth0-amazon-cognito-mobile-apps.md) links to an [AWS page](https://docs.aws.amazon.com/cognito/latest/developerguide/open-id.html) and in the `iOS - Swift` section there are comments where Auth0 code would go `//TODO code to get token from your server` 

Do you have a complete sample that integrates the latest Lock/Auth0 with Cognito?
If not, do you have an example of the code that would replace `//TODO code to get token from your server`? That would help round-off your page on this integration.

**Comment by khorne3** [comment]
Hey! We don't have plans to rewrite this for the time being, so if you need assistance with getting tokens from Auth0 using iOS/Swift, check out [this SDK](https://auth0.com/docs/quickstart/native/ios-swift).
