### ISSUE TITLE
How to update password via Management API v2 ?

### ISSUE THREAD

**Issue by NikhilNanjappa-zz** [auth0/docs#5603]
I have a mobile application. I am trying to update/change the password of a registered user. I dont want to use the Authentication API to send an email. I need a way to update directly via a Management API.

This document says it exists but does not allow to change the password. Is this document outdated ? If not could you please help me with resolving my issue.
https://auth0.com/docs/connections/database/password-change#using-the-management-api

**Comment by mpaktiti** [comment]
Hey there @NikhilNanjappa 

Are you calling from your mobile app the [Update user endpoint](https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id) and you get back an error?  What error is that?

**Comment by NikhilNanjappa-zz** [comment]
Hey @mpaktiti 

The error message I am getting is something like "you do not have permission to change the password or dbconnections".

I assume my scope does not have the rights to change the password. But how else can I do it then?

**Comment by mpaktiti** [comment]
@NikhilNanjappa I tried this for my tenant and it worked (I even logged in with the new password). Can you tell me a) the scopes that your access token contains (you can use https://jwt.io/ to check this) b) copy here your request (removing your tenant name, user id, and token)

**Comment by mpaktiti** [comment]
Hey there @NikhilNanjappa do you still need help with this or should I go ahead and close it?

**Comment by mpaktiti** [comment]
Hey @NikhilNanjappa I'm gonna go ahead and close this. If the issue persists please reopen this and post the info I asked for so I can troubleshoot. Thanks!
