### ISSUE TITLE
Provide Names (nickname, given_names etc) while creating user using Auth API

### ISSUE THREAD

**Issue by NikhilNanjappa-zz** [auth0/docs#5604]
While using the authentication API(**/dbconnections/signup**), how do I give a name/nickname/given_name to that new user ? (Not as part of user_metadata).

While retrieving user details using management API(**/api/v2/users/{userID}**), I see fields like "nickname" and "name". How do I set these values while creating a user via authentication API ?

**Comment by mpaktiti** [comment]
Hello @NikhilNanjappa 

With the [/dbconnections/signup](https://auth0.com/docs/api/authentication#signup) you can only set the `email` and `user_metadata`. If you want to keep using this endpoint and update these fields (`name`, `nickname`, `given_name`) you can create new properties in the `user_metadata` and set these values upon signup using the [/dbconnections/signup](https://auth0.com/docs/api/authentication#signup) endpoint. Then you can either use those `user_metadata` properties to display this info at your UI, or use a rule like in this example: [Change a User's Picture](https://auth0.com/docs/user-profile/user-picture#change-a-user-s-picture).

Alternatively, you can use the [Management API](https://auth0.com/docs/api/management/v2#!/Users/get_users). If you do, note the following:

- The user attributes `name`, `nickname`, and `picture`, are not editable. What you can do is replace them with new properties in the `user_metadata` that will hold this information (for an example on how to update the `picture` see [Change a User's Picture](https://auth0.com/docs/user-profile/user-picture#change-a-user-s-picture)).
- You can set a value for `given_name` if you create a user using the Management API, but these fields are not available to be edited with the update a user endpoint.

I hope this helps.
