### ISSUE TITLE
 Cannot find module 'auth0-js'.

### ISSUE THREAD

**Issue by hayanisaid** [auth0/docs#5608]
I get this message in the service file  ` Cannot find module 'auth0-js'.`
 I implement the auth0 module in index.html and I installed it via npm
here is what it look like in index.html

`<script type="text/javascript" src="node_modules/auth0-js/build/auth0.js"></script>`

and the service file 

`import * as auth0 from 'auth0-js';`

**Comment by mpaktiti** [comment]
Hey there @hayanisaid ! 

To resolve problems with your implementation it is best if you use our [Support](https://support.auth0.com/). Note that if you have a free subscription, and you are not in the initial 22-day trial period, then support will not be available but you can still post your question at our  [Community](https://community.auth0.com/). 

If I misunderstood and you want to report an issue with our docs please re-open this issue.

Thank you!
