### ISSUE TITLE
Native Windows Universal: Typo in the documentation

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#5614]
In the Auth0 documentation, the name is Windows Universal App C# (https://auth0.com/docs/quickstart/native/windows-uwp-csharp), but, when you click "Fork on Github" and get redirected to the repo (https://github.com/auth0-community/auth0-uwp-oidc-samples/tree/master/Quickstart/00-Starter-Seed), the readme file says: "This example shows how to add Login/SignUp to your Windows Universal Platform application using the Auth0 OIDC Client for .NET.".

![capture-for-jira-screenshot-20180117-112742-220](https://user-images.githubusercontent.com/15818783/35154962-8ba9669e-fd02-11e7-9882-84729741788b.png)
![capture-for-jira-screenshot-20180117-113129-413](https://user-images.githubusercontent.com/15818783/35154963-8bcb9430-fd02-11e7-95f5-6b4017189085.png)

**Comment by albertoperdomo** [comment]
Fixed via https://github.com/auth0-community/auth0-uwp-oidc-samples/pull/2.
Closing.
