### ISSUE TITLE
Native Windows Universal: Inconsistency between the sample and the documentation.

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#5616]
This code line:

´var loginResult = await client.LoginAsync();´

Doesn't appear in the code of the sample project. This code line doesn't specify where the user should use this line, and the explanation sugest that it belongs to the previously explained method, but this line is not present in the entire MainPage.xaml.cs file of the sample.

The code line that looks more alike is:

´DisplayResult(await client.LoginAsync(extraParameters: extraParameters));´

![capture 2018-01-03 at 14 13 12](https://user-images.githubusercontent.com/15818783/35156239-9e56c774-fd06-11e7-8624-67d71c75c616.png)
![Uploading Capture 2018-01-03 at 14.13.43.png…]()

**Comment by albertoperdomo** [comment]
The tutorial provides basic guidance, while sample goes well beyond that into a more elaborate implementation.
Won't fix.
