### ISSUE TITLE
Django Tutorial: Wrong API_IDENTIFIER when downloading sample project

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#5631]
When downloading the sample project, directly from the QS (https://auth0.com/docs/quickstart/backend/django/01-authorization), the prepopulated API_IDENTIFIER is from the wrong tenant. The steps followed for this:

- Login to my Auth0 tenant (that open to my default tenant), then switch to another tenant.
- In a new tab, open the Django tutorial (https://auth0.com/docs/quickstart/backend/django/01-authorization), download the sample project.
- Open the .env file, and in the field API_IDENTIFIER, I get the an identifier from the default tenant that is not registered in the current open tenant:

![screenshot_1](https://user-images.githubusercontent.com/15818783/35288072-2fd033c6-003a-11e8-98c7-3f383a51e952.jpg)

If I go to the clients section of my tenant and download the sample in the quickstart tab, the API_IDENTIFIER field is not populated:

![screenshot_2](https://user-images.githubusercontent.com/15818783/35288457-1925e70a-003b-11e8-9543-6346cef6e18a.jpg)

**Comment by albertoperdomo** [comment]
Tenant switching for Quickstarts needs to happen in docs, not manage. Closing.
