### ISSUE TITLE
Bad link in Vanillajs tutorial

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#565]
On VanillaJS tutorial, on this line To discover all the available arguments for lock.show, see the Auth0Lock documentation. the Auth0LockDocumentation points to this link https://auth0.com/libraries/lock and it doesn't work.

**Comment by Annyv2** [comment]
React and jquery had this same issue

**Comment by Catografix** [comment]
Sould these kinks be in the form of (/libraries/lock) ? The above changes are hard-coded ()
Ive found 13 other articles with the (/lock) link that I can update:
\articles\apps-apis.md
\articles\hrd.md
\articles\hrd.md
\articles\hrd.md
\articles\connections\social\auth0-oidc.md
\articles\connections\social\oauth2.md
\articles\libraries\login-widget.md
\articles\libraries\login-widget2.md
\articles\native-platforms\wpf-winforms.md
\articles\native-platforms\xamarin.md
\articles\scenarios\zendesk-sso.md
\articles\scenarios\zendesk-sso.md
\articles\server-platforms\laravel.md
