### ISSUE TITLE
tiny help doc grammar issue

### ISSUE THREAD

**Issue by dmbraasch** [auth0/docs#5702]
tiny grammar issue. 

maybe "applications"?

>>The framework provides the flexibility the company wants since the different grants can allow them to easily authorize the various types of **application** which need to communicate with the Timesheets API.

https://auth0.com/docs/architecture-scenarios/application/spa-api/part-1

**Comment by mpaktiti** [comment]
Thank you for reporting that @dmbraasch ! 👍
