### ISSUE TITLE
Docs: Lock & Social Login

### ISSUE THREAD

**Issue by JakobJingleheimer** [auth0/docs#5730]
The [When to use Lock](https://github.com/auth0/docs/blob/master/articles/libraries/when-to-use-lock.md) document appears to say that social login does not work with Lock, but then the screenshot immediately below shows social network logins.

Desired UI Attributes: | Lock | Custom UI
:- | -- | --
Adapts to a simpler process for username/password and social provider authentication | No | Yes

So I think the "no" and "yes" is incorrect in the table.

**Comment by jeffreylees** [comment]
Hey, terribly sorry, I totally overlooked this issue. I believe that what was intended here is that using a custom UI can allow you to adapt your authentication process to be simpler - a single button, fill in u/p in a form embedded in a header, whatever you need, whereas Lock doesn't really adapt to any of those types of needs.

However, the line item is confusing and seems a bit unnecessary, so I'll submit a PR this week to modify or remove it. 

Thanks @jshado1 !

**Comment by JakobJingleheimer** [comment]
@jeffreylees shouldn't you wait to close this issue until it's actually fixed? You can set the PR to automatically close this issue when the PR is merged by adding `closes #5730` in the PR body.
