### ISSUE TITLE
tiny wording issue in connections database ui,

### ISSUE THREAD

**Issue by dmbraasch** [auth0/docs#5739]
in the connections database ui, this feels like a tiny grammar issue. 

prefer "a username" 

Requires Username
Requires the user to provide an username in addition to email.

https://manage.auth0.com/#/connections/database/con_JBDnxnqXDj4Gjv4h/settings

**Comment by mpaktiti** [comment]
Good catch, thanks @dmbraasch ! 

This fixes a couple of occurrences in our docs https://github.com/auth0/docs/pull/5781
I also pushed a PR to fix the dashboard, I'll keep this issue open until it's merged.
