### ISSUE TITLE
Laravel Spark Tutorial

### ISSUE THREAD

**Issue by scottybo** [auth0/docs#5759]
There are many great tutorials on how to integrate Auth0 with Laravel but I can't find any guides on how to integrate with Laravel Spark.

If anyone has some experience with getting it up and running with the Spark User Repository I would be eternally grateful if you could share your knowledge.

**Comment by albertoperdomo** [comment]
Hello @scottybo,

I would suggest posting your question on our community site at https://community.auth0.com/.
Maybe someone there can help you out.

Closing this as it is not really an issue about our docs.
