### ISSUE TITLE
Sendgrid email provider documentation seems out-of-date

### ISSUE THREAD

**Issue by pmalouin** [auth0/docs#5765]
The instructions [here](https://auth0.com/docs/email/providers#configure-sendgrid-for-sending-email) seem to have an out-of-date screenshot.

The current "Create API Key" screen looks like this:
![image](https://user-images.githubusercontent.com/1411117/36505694-4c8fb1e0-1722-11e8-84f9-4dc26fe8e436.png)

**Comment by mpaktiti** [comment]
Fixed by @rkhoriander with https://github.com/auth0/docs/pull/5843

Thank you @pmalouin !
