### ISSUE TITLE
Explain or link acronyms

### ISSUE THREAD

**Issue by Nyholm** [auth0/docs#5768]
This section was added by @khorne3: https://github.com/auth0/docs/blob/master/articles/compliance/gdpr/roles-responsibilities.md#data-processor-auth0-responsibilities

It mentions "MSA" and "DPA" without any references to the actual documents or any explanation to what the acronyms mean.

**Comment by khorne3** [comment]
@Nyholm I apologize for the oversight. I've [updated the docs](https://github.com/auth0/docs/pull/5770) to include the full names. Thanks!

**Comment by Nyholm** [comment]
That is excellent. Thank you very much
