### ISSUE TITLE
Sidebar links broken

### ISSUE THREAD

**Issue by corysimmons** [auth0/docs#5774]
https://auth0.com/docs/extensions/authorization-extension/v2

Some sidebar links don't seem to work either.

```
Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

```
Error: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r._throwOrCallErrorHandler (https://cdn2.auth0.com/docs/js/client.2b0d46f844c032fa1365.bundle.js:1:24762)
    at r.dispatch (https://cdn2.auth0.com/docs/js/client.2b0d46f844c032fa1365.bundle.js:1:27021)
    at a (https://cdn2.auth0.com/docs/js/client.2b0d46f844c032fa1365.bundle.js:5:12425)
    at <anonymous>
```

Tried posting in Forum but it's broken too.

QA sprint gogogo

**Comment by corysimmons** [comment]
Page suddenly works.

Sidebar still broken. Reproduce:

1. Click "Integrations" a few times until it expands.
2. Click "Single Sign On". Nothing happens.
3. Click "Marketing" a few times until it expands.
4. Click any of those links. Nothing.

**Comment by mpaktiti** [comment]
Hey there @corysimmons We pushed a couple of fixes and I can no longer reproduce this behaviour. In case you do please re-open this issue.

Thanks for taking the time to report this, we really appreciate it! 👍
