### ISSUE TITLE
Link to GitHub from asp.net core quickstart is broken

### ISSUE THREAD

**Issue by davidelettieri** [auth0/docs#5822]
The link "Any suggestions or typos? Edit on GitHub" at bottom of the page lead to https://github.com/auth0/docs/edit/master/articles/quickstart/webapp/aspnet-core/00-intro.md which is a 404.
It should be pointing to https://github.com/auth0/docs/blob/master/articles/quickstart/webapp/aspnet-core/v2/00-intro.md

**Comment by valerianpereira** [comment]
Guess this is done already. 
Please close the issue

**Comment by albertoperdomo** [comment]
Thanks for calling it out @valerianpereira.
