### ISSUE TITLE
Spring boot security example should explain how to retrieve User info from controller

### ISSUE THREAD

**Issue by kamal2311** [auth0/docs#5867]
Currently, the documentation does not show how can one retrieve the user profile information from inside the spring boot MVC controller after the request has been authorized. 

I am specifically talking about Implict Grant scenario where Angular is the SPA and spring boot is the API.
This being a very basic use case. A clear example and explanation will serve a huge number of developers working in this stack.

**Comment by cocojoe** [comment]
Closing, Angular SPA covers itself how to retrieve user profile.

**Comment by cocojoe** [comment]
Closing, Angular SPA covers itself how to retrieve user profile.
