### ISSUE TITLE
IETF RFC Url gives HTTP 404

### ISSUE THREAD

**Issue by facundofarias** [auth0/docs#5873]
The RFC url that is being used is returning http 404:
- Current [URL](https://tools.ietf.org/html/rfc6749).
- This [one](https://www.ietf.org/rfc/rfc6749.txt) should be used instead.

Cheers

**Comment by mpaktiti** [comment]
Hello @facundofarias. Can you tell me which page throws the 404? Thanks!

**Comment by facundofarias** [comment]
Hello @mpaktiti. Seems to be solved now!
Thanks
