### ISSUE TITLE
Go webapp quickstart using os.Getenv incorrectly.

### ISSUE THREAD

**Issue by theherk** [auth0/docs#5933]
As you can see [here](https://github.com/auth0/docs/blob/master/articles/quickstart/webapp/golang/01-login.md), scattered about are calls using `os.Getenv`. Some are correct; others are probably not.

``` go
domain := os.Getenv("AUTH0_DOMAIN") // Good
domain := os.Getenv("${account.namespace}") // Not good; unless you intend to set an environment variable called your namespace ... to your namespace.
```

I'm happy to open a PR, but there are two options.

### Option 1 - Just set the variable and let the user sort out getting from config, environment, etc.

``` go
	domain := "${account.namespace}"

	conf := &oauth2.Config{
		ClientID:     "${account.clientId}",
		ClientSecret: "YOUR_CLIENT_SECRET",
		RedirectURL:  "http://localhost:3000/callback",
		...
	}
```

### Option 2 - Use `os.Getenv` still, but correctly.

``` go
	domain := os.Getenv("AUTH0_DOMAIN")

	conf := &oauth2.Config{
		ClientID:     os.Getenv("AUTH0_CLIENTID"),
		ClientSecret: os.Getenv("AUTH0_CLIENTSECRET"),
		RedirectURL:  os.Getenv("AUTH0_CALLBACKURL"),
		...
	}
```

If using this option, it may be helpful to include instructions for setting the variable.

    AUTH0_DOMAIN=${account.namespace} \
    AUTH0_CLIENTID=${account.clientId} \
    AUTH0_CLIENTSECRET=YOUR_CLIENT_SECRET \
    AUTH0_CALLBACKURL="http://localhost:3000/callback"; \
    ./your_app
    // or
    export AUTH0_DOMAIN=${account.namespace}
    export AUTH0_CLIENTID=${account.clientId}
    export AUTH0_CLIENTSECRET=YOUR_CLIENT_SECRET
    export AUTH0_CALLBACKURL="http://localhost:3000/callback"
    ./your_app

- [os.Getenv documentation](https://golang.org/pkg/os/#Getenv).

**Comment by aaguiarz** [comment]
@alexisluque can you look at this?

**Comment by albertoperdomo** [comment]
I've addressed this with Option 1 in https://github.com/auth0/docs/pull/6556.

**Comment by albertoperdomo** [comment]
Thanks for taking the time to report this @theherk !
The downloadable sample does use env vars to populate the values. The Quickstart tutorial generally does not. It seems that the code was erroneously copied over and ended up like this.
