### ISSUE TITLE
Difference between code and samples

### ISSUE THREAD

**Issue by rafanog** [auth0/docs#5945]
In the [Android quickstart](https://auth0.com/docs/quickstart/native/android), There are some difference between the code and the samples:

- Session Handling:
In the "Log the user out" section:
![image](https://user-images.githubusercontent.com/15782359/38102325-e1da7812-3350-11e8-99e5-15a9345289ba.png)

- User Profile:
In the "Request user's info" section:
![image](https://user-images.githubusercontent.com/15782359/38103113-79844650-3353-11e8-98ae-fdba959eddff.png)

-Calling APIs:
At the "Get the user's access token" section:
![image](https://user-images.githubusercontent.com/15782359/38108098-d1013e16-3361-11e8-97d3-bb40b1695fb2.png)

At the "Attach token" section:
![image](https://user-images.githubusercontent.com/15782359/38116118-c4cdef48-337c-11e8-97c7-decc83eda418.png)

**Comment by albertoperdomo** [comment]
After reviewing, the changes don't seem appropriate.
In the sample, variables are assigned because they are declared above. In the tutorial, if this omitted it can cause confusion so it's better to leave it as is, IMO.

Closing.
