### ISSUE TITLE
`last_login` attribute is no longer available in rules

### ISSUE THREAD

**Issue by joseeantonior** [auth0/docs#5965]
https://auth0.com/docs/rules/current#rule-syntax

and

https://auth0.com/docs/user-profile/user-profile-structure

mention the user.last_login attribute being available for use in rules. However, after checking with crew-auth in Slack (https://auth0.slack.com/archives/C0LAJF9KQ/p1522788641000036), last_login is no longer supported in rules execution.

It is not clear if the items marked with an asterisk in the last document mentioned are no longer supported (4 items), but at least last_login isn't supported anymore. Docs should reflect the same.

**Comment by mpaktiti** [comment]
Fixed by https://github.com/auth0/docs/pull/6052

**Comment by webloem** [comment]
Current documentation here https://auth0.com/docs/rules/references/user-object still mention the fields. In practice they are not available right now.
