### ISSUE TITLE
Error Handling when user changes the password

### ISSUE THREAD

**Issue by dleitee** [auth0/docs#5987]
I'm using the updateUser's API to change the user's password at my app and I'm facing a problem when the user inserts a password that doesn't match the required Password Strength.

I want to show to the user what is the problem at the update with details, but the message that I receive at the failure is `Password is too weak`.

There is any way to get the error description (in this case, the Password Strength) in the failure callback?

**Comment by tamigoodall** [comment]
Am I supposed to approve the change or make it? I can't tell from the original comment if this is a fix for the docs or a fix I need to request from dev for a prompt or message.

**Comment by tamigoodall** [comment]
This is a dev issue. Docs cannot fix.
