### ISSUE TITLE
"Searchable Fields" section missing from v3 doc

### ISSUE THREAD

**Issue by d60402** [auth0/docs#5999]
The sentence "See searchable fields." in https://auth0.com/docs/users/search/v3 references a section that does not exist on the page (https://auth0.com/docs/users/search/v3#searchable-fields)

**Comment by mpaktiti** [comment]
This will be fixed by https://github.com/auth0/docs/pull/6048
You can check it out here https://auth0-docs-content-pr-6048.herokuapp.com/docs/users/search/v3/query-syntax#searchable-fields
