### ISSUE TITLE
Code-Block Syntax Highlighting breaks if language is not defined

### ISSUE THREAD

**Issue by lbalmaceda** [auth0/docs#6032]
Multi-line code blocks in Markdown accept a `language` property to define how the code will be highlighted. While on GH where most of our code is hosted a code block without a specified `language` is treated as plain text and is not highlighted, docs does the opposite and tries to auto-detect the language used in the code block. This leads to errors such as https://auth0.com/docs/errors/libraries/auth0-js/invalid-token:

![image](https://user-images.githubusercontent.com/3900123/38754129-0269827a-3f37-11e8-9178-72a8cad390c5.png)

While syntax highlighting is not part of the Markdown spec, it makes sense to have the same look and feel that users already have experienced on Github.

@arielger told me docs uses [hightlightjs](https://highlightjs.org/usage/) just as [Github does](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting). A possible solution would be to stop guessing the language if it's not specified and have the writer explicitly set it, again, just as someone would do in Github.

**Comment by mpaktiti** [comment]
Issue moved to `auth0/auth0-docs` repo
