### ISSUE TITLE
Usability improvements for docs landing page

### ISSUE THREAD

**Issue by LadyCarni** [auth0/docs#6067]
The very first page of the documentation is slightly lacking direction and simplicity for the user to get started quickly and easily. Here are a few tips to improve the focus of the flow.

![chrome_2018-04-19_20-37-45](https://user-images.githubusercontent.com/6787230/39025725-e7b959f2-4416-11e8-90b1-c2b50e03c752.png)

## Items to note:
- [ ] Create a single header guiding the user in how to use this screen (e.g. "Choose your application type") and remove the `<p class="navigator-title">`
- [ ] Create equal space between the top and bottom of the application type selection options with a `max-height: 400px;` on the `<div id="tutorial-navigator">`
- [ ] Increase the `font-size` on the `<strong class="title">` within the `<div class="quickstart">`  to `1.25em` and add a `margin-bottom: 1em;` for ease of readibility with the additional white space
- [ ] Remove the `<p class="description">` in each `<div class="quickstart">` as the titles are self-explanatory and the examples serve as adequate context. Increase the `opacity` of the `<p class="sample">` in the items to `0.75` so the contrast ratio isn't quite so hard to read

![chrome_2018-04-19_20-37-45 1](https://user-images.githubusercontent.com/6787230/39026981-c9369c7c-441d-11e8-916d-88fa98a728f6.png)

**Comment by made-by-max** [comment]
Hi Caryn, 

Thanks for your feedback. Improving the UX of this page and our documentation in general is one of our big priorities for this year and we will take your suggestions into account. 

- Stacy Taylor, UX Designer
