### ISSUE TITLE
Asp.Net Web API Quickstart Sample Issues

### ISSUE THREAD

**Issue by baskarmib** [auth0/docs#6105]
There is a typo error in the Startup.cs code. The keyword identifier is not recognized from the sample. I was following the steps mentioned in the below url.
https://auth0.com/docs/quickstart/backend/webapi-owin

app.UseJwtBearerAuthentication(
                new JwtBearerAuthenticationOptions
                {
                    AuthenticationMode = AuthenticationMode.Active,
                    TokenValidationParameters = new TokenValidationParameters()
                    {
                        ValidAudience = apiIdentifier,
                        ValidIssuer = domain,
                        IssuerSigningKeyResolver = (token, securityToken, identifier, parameters) => keyResolver.GetSigningKey(**identifier**)
                    }
                });

The identifier is not recognized.

**Comment by michizhou** [comment]
Hi @baskar3078 I noticed that the keyword identifier seems to be added now in place of identifier with 'kid'. Does that solve the issue? If not, I would be willing to take this issue!

**Comment by baskarmib** [comment]
Thanks @michizhou for reaching out. It should be fine if the samples are updated.
