### ISSUE TITLE
Quickstart: React - Handling Authentication setState error

### ISSUE THREAD

**Issue by Birkbjo** [auth0/docs#6141]
Hello!

I'm sorry if I'm doing something wrong, but I'm assuming something is wrong with the React quickstart documentation. More precisely in this part: https://auth0.com/docs/quickstart/spa/react#process-the-authentication-result .

For one, the parameters in handleAuthentication seems to be wrong, as "replace" is never given. Might be something that is not migrated from old react router-docs?

The biggest problem is that the setSession and handleAuthentication in the Auth-service are both calling history.replace(). Why is this done two times? The most troubling part is that this will cause a setState, which is not allowed in the render, and you get an error in the console. It seems like this should be handled in the componentWillMount in the Callback-component.

**Comment by cocojoe** [comment]
This has been completely replaced now.
