### ISSUE TITLE
/hosted-pages/login/auth0js references Auth0.js v8

### ISSUE THREAD

**Issue by joseeantonior** [auth0/docs#6184]
When accessing https://auth0.com/docs/hosted-pages/login/auth0js, it mentions:

```You can start out with a basic template that will provide you with a working, ready-to-use example of a custom UI using Auth0.js v8 in your universal login page.```

This page needs to be updated to reference v9, and update the code snipped listed, accordingly.

**Comment by strugee** [comment]
This issue should probably be closed since #6782 landed.
