### ISSUE TITLE
Swift version for "Lock iOS: Saving and Refreshing JWT Tokens"

### ISSUE THREAD

**Issue by lobo** [auth0/docs#620]
Link to tutorial: https://auth0.com/docs/libraries/lock-ios/save-and-refresh-jwt-tokens
Received feedback in one ticket: "It is not unhelpful, but a version in Swift2 would be super awesome."

**Comment by mpaktiti** [comment]
Thank you @lobo ! I moved this issue at our Docs trello board and someone will look into this shortly.

**Comment by ankits16** [comment]
@mpaktiti is it done?

**Comment by mpaktiti** [comment]
@ankits16 That's the latest doc, it's using Swift 3.0 https://auth0.com/docs/libraries/lock-ios/v2
