### ISSUE TITLE
Broken link on Silent Authentication page 

### ISSUE THREAD

**Issue by FastNinja** [auth0/docs#6208]
on this page:
https://auth0.com/docs/api-auth/tutorials/silent-authentication
 link at the bottom - `how to implement ASP.NET Core MVC` leads to 404 page on github:

[git hub broken link](https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples/tree/master/Samples/silent-auth)

**Comment by mpaktiti** [comment]
Thanks for reporting this @FastNinja ! The link was pointing to an outdated sample that was removed a couple months back from the repo. I pushed an update to remove the broken link from the doc.
