### ISSUE TITLE
The "new version" link in api v1 doc points to v1 instead of v2

### ISSUE THREAD

**Issue by glena** [auth0/docs#622]
![image](https://cloud.githubusercontent.com/assets/5647310/11569859/e9aaf8d8-99d2-11e5-93f2-171836864e3d.png)

**Comment by sandrinodimattia** [comment]
I'm not sure if we want to do this yet:
- Not all of our SDKs are using v2, so we should update those first
- Not all features we had in v1 are already in v2 (e.g.: the logs endpoint)

**Comment by glena** [comment]
but
- api v1 is not linked in docs
- we are already showing the warning wrongly linked

why we wouldn't fix it?
