### ISSUE TITLE
We should document which fields are not allowed to be stored in "app_metadata"

### ISSUE THREAD

**Issue by glena** [auth0/docs#627]
This is because app_metadat is merged with the root object in client user after the rules pipeline on each login.

The complete list of fields is (but maybe there are fields we shouldnt publish like `_id` and `__tenant`):

```
      "clientID": { "not": {} },
      "globalClientID": { "not": {} },
      "global_client_id": { "not": {} },
      "email_verified": { "not": {} },
      "user_id": { "not": {} },
      "identities": { "not": {} },
      "lastIP": { "not": {} },
      "lastLogin": { "not": {} },
      "metadata": { "not": {} },
      "created_at": { "not": {} },
      "loginsCount": { "not": {} },
      "_id": { "not": {} },
      "email": { "not": {} },
      "blocked": { "not": {} },
      "__tenant": { "not": {} },
```

> https://github.com/auth0/api2/blob/master/api/users/schemas/app_metadata.js#L9-L23

**Comment by mpaktiti** [comment]
Thanks @glena . I moved this issue at our Docs trello board and someone will look into this shortly.

**Comment by mpaktiti** [comment]
Solved https://github.com/auth0/docs/pull/3476
