### ISSUE TITLE
Passwordless with Magic Link for iOS 

### ISSUE THREAD

**Issue by hzalaz** [auth0/docs#632]
We need a doc on how to use Magic Link with iOS, for that we can use this blog post as the source material https://auth0.com/blog/2015/12/04/how-to-implement-slack-like-login-on-ios-with-auth0/.

I'd suggest to have 2 guides
- How to configure iOS 9 Universal Links
- How to authenticate with Magic Link

The latter will reference the former since it relies in Universal Links.

The reasoning with having two guides is that the Universal Links configuration guide will be used to authenticate with IdP that doesn't have a native integration and avoid relying in custom schemes which are insecure and deprecated
## How to configure iOS 9 Universal Links

The steps (and images/gifs) can be found in the step 3 of this [blogpost](https://auth0.com/blog/2015/12/04/how-to-implement-slack-like-login-on-ios-with-auth0). The blogpost was made before the dashboard included a way to configure it, so it's relying on Auth0 Management API for some part of the configuration, so we should probably add how to do it inside the Auth0 dashboard. To use Auth0 Dashboard, just go to any of your apps's settings -> Show Advanced Settings -> Mobile Settings
## How to authenticate with Magic Link

All info and neccesary steps are detailed in the [blogpost](https://auth0.com/blog/2015/12/04/how-to-implement-slack-like-login-on-ios-with-auth0) so it's just copy/paste and rewrite if needed. Android already has a [doc](https://auth0.com/docs/libraries/lock-android/passwordless-magic-link) for this if we want to keep the same structure (the content will be different since they are different platforms but the key points are the same)

**Comment by mpaktiti** [comment]
The request was registered in our Docs trello board, someone will look into this soon.
