### ISSUE TITLE
How to customise Lock UI in Android/iOS

### ISSUE THREAD

**Issue by hzalaz** [auth0/docs#633]
We need to improve a little (and update) this guide for iOS and add the same for Android

**Comment by volbap** [comment]
You are referencing [this Lock-iOS customization guide](https://github.com/auth0/docs/blob/master/articles/libraries/lock-ios/customization.md). Please, correct me if I'm wrong. @hzalaz

**Comment by volbap** [comment]
Corrected by @hzalaz, these are the docs: https://auth0.com/docs/libraries/lock-ios
