### ISSUE TITLE
Update iOS/Android advance usage docs

### ISSUE THREAD

**Issue by hzalaz** [auth0/docs#634]
- [x] For both platforms we need to check that they are not using deprecated API's from either the OS or Lock itself. 
- [ ] For iOS we need to have code samples for both Objective-C & Swift and deprecate this guide since it is no longer necessary

**Comment by volbap** [comment]
@hzalaz Could you give me a link to the advance usage guide that you mention? Thanks.

**Comment by mpaktiti** [comment]
Hello @pablolvillar , is this something you are working on?

^ @chenkie

**Comment by mpaktiti** [comment]
Hi @hzalaz Is this still valid? Can you tell me please to which docs this refers to?

**Comment by mpaktiti** [comment]
I'm closing this issue, please re-open if it's still valid.
