### ISSUE TITLE
OneLogin incomplete documentation (Auth0 as Service Provider)

### ISSUE THREAD

**Issue by deepjaisia** [auth0/docs#6348]
The documentation for Auth0 as service provider when configuring with OneLogin is verbose and great. I was following the documentation myself and saw that there is one piece that is missing in the documentatino and it causes the SAML connection to not work at all whilst producing "Destination doesn't have the same recipient URL Error".

To over come this issue I entered the same value as the "ACS (Consumer) URL" and it worked. Hope that would help other people out who are trying to configure the same thing.
![auth0docgitissue](https://user-images.githubusercontent.com/19859829/42109719-a0019070-7bac-11e8-8f1d-1b5be5714cd6.png)

**Comment by mpaktiti** [comment]
Thanks for reporting @deepjaisia ! We just pushed a fix!

**Comment by deepjaisia** [comment]
Thanks for updating the documentation. I took a look at it, the new image looks good. @rkhoriander @mpaktiti - Great work. I was assuming if there is any way also to update the text of the documentation to tell the reader to copy the "post-back URL" to the "Recipient". Thanks again 😸

**Comment by mpaktiti** [comment]
@rkhoriander Can you look into this?

**Comment by rkhoriander** [comment]
Hi, @deepjaisia!

We had added it into the first bullet above the screenshot. Is there somewhere else you would have expected to see it that you think we should also include it?

**Comment by deepjaisia** [comment]
![auth0-onelogindoc](https://user-images.githubusercontent.com/19859829/42234632-2999f944-7ec3-11e8-93d6-638857fe5212.jpg)
In the highlighted area if you could include "copy the post-back URL on the Recipient input" alongwith the other text that would be great. Thanks @rkhoriander.

**Comment by rkhoriander** [comment]
Hi again. We merged the PR, but it may take a bit to be reflected on the live site. The updated file is here: https://github.com/auth0/docs/blob/master/articles/protocols/saml/identity-providers/onelogin.md

This is what we added:

<img width="923" alt="screen shot 2018-07-03 at 12 37 41 pm" src="https://user-images.githubusercontent.com/36277044/42235616-f08eaa82-7ebd-11e8-891f-7e71063975ab.png">

I believe this reflects what you suggested? Thanks again, @deepjaisia!

**Comment by deepjaisia** [comment]
Hey, 
I couldn't access the app hosted that was hosted for some reason and was checking the live one for the changes. That looks amazing, it solves the issue. Thanks for cooperating and the help, appreciate it. 😸
