### ISSUE TITLE
Add/Improve doc on how to use /delegation in iOS/Android

### ISSUE THREAD

**Issue by hzalaz** [auth0/docs#635]
There are two uses for delegation, one to get a token from another service and the other to get a new id_token using either refresh_token or a valid id_token. So we should have a doc that covers both usages.
## Delegation to get a token from another service

We need to document how to call `/delegation` endpoint for retrieving a token from another service like AWS, Firebase, etc, for iOS we have [this guide](https://auth0.com/docs/libraries/lock-ios/delegation-api) but for Android we have none. 
The docs should explain the parameters needed to call the method (id_token, grant_type, etc) and show a code snippet (swift+objc in iOS & java in Android), potentially we could add also a sample of how to obtain a token from Firebase or AWS since it will require handling the different responses (the response payload will be different when calling delegation endpoint)

Android delegation:  https://github.com/auth0/Lock.Android/blob/master/core/src/main/java/com/auth0/api/authentication/AuthenticationAPIClient.java#L368

``` java
Auth0 auth0 = new Auth0("CLIENT_ID", "tenant.auth0.com");
AuthenticationAPIClient client = new AuthenticationAPIClient(auth0);
Map<String, Object> parameters = new ParameterBuilder()
        .set("api_type", "firebase")
        .set("id_token", "MY_ID_TOKEN")
        .asDictionary();
client.delegation().addParameters(parameters).start(new BaseCallback<Map<String, Object>>() {
    @Override
    public void onSuccess(Map<String, Object> payload) {

    }

    @Override
    public void onFailure(Throwable error) {

    }
});
```
## Delegation to get a new auth0 id_token

In iOS we explain how to obtain a new id_token using a refresh_token (https://auth0.com/docs/libraries/lock-ios/save-and-refresh-jwt-tokens) but there is no guide for android. 

with id_token https://github.com/auth0/Lock.Android/blob/master/core/src/main/java/com/auth0/api/authentication/AuthenticationAPIClient.java#L351
with refresh_token https://github.com/auth0/Lock.Android/blob/master/core/src/main/java/com/auth0/api/authentication/AuthenticationAPIClient.java#L368

**Comment by jpshelley** [comment]
Is this different then the refresh in the sample app?
https://github.com/auth0/Lock.Android/blob/master/app/src/main/java/com/auth0/app/MyActivity.java#L120

**Comment by mpaktiti** [comment]
The request was registered in our Docs trello board, someone will look into this soon.
