### ISSUE TITLE
Improve Lock for iOS & Android index pages

### ISSUE THREAD

**Issue by hzalaz** [auth0/docs#636]
Make the other child guides easier to find, in iOS they are in the middle of the page not very visible
Also we should probably re-write them since the "README" structure might not be the best for the docs site.

**Comment by volbap** [comment]
I interpret that what you want to enhance is the [Lock.iOS-OSX's **README.md** file](https://github.com/auth0/Lock.iOS-OSX/blob/master/README.md). Correct me if I'm wrong, @hzalaz .
