### ISSUE TITLE
Android documentation review: typo in all android sample docs

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#6400]
After Authos, in the next line, it should read "Auth0." with a period at the end of the word. In any of the sample docs of Android, Auth0 has the period.
![screenshot_1](https://user-images.githubusercontent.com/15818783/42787199-75f0faf4-8927-11e8-87f5-41019fc01e55.png)
![screenshot_2](https://user-images.githubusercontent.com/15818783/42787206-7ea65900-8927-11e8-99f5-50b54944f451.png)
![screenshot_3](https://user-images.githubusercontent.com/15818783/42787209-81f5c154-8927-11e8-9ae6-2018d7889489.png)
![screenshot_4](https://user-images.githubusercontent.com/15818783/42787211-845eb4b4-8927-11e8-9d9e-bd1df4871c69.png)
![screenshot_5](https://user-images.githubusercontent.com/15818783/42787213-85465ab2-8927-11e8-8631-298bd3185046.png)
![screenshot_6](https://user-images.githubusercontent.com/15818783/42787215-86525316-8927-11e8-8473-db3a87fa4d98.png)

**Comment by mpaktiti** [comment]
Hello @paulioceano. This is not something we do so I'm gonna go ahead and close this issue. Thanks.
