### ISSUE TITLE
Wrong redirection in native docs.

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#6410]
After click in the "Login & download sample" button, the page redirect to a login form, but after this it doesn't return to the doc page as supossed, it takes the user to the dashboard page.

**Comment by albertoperdomo** [comment]
Hi @paulioceano,

Thanks for the submitting this.

I talked today about this with @davidpatrick and this is a known issue.
The resolution is currently blocked internally. We hope to able to resolve this soon.

In any case, this will be addressed in the docs app, not here, so it would be the wrong repo for this issue. I'm going ahead and closing this issue.

Feel free to reach out to me for a more in-depth discussion.
