### ISSUE TITLE
Missing Instructions to install dependency on download page for React Native

### ISSUE THREAD

**Issue by rafanog** [auth0/docs#6420]
At the [React Native download page](https://github.com/auth0/docs/blob/master/articles/quickstart/native/react-native/download.md), he instructions to install the dependencies is missing on the download page for the React Native example, to execute the sample code, the user needs to make a **npm install** command to download all the necessary dependencies.

![image](https://user-images.githubusercontent.com/15782359/43135910-775d8550-8f1d-11e8-8b1e-65dec2d7f45e.png)

**Comment by valerianpereira** [comment]
I believe this is done already. Could you close the issue?

**Comment by albertoperdomo** [comment]
It turns out I fixed it myself in August but I failed to close this issue.
Thanks for the catch!
