### ISSUE TITLE
Outdated screenshots in "Server + API" doc

### ISSUE THREAD

**Issue by chugreevd** [auth0/docs#6474]
https://auth0.com/docs/architecture-scenarios/server-api/part-2

As far as I can see, the text is up-to-date, but the screenshots are from some older version of Auth0 dashboard.
Examples: on the screenshots there is a menu "Clients" instead of "Applications", "Client type" dropdown instead of "Application type", and so on.

**Comment by tamigoodall** [comment]
Added to Jira Docs Tasks Board: https://auth0team.atlassian.net/browse/DOCS-99
