### ISSUE TITLE
Webapp Python: There are more than 5 steps listed in doc.

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#6494]
In the Django QS (https://auth0.com/docs/quickstart/webapp/django) there are more than 5 steps listed. According to test guidelines, there shuld not be more than 5.

![screenshot_1](https://user-images.githubusercontent.com/15818783/43742884-8d5ffb38-99a1-11e8-8074-0c681cb4bb8b.png)

**Comment by albertoperdomo** [comment]
How about we change it to:

* Configure Auth0
* Configure Django to Use Auth0
* Trigger Authentication
* Display User Information
* Implement Logout

Or something along these lines... Thoughts @aaguiarz ?

**Comment by aakash2602** [comment]
Is it finalized? I can update it accordingly

**Comment by albertoperdomo** [comment]
Deferred.
