### ISSUE TITLE
React Native iOS: A "copy code" icon should be added to the callback on download sample

### ISSUE THREAD

**Issue by benlizar** [auth0/docs#6496]
**Actual result**
The user is not able to copy in an easy way the callbacks codes on the download examples.

**Expected results**
A copy icon should be added to the code snippet.

**Reference code**
https://github.com/auth0/docs/blob/master/articles/quickstart/native/react-native/download.md
![image](https://user-images.githubusercontent.com/36707032/43744666-058625cc-99a9-11e8-8b94-a45d87626899.png)

**Comment by michizhou** [comment]
Hi @benlizar, I would be willing to take on this issue. Should I just be changing the reference code doc file or some other file outside of the docs repo? Please let me know!

**Comment by albertoperdomo** [comment]
Not addressable in docs. If we wanted to do this improvement, it would need to be implemented in docs-dev, the app serving the docs and Quickstarts downloads. 

Closing.
