### ISSUE TITLE
React Native iOS app: Missing the CD to the app folder

### ISSUE THREAD

**Issue by benlizar** [auth0/docs#6497]
**Actual results**
The user does not knows were to run the "Npm i" command

**Expected results**
On the Copy we should add the location on where this commands will run.

![image](https://user-images.githubusercontent.com/36707032/43744697-37692670-99a9-11e8-87ea-561132e1e31e.png)

**Comment by aaguiarz** [comment]
We are never explaining this in the Quickstarts
