### ISSUE TITLE
React Native App: Missing react-native documentation link

### ISSUE THREAD

**Issue by benlizar** [auth0/docs#6498]
**Actual result**
The user is not able to find the react-native documentation with ease

**Expected results**
All external function should be linked to their documentations.

![image](https://user-images.githubusercontent.com/36707032/43744711-59313c7a-99a9-11e8-9f5c-585f06612e32.png)

**Comment by arshadkazmi42** [comment]
@benlizar I checked here https://auth0.com/docs/quickstart/native/react-native#configure-auto0
Documentation link looks fine. What exact change do we need here? Or is it already fixed?
