### ISSUE TITLE
Mobile app Xamarin iOS: Info.plist is not displayed correctly on the QS documentation

### ISSUE THREAD

**Issue by benlizar** [auth0/docs#6499]
**Actual results**
The user only sees the UI instead of the xml.

**Expected results**
The "View as source" header should be on the documentation

**Reference**
https://github.com/auth0/docs/blob/master/articles/quickstart/native/xamarin/download.md

![image](https://user-images.githubusercontent.com/36707032/43744922-4725cb12-99aa-11e8-92ec-e58c161068ea.png)
![image](https://user-images.githubusercontent.com/36707032/43744929-4bd05434-99aa-11e8-8ae4-381df34ad337.png)

**Comment by ptw007** [comment]
At book bottom of Safari page says use 43615 to log into my email usually just gives my email account numbers

**Comment by albertoperdomo** [comment]
Can you please elaborate @benlizar ? Is this still an issue?
