### ISSUE TITLE
Webapp Node.js - Repository not found.

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#6500]
When trying to download the sample for User profile in the QS (https://auth0.com/docs/quickstart/webapp/nodejs/02-user-profile) I got an error:

![screenshot_1](https://user-images.githubusercontent.com/15818783/43751463-f8f1621e-99ca-11e8-8577-6e5c687f68c6.png)

This is because the repo is not in github. After clicking in "View on Github" button, redirects to a not found page.

![screenshot_2](https://user-images.githubusercontent.com/15818783/43751574-799688ae-99cb-11e8-84d4-a81fb8aff434.png)

**Comment by albertoperdomo** [comment]
Thanks for reporting @paulioceano!

This one is on me. I was too fast in merging the sample, but then I got stuck improving the Quickstart.
I'm working on unblocking this ASAP.

**Comment by albertoperdomo** [comment]
https://github.com/auth0/docs/pull/6426 has been merged. When it's deployed this issue should be fixed.

**Comment by albertoperdomo** [comment]
Confirm this is fixed now in prod.
