### ISSUE TITLE
login with referral token

### ISSUE THREAD

**Issue by nitsx2** [auth0/docs#6501]
hy, i want to login with auth0 but also want to save referral token which is coming in url(myweb.com?referral=xxxx).
Is there anyway to achieve this??

**Comment by mpaktiti** [comment]
Hi @nitsx2 👋 Can you ask your question at our [Community](https://community.auth0.com/)? This is the place that our engineers monitor for customer questions and respond, I'm sure you'll get your answer there. If you find that there is some error or omission in any of our docs feel free to reopen this issue. Thank you!
