### ISSUE TITLE
Swift QS: Be more explicit about opening xcworkspace in XCode

### ISSUE THREAD

**Issue by benlizar** [auth0/docs#6511]
**Actual result**
The current instructions are not helping the user to run the demo.

**Expected results**
According to the solution on ticket:
https://github.com/auth0-samples/auth0-ios-objc-sample/issues/43
the Step 2. should be modified to `Open the xcworkspace in Xcode.` for those who are not familiar with cocoapods.

![image](https://user-images.githubusercontent.com/36707032/43851775-a1f326b0-9b09-11e8-9bff-1b7edae7a67b.png)

**Comment by albertoperdomo** [comment]
Thanks for reporting @benlizar.

This has been addressed in https://github.com/auth0/docs/pull/6505, which has already been merged and should be deployed very soon (even today?).
Closing.
