### ISSUE TITLE
ASP.NET (OWIN) Reguler Web App: No mention of RS256 JWT Signature Algorithm

### ISSUE THREAD

**Issue by mikearias3** [auth0/docs#6515]
**Environment Information**
- Visual Studio 2017 v15.7.6
- Google Chrome v68

**Issue**
In the [ASP.NET (OWIN) Quickstart](https://auth0.com/docs/quickstart/webapp/aspnet-owin), if the user has an old account, the JWT Signature Algorithm will be set to HS256 by default. It would be useful to have a mention of the RS2566 JWT needed to run this sample.

**Screenshot**
![jsonwebtokensignature](https://user-images.githubusercontent.com/5594487/43904765-835d4302-9bbd-11e8-9e38-3feed2507a67.PNG)

**Comment by aaguiarz** [comment]
We should test all the QS with OIDC Conformant = True and JsonWebToken Signature Algorithm
