### ISSUE TITLE
Play 2 Scala: On snippet code the "Sign in" label is misspelled

### ISSUE THREAD

**Issue by benlizar** [auth0/docs#6528]
**Actual result**
On link tag The "Sign in" label is displayed as "signin" on the demo.

**Expected results**
The text should say "Sign in" instead of "Signin".

Configuration
-OS: MacOS 10.13.6
-Browser: Chrome 68.0
-Scala version: 2.12
-Sbt version: 1.1.16

![image](https://user-images.githubusercontent.com/36707032/44042976-b44a9214-9eef-11e8-9d4f-dc4368626114.png)

**Comment by albertoperdomo** [comment]
Fixed in #6553
