### ISSUE TITLE
qs Play 2 Scala: On Download popup, the callback is not the same as the demo app

### ISSUE THREAD

**Issue by benlizar** [auth0/docs#6529]
**Actual result**
On Download popup, the callback is pointing to http://localhost:3000/auth/oauth2/callback

**Expected results**
The callback should be pointing to http://localhost:9000/callback, according to the Source code and QS documentation.

(Wrong callback)
![image](https://user-images.githubusercontent.com/36707032/44050351-b3bb5a80-9f04-11e8-8ae4-09e459fc5f3d.png)

(Good callback)
![image](https://user-images.githubusercontent.com/36707032/44050402-d30f937e-9f04-11e8-8b55-6d2a84c5007d.png)

**Comment by paulioceano** [comment]
@albertoperdomo I re-test this sample.

Both in the Download popup as in the code snippets the callback URL is set to `ttp://localhost:9000/callback`, but, in the downloaded sample, both from the QS page (https://auth0.com/docs/quickstart/webapp/scala) and in the QS from the dashboard, the callbackURL populated in the sample is `http://localhost:3000/callback`

![screenshot_1](https://user-images.githubusercontent.com/15818783/45001817-95ef9480-af9e-11e8-9e66-5e1407d4a0e8.png)

In the Application.scala file in the downloaded sample. the Redirect URL is set to `http://localhost:3000`
![screenshot_3](https://user-images.githubusercontent.com/15818783/45001818-96882b00-af9e-11e8-88e5-732b7bc006ab.png)

But, the code snippet for this file shows a wrong URL (http://localhost:9000)

![unknown](https://user-images.githubusercontent.com/15818783/45001999-69d51300-afa0-11e8-9ef2-34c7cba04d1b.png)
