### ISSUE TITLE
Webapp ASP.Net Core 2 Issues with the execution instruction

### ISSUE THREAD

**Issue by rafanog** [auth0/docs#6533]
In the 2nd step of the download page, these are the instructions that explain the user what to do to execute the project:

![image](https://user-images.githubusercontent.com/15782359/44063095-7a44204e-9f35-11e8-9f7d-8784e72b5d0a.png)

First of all, the `dotnet restore` instruction isn't required since the Core V2.0 documentation explains it here:

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x

As the documentation says it's implicitly executed as part of other instructions.

And the `dotnet run` needs to add the `--project` tag along with the address of the project, in this case, the address should route to the SampleMvcApp folder contained in the downloaded code, if executed without these parameters the dotnet tool wouldn't find the project.

**Comment by aaguiarz** [comment]
@jerriep can you please confirm this?

**Comment by jerriep** [comment]
> the dotnet restore instruction isn't required

This is correct. I does no harm having it there, but the `run` command will do a restore if it was not done explicitly

> the dotnet run needs to add the --project tag 

Correct as well. We will either need to add that or move the code out of the `SampleMvcApp` folder into the root folder of each Quickstart step

**Comment by albertoperdomo** [comment]
Thanks! I'm no .net expert by any means, so I'd love to know your opinion on how address these issues @jerriep. 

>This is correct. I does no harm having it there, but the run command will do a restore if it was not done explicitly

Which route should we go? Should we keep it or remove it?

>Correct as well. We will either need to add that or move the code out of the SampleMvcApp folder into the root folder of each Quickstart step

What is the preferred solution, in your opinion?

**Comment by jerriep** [comment]
@albertoperdomo 

> Which route should we go? Should we keep it or remove it?

I will remove it

> What is the preferred solution, in your opinion?

I think it is best to move the code out of the sub-folder. I will need to look into this carefully though to ensure it does not break the docker stuff

**Comment by jerriep** [comment]
@rafanog @albertoperdomo I have moved the Quickstarts samples out of the `SampleMvcApp` folder into the root folder for each step. I have tested for Docker and it works.

Can you please ensure that CircleCI also still works?

I have updated the CircleCI config file where appropriate, but I have no way to test that to ensure everything is still OK

**Comment by albertoperdomo** [comment]
We will review this in case there is anything broken.
Thanks @jerriep!
