### ISSUE TITLE
qs Regular WebApp ServiceStack: The Port inside the tip box is missing

### ISSUE THREAD

**Issue by benlizar** [auth0/docs#6534]
Actual result
The port is not specified on the tip box.

Expected result
The tip box should specify the MVC port to be used, Having in mind that the MVC ports are dynamics when creating a new project. Maybe a good approach to suggest is adding a step changing that port inside the project's property to the desired one.

![image](https://user-images.githubusercontent.com/36707032/44093080-76140f46-9fa0-11e8-8649-8bd70dc5bea6.png)

**Comment by albertoperdomo** [comment]
Hello @jerriep,

can you please share your thoughts on this?

**Comment by aaguiarz** [comment]
@jerriep can we make the port fixed?

**Comment by aaguiarz** [comment]
@alexisluque can you check if we can make the port fixed in the ServiceStack sample?

**Comment by jerriep** [comment]
The port is configured as `6132`:
https://github.com/auth0-community/auth0-servicestack-samples/blob/c1f1aa5d8f9a88d52b778e52ec35bf149526ac70/00-Starter-Seed/ServiceStack-Auth0-Sample/ServiceStack-Auth0-Sample.csproj#L327

**Comment by jerriep** [comment]
Submitted PR: https://github.com/auth0/docs/pull/6582
