### ISSUE TITLE
SPA Jquery: On download popup, the callback is not the one in the demo

### ISSUE THREAD

**Issue by benlizar** [auth0/docs#6537]
Actual result
The callback displayed on the download popup is not the same that the sample is expecting.

Expected result
The callback should be "http://localhost:3000"

![image](https://user-images.githubusercontent.com/36707032/44103886-5fa9c118-9fbb-11e8-86f0-49f2b74e43bf.png)

**Comment by albertoperdomo** [comment]
Hello @benlizar.

If we change the suggested callback URL to `http://localhost:3000`, can you confirm that the sample works without issues?

**Comment by albertoperdomo** [comment]
It seems odd that the callback URL is `/`. What do you think @aaguiarz?

Is this how the sample is implemented, we could with address this by fixing the callback URL in the download instructions and mid-term changing the callback URL in the implementation to be `/callback` or any other route other than `/`.

just my 2 cents.

**Comment by aaguiarz** [comment]
It should be '/', as in plain JS you can't easily handle routes like '/callback' on the client side.

So, we should update the download.md and set it to http://localhost:3000/

**Comment by benlizar** [comment]
@albertoperdomo  Yes, the sample is working without issue.
