### ISSUE TITLE
SPA JavaScript: Mismatch in callback URL displayed.

### ISSUE THREAD

**Issue by paulioceano** [auth0/docs#6543]
In the Download Sample popup, the Allowed callback URL asked to be set is ´http://localhost:3000/callback´

![screenshot_2](https://user-images.githubusercontent.com/15818783/44155234-c32a7178-a07a-11e8-88a5-ea72c57a513f.png)

But in the Sample README file, the Allowed callback URL is http://localhost:3000, the URL that is asked to add in the sample.

![screenshot_1](https://user-images.githubusercontent.com/15818783/44155957-b29642b8-a07c-11e8-8c05-6a738fe9c0cc.png)

![screenshot_3](https://user-images.githubusercontent.com/15818783/44155958-b2e70810-a07c-11e8-9b49-7bb8f4fc59e6.png)

**Comment by albertoperdomo** [comment]
See https://github.com/auth0/docs/issues/6537#issuecomment-413574961
