### ISSUE TITLE
multifactor-authentication doc IP rangeCheck example

### ISSUE THREAD

**Issue by keithlamar** [auth0/docs#657]
Doc: https://auth0.com/docs/multifactor-authentication#access-a-critical-app-from-extranet

rangeCheck is not defined
`return !rangeCheck.inRange(context.request.ip, '10.0.0.0/8');`

I believe it should be:
`return !ip.in_range(context.request.ip, '10.0.0.0/8');`

**Comment by mpaktiti** [comment]
This section seems to be removed, closing the issue.
