### ISSUE TITLE
Request to Webtask got ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by JayathmaChathurangani** [auth0/docs#6571]
What I am trying to do is authenticate users using my own database. There I am following the guidelines mentioned in Articles at Auth0 web site [here](https://auth0.com/docs/connections/database/custom-db/create-db-connection). I followed all the steps mentioned there for msql connection (including configuring my firewall to allow access to the specified addresses). Actually first I created the 'Login' database action script. But when I am going to 'try' it, the following error appears. 

_Request to Webtask got ESOCKETTIMEDOUT_

How to get rid of this?

**Comment by rkhoriander** [comment]
Hi, @JayathmaChathurangani! Often this is related to problems with rules or hooks. Can you please ask your question at [our Community](https://community.auth0.com/)? Our engineers monitor the community and respond to customer questions, so I'm sure you'll get your answer there. If you find that there is some error or omission in any of our docs feel free to reopen this issue. Thank you!

**Comment by rkhoriander** [comment]
Actually, I've just seen that you did already [post in our Community](https://community.auth0.com/t/request-to-webtask-got-esockettimedout/14687). I hope they were able to help. Thanks!
