### ISSUE TITLE
Step-up authentication graphic typo

### ISSUE THREAD

**Issue by joseeantonior** [auth0/docs#6602]
In the [step-up authentication document](https://auth0.com/docs/multifactor-authentication/step-up-authentication) there is a graphic explaining the process.

Step 4 of the graphic mentions: `Set up authentication required`

Instead, it should read: `Step-up authentication required`

This typo can be confusing and could lead users to set up authentication again.

**Comment by rkhoriander** [comment]
PR: https://github.com/auth0/docs/pull/6674

**Comment by valerianpereira** [comment]
PR is merged already. Please close this issue

**Comment by rkhoriander** [comment]
PR merged.
