### ISSUE TITLE
Explain how exactly to obtain the JWT

### ISSUE THREAD

**Issue by dandv** [auth0/docs#6646]
I've read [two](https://auth0.com/docs/jwt) Auth0 [tutorials](https://auth0.com/docs/tokens/id-token) about JWT so far, and still can't tell how to easily obtain the JWT.

**Comment by parthpandyappp** [comment]
I would like to contribute to this.!

**Comment by tamigoodall** [comment]
We've added this task to our backlog and will implement the changes in an upcoming sprint. Thanks for your feedback.
