### ISSUE TITLE
Bad reference in Android PHP API Seed Project Readme file

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#67]
Readme file for PHP API Seed project indicates a different port in the start command and the test at the end:

![2015-06-02_2108](https://cloud.githubusercontent.com/assets/12707130/7950899/ed9045ba-096e-11e5-9b38-475fdecfdd0a.png)

``` bash
composer install
php -S localhost:30001
```

Now, try calling [http://localhost:3001/ping](http://localhost:3001/ping)

**Comment by glena** [comment]
done
