### ISSUE TITLE
Lacking documentation regarding Self-Signed Certificate flow

### ISSUE THREAD

**Issue by knutole** [auth0/docs#6724]
The documentation for Self-managed certificates are either outdated or wrong, as far as I can tell. 

Github file: https://github.com/auth0/docs/blob/master/articles/custom-domains/self-managed-certificates.md
Documentation URL: https://auth0.com/docs/custom-domains/self-managed-certificates
The settings page in question: https://manage.auth0.com/#/tenant/custom_domains

1. The documentation is asking for TXT records, while the actual settings page are using CNAME records. 
2. There is no `cname-api-key` visible on the settings page, although it's described in the documentation. 

As a result, the Self-signed certificate flow described in the documentation is inaccessible.

**Comment by knutole** [comment]
On closer inspection, it turns out this is due to Self-Signed Certificates only being available to Enterprise users. This should probably be mentioned somewhere more conspicuous, as it took me a good half hour of reading before I found it. 👍

### Todo
- [ ] add more clear message that Self-Signed Certs is for Enterprise clients only

**Comment by michizhou** [comment]
I would be willing to take this issue!

**Comment by tamigoodall** [comment]
Closed.
