### ISSUE TITLE
Grant type keys do not match "gty" claim name

### ISSUE THREAD

**Issue by ryno1234** [auth0/docs#6729]
The grant type keys listed in the documentation do not match the grant type keys received in the claims of a given token. For example, the grant type Client Credentials is specified as having a key of `client_credentials` while the value I found in my `gty` claim was `client-credentials`. This caused a bug in my software so I'm mentioning it here to the potential for someone else to have an issue like that.

I'm referring to the content on this page: https://github.com/auth0/docs/blob/master/articles/applications/application-grant-types.md

**Comment by tamigoodall** [comment]
We have created a task to address this and added it to our backlog. It will be added to an upcoming sprint. Thanks for your feedback!
