### ISSUE TITLE
Delegated Admin. extension installation updates

### ISSUE THREAD

**Issue by d60402** [auth0/docs#6819]
A few things out of sync with [the doc](https://auth0.com/docs/extensions/delegated-admin/v3) and the actual implementation...

- The "Install the Extension" [screenshot](https://cdn2.auth0.com/docs/media/articles/extensions/delegated-admin/install-extension.png), along with the configuration variables for it listed in the copy need to be updated.
  - FAVICON_PATH var needs to be added to copy
  - FEDERATED_LOGOUT var needs to be added to copy
  - SEARCH_ENGINE var needs to be removed from copy

**Comment by vyaspranjal33** [comment]
@d60402  i would like to add things you mentioned please provide me details about following variables 

FAVICON_PATH 

FEDERATED_LOGOUT

**Comment by vyaspranjal33** [comment]
@d60402  would you like to share new screenshot , it would be really helpful for PR
