### ISSUE TITLE
404 links on Access tokens for the Management API documentation page

### ISSUE THREAD

**Issue by Jazzepi** [auth0/docs#6865]
https://auth0.com/docs/api/management/v2/tokens

The following links are all 404

Create and Authorize a Machine-to-Machine Application.
Get Access Tokens for Testing
Get Access Tokens for Production

Can you guys add some kind of static link scanner to your documentation build process? Or to the deployment process? I'm constantly finding links that are broken thorough the Auth0 docs.

**Comment by Jazzepi** [comment]
By the way I found the link to that page in the Java API SDK docs.

https://github.com/auth0/auth0-java#management-api

`The implementation is based on the Management API Docs.` <= https://auth0.com/docs/api/management/v2

**Comment by jeffreylees** [comment]
Those links are fixed, thanks!
