### ISSUE TITLE
Java Spring MVC and Security: Instrucions for Mac/Linux and Windows are swapped

### ISSUE THREAD

**Issue by mikearias3** [auth0/docs#6905]
In the following quickstarts:
- https://auth0.com/docs/quickstart/webapp/java-spring-mvc/01-login
- https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc

The second set of instructions are swapped.
![image](https://user-images.githubusercontent.com/5594487/47884208-44c91900-de06-11e8-8abb-a8295f3ac5f8.png)

Mac/Linux should have `gradlew clean bootRun` and Windows should have `./gradlew clean bootRun`

**Comment by mikearias3** [comment]
Fixed on this PR: https://github.com/auth0/docs/pull/6911

**Comment by cocojoe** [comment]
@jimmyjames please can you check this and fix if required.

**Comment by jimmyjames** [comment]
As discussed in #6911, Mac/Linux should be `./graldew` and Windows `gradlew`.
