### ISSUE TITLE
Java Spring MVC: Missing instruction for logout

### ISSUE THREAD

**Issue by mikearias3** [auth0/docs#6906]
In the following quickstart:
- https://auth0.com/docs/quickstart/webapp/java-spring-mvc/

There are no instructions explaining the user where to add the "Allowed Logout URLs". Because of this, when the user runs the app and clicks the logout button it will get a 400 error.
![image](https://user-images.githubusercontent.com/5594487/47884598-bf466880-de07-11e8-9047-a62581f4f408.png)

A possible fix for this would be to add a step to the Download Sample modal after setting up the Callback URL that told the user to add http://localhost:3000 to their Allowed Logout URLs".
![image](https://user-images.githubusercontent.com/5594487/47884640-ed2bad00-de07-11e8-84b9-d5b1a8945e42.png)

**Comment by cocojoe** [comment]
QS had logout added so this should be resolved.
