### ISSUE TITLE
https://auth0.com/docs/api/v2/changes#user-endpoints table is impossible to read

### ISSUE THREAD

**Issue by rolodato** [auth0/docs#694]
![image](https://cloud.githubusercontent.com/assets/829698/12148581/0126260c-b47e-11e5-841c-82cf0c6f730b.png)

**Comment by mpaktiti** [comment]
Table has been updated.

![image](https://cloud.githubusercontent.com/assets/11715799/17549009/19494f1a-5ef7-11e6-8fa0-64e037bc43c4.png)
