### ISSUE TITLE
i18n guide for Mobile

### ISSUE THREAD

**Issue by hzalaz** [auth0/docs#696]
iOS:
He needs to add a file named Auth0.strings, which is the format for i18n in iOS, included in the bundle of the app when is built.

The easier way to do it is using Xcode, just go to File -> New File, then iOS -> Strings File. The name will be Auth0 and make sure it's added to your application target by checking the box
![2](https://cloud.githubusercontent.com/assets/282782/12156193/5f3cada6-b47e-11e5-9946-a0088a3cfdde.png)

![1](https://cloud.githubusercontent.com/assets/282782/12156191/5a6852da-b47e-11e5-8ec4-604f317f828c.png)

Then the file contents should be something like this:

"Email" = "Email";
"Password" = "Passwort";
"ACCESS" = "ZUGRIFF";
where the key is the text you see in screen and the value is the translation.

To have multiple languages you'll need to add them in your project settings:

![2](https://cloud.githubusercontent.com/assets/282782/12156196/6716d240-b47e-11e5-966f-88baa2c194b4.png)

and then you will see different files per language you can customize:

![3](https://cloud.githubusercontent.com/assets/282782/12156203/6b432526-b47e-11e5-92be-8499a157aa16.png)

Android:

He need to follow this guide on how to localise resource files http://developer.android.com/guide/topics/resources/localization.html, so he can create a resource per language in his android project. The key and values that can be localised can be found here https://github.com/auth0/Lock.Android/blob/master/lock/src/main/res/values/strings.xml

These guides should be available for iOS & Android, and for react-native when we add a better support there (they can use the guide for iOS or Android since it's a wrapper)

**Comment by hzalaz** [comment]
iOS will have a major refactor to allow more flexibility and simpler to use since now it assumes that the i18n file has a fixed name, located in the main bundle of the app and the keys are the english value instead of a coded key like `login.submit`. My advice will be to hold of iOS till then, Android implementation with localised resources will remain the same http://developer.android.com/guide/topics/resources/localization.html

**Comment by volbap** [comment]
Is this refactor done? Do you have more information on this @hzalaz ?

**Comment by wenxin3262** [comment]
Just figured the file name should be `Lock.strings` for the newest version of Auth0 pod

**Comment by mpaktiti** [comment]
The request was moved to our Docs trello board, someone will look into this soon.
