### ISSUE TITLE
Vanilla JS + NET API - Missing detailed and accurate information for binding API to front end

### ISSUE THREAD

**Issue by javlc** [auth0/docs#70]
Links to tutorial: https://auth0.com/docs/quickstart/spa/javascript/aspnetweb-api 

The information to bind the api from the front end is not present in the tutorial.
Tutorial will be greatly enhanced with some basic information about accurately binding vanilla js front end with NET API seed project, instead of having the developer investigate too many web references on the subject.
No suggestions developed yet.

**Comment by iannyanes** [comment]
Closing this issue. This issue is no longer valid since step 5 of the current VanillaJS tutorial https://auth0.com/docs/quickstart/spa/vanillajs/no-api is about how to use the token granted by Auth0 to query your own protected API.
