### ISSUE TITLE
Auth api does not provide info about oauth/token endpoint

### ISSUE THREAD

**Issue by glena** [auth0/docs#705]
It is only documented in api/v1 (and not completely documented) while it is an auth endpoint (https://auth0.com/docs/api/v1#!#post--oauth-token).

For example, there is no doc about code exchange in auth doc

**Comment by glena** [comment]
@ntotten there is no info about this endpoint under `auth api` (grant type client_credentials nor authorization_code)

**Comment by eugeniop** [comment]
+1 it is only documented here: https://auth0.com/docs/protocols#3-getting-the-access-token

**Comment by glena** [comment]
and under apiv1 (which is not correct)

**Comment by mpaktiti** [comment]
`/oauth/token` is now documented in [Authentication API](https://auth0.com/docs/api/authentication#get-token)
