### ISSUE TITLE
Broken link in Legacy Rules doc

### ISSUE THREAD

**Issue by MatthewBacalakis** [auth0/docs#7061]
A  [legacy rules](https://auth0.com/docs/rules/references/legacy) document has a broken link.  The Context Argument Properties in Rules link points at https://auth0.com/docs/rules/context which does not exist.  [Context object in rules](https://auth0.com/docs/rules/references/context-object) seems like the right one but as that is not a legacy document I thought it was worth confirming before submitting a PR.

**Comment by rkhoriander** [comment]
Fixed with this PR:
https://github.com/auth0/docs/pull/7077

Already merged and live in production.

Thanks for reporting!
