### ISSUE TITLE
lockSDK update

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#707]
lockSDK contains references to outdated libraries.
Up to date version of passwordless library is 2.2.3 when tutorial suggest me to use 1.0:

![image](https://cloud.githubusercontent.com/assets/1114365/12179710/0d0b597a-b581-11e5-96e7-651b19467565.png)

Same with the auth0.js. Version in tutorial is 6.7 when up to date is 7.0.3

![image](https://cloud.githubusercontent.com/assets/1114365/12179671/df35afdc-b580-11e5-9db1-20bf438474cf.png)

**Comment by mpaktiti** [comment]
Hello @Amialc Can you please let me know which doc you are referring to?

**Comment by vmartynets** [comment]
Hi @mpaktiti, this issue related to tutorials that use `${lockSDK}` variable. (For example, [Scala tutorial](https://auth0.com/docs/quickstart/webapp/scala#3-trigger-login-manually-or-integrate-auth0lock))

**Comment by mpaktiti** [comment]
Hi @Amialc I cannot find such references in the [Scala quickstart](https://auth0.com/docs/quickstart/webapp/scala)

Can you list for me the tutorials that have this problem? See this issue was reported some time ago and the quickstarts have gone through many updates since then.

Thanks for your help in this.

**Comment by vmartynets** [comment]
Hello, @mpaktiti, click [here](https://auth0.com/docs/quickstart/webapp/scala#3-trigger-login-manually-or-integrate-auth0lock) and choose `Passwordless - SMS`, scroll a little bit and you see this:
![image](https://cloud.githubusercontent.com/assets/1114365/18232844/17241244-72e1-11e6-826d-b5c5f69e54fc.png)
Version of passwordless library is outdated. Outdated version to auth0.js if you choose `custom-ui`:
![image](https://cloud.githubusercontent.com/assets/1114365/18232861/4d585690-72e1-11e6-92e5-5887e66f5b17.png)

**Comment by mpaktiti** [comment]
Thank you for the input @Amialc, the issue is clear now and we will look into this shortly. 👍

**Comment by mpaktiti** [comment]
Hi @Amialc The issue has been fixed so I'm going to close this issue. You can verify using this page https://auth0.com/docs/quickstart/webapp/aspnet#4-triggering-login-manually-or-integrating-the-auth0lock Thanks!
