### ISSUE TITLE
ASP Core v2.0: Not all needed Callback URLs are listed in the tutorial

### ISSUE THREAD

**Issue by mikearias3** [auth0/docs#7078]
In the ASP.NET Core v2.0 quickstart, not all the callback URLs needed are listed. 

![image](https://user-images.githubusercontent.com/5594487/50375973-5e076e00-05dc-11e9-935d-86f9342695ec.png)

Only `http://localhost:5001/signin-auth0` is listed, but for the login screen to show up the user also needs to add `http://localhost:3000/signin-auth0` or the following error will show up.

![image](https://user-images.githubusercontent.com/5594487/50375980-94dd8400-05dc-11e9-9c17-8c0cdcdc521e.png)

**Comment by cocojoe** [comment]
This has been updated @mikearias3. Thanks
