### ISSUE TITLE
Broken link on: https://auth0.com/docs/api/management/v2/get-access-tokens-for-production

### ISSUE THREAD

**Issue by mathiasconradt** [auth0/docs#7090]
Broken link on https://auth0.com/docs/api/management/v2/get-access-tokens-for-production at the end of the page under "Keep reading":

> Management API Access Tokens FAQs

 -> https://auth0.com/docs/v2/faq-management-api-access-tokens leads to a 404

**Comment by rkhoriander** [comment]
Thanks for letting us know! 

Fixing this in PR:
https://github.com/auth0/docs/pull/7106

**Comment by rkhoriander** [comment]
Fixed and merged. Awaiting deployment to production. Thanks again!
