### ISSUE TITLE
Broken link in Getting Started / Welcome to Auth0: "Download this .json file of sample users."

### ISSUE THREAD

**Issue by mathiasconradt** [auth0/docs#7091]
Broken link in the Getting Started steps:

"Download this .json file of sample users." -> https://auth0-marketing.run.webtask.io/onboarding-migrate-users-example leads to a 404

![image](https://user-images.githubusercontent.com/295122/50540903-f2ed0700-0b9a-11e9-8e8a-19989e825d0f.png)

**Comment by albertoperdomo** [comment]
Hello @mathiasconradt,

thanks for taking the time to report this.
The team responsible for this is already aware and it will be fixed as soon as possible.

Alberto.
