### ISSUE TITLE
Don't suggest storing tokens in LocalStorage in "SPA + API: API and SPA Configuration" scenario

### ISSUE THREAD

**Issue by coduinix** [auth0/docs#7121]
The [SPA + API: API and SPA Configuration - part 3](https://github.com/auth0/docs/blob/master/articles/architecture-scenarios/spa-api/part-3.md)  suggests to store access tokens in local storage. This is in contradiction with the advice on the [Where to store tokens page](https://github.com/auth0/docs/blob/master/articles/security/store-tokens.md).

It would be best to just drop the example which stores the accessToken in local storage.

**Comment by RachelScodes** [comment]
Was coming here to leave the same feedback.

**Comment by skyrpex** [comment]
I think that the [CSP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) allow safely using the local storage to store sensitive information. If there's no way to send sensitive information outside the website, ~there's no possible XSS attack~ it's very hard to perform XSS attacks.

**Comment by RachelScodes** [comment]
The issue is the docs specifically point to using localStorage as bad practice. Either it's not bad practice - and shouldn't be referenced as such - or it is bad practice and shouldn't be used in example tutorials.

**Comment by coduinix** [comment]
Maybe nice to add is that the [OWASP HTML5 Security Cheat Sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/HTML5_Security_Cheat_Sheet.md#local-storage) also has some information on _Local Storage_:
> ... it's recommended not to store any sensitive information in local storage.

I bet that an access token qualifies for _sensitive information.
One of the suggestions is to use `sessionStorage` instead. That would prevent the issue of having the token lying around on disk somewhere, but it might still be a weak spot when an XSS attack is performed in some way.

**Comment by tamigoodall** [comment]
I will modify the https://github.com/auth0/docs/blob/master/articles/architecture-scenarios/spa-api/part-3.md doc to remove the example and link to the Where to store tokens page.

**Comment by tamigoodall** [comment]
Docs updated in this PR: https://github.com/auth0/docs/pull/7714
