### ISSUE TITLE
No syntax colorization for jsx blocks

### ISSUE THREAD

**Issue by TravisTheTechie** [auth0/docs#715]
On https://auth0.com/docs/client-platforms/react, the `react.use` snippit is not colored. 

(see https://github.com/auth0/docs/blob/master/snippets/client-platforms/react/use.md, jsx labeled code block)

**Comment by iannyanes** [comment]
Not reproducible - Closing

**Comment by TravisTheTechie** [comment]
This is still a problem even though I think the docs have been restructured. See https://auth0.com/docs/quickstart/spa/react/01-login

<img width="618" alt="screen shot 2016-08-23 at 4 07 01 pm" src="https://cloud.githubusercontent.com/assets/186225/17912931/b8b5c75a-694b-11e6-98d6-c1576dd07348.png">

vs

<img width="683" alt="screen shot 2016-08-23 at 4 07 12 pm" src="https://cloud.githubusercontent.com/assets/186225/17912934/bd50137e-694b-11e6-9d37-8b3de3c3c126.png">

They both should have the same colorization.
