### ISSUE TITLE
Forgot password page customize UI

### ISSUE THREAD

**Issue by coreylarkin12** [auth0/docs#7160]
Under the hosted pages tab in the auth0 dashboard you can customize the login page to look and say what you want you can even change the text for the forgot password link. You can also customize the reset password page but there is no option or documentation on how to customize the forgot password page. The page that pops-up when your on the login screen and click on the forgot password link and it asks you to enter your email and then you click the button below that says send email. 

Our clients are asking us to change the design on that but there is no option  on the hosted pages to do so. They want the title changed and the text in the button changed and where it redirects you after clicking send email changes they don't want it going back to the login screen for whatever reason 

![forgotpassword](https://user-images.githubusercontent.com/29547645/51406118-28e03400-1b26-11e9-9fd7-e50bd1f43515.PNG)

**Comment by tamigoodall** [comment]
Resolved

**Comment by sunnyvempati** [comment]
@tamigoodall how was this resolved? what if i wanted to customize the form and inputs?  I know there's not a supported API call, but injecting code into a div gives me 0 control.
