### ISSUE TITLE
The screenshot is older than the Dashboard API

### ISSUE THREAD

**Issue by adriatic** [auth0/docs#7164]
The word **`Clients`** on the screenshot below should be **`Applications`**

![image](https://user-images.githubusercontent.com/2712405/51443171-c36d7e00-1cb2-11e9-8777-a9f9574e499b.png)

This is what this same screenshoot actually looks now:

![image](https://user-images.githubusercontent.com/2712405/51443210-6c1bdd80-1cb3-11e9-9570-76b470383b10.png)

**Comment by tamigoodall** [comment]
Fixed: https://github.com/auth0/docs/pull/7948
