### ISSUE TITLE
WordPress Application Signing Algorithm setting does not exist

### ISSUE THREAD

**Issue by adriatic** [auth0/docs#7165]
The section https://auth0.com/docs/cms/wordpress/configuration#update-auth0-settings-in-wordpress references non-existing WordPress setting (marked with the arrow in the screenshot below)

![image](https://user-images.githubusercontent.com/2712405/51448532-33045d00-1cf5-11e9-83ee-518138e5fe83.png)

**Comment by tamigoodall** [comment]
Fixed: https://github.com/auth0/docs/pull/7948
