### ISSUE TITLE
custom database user profile handling issue

### ISSUE THREAD

**Issue by chriskeyser** [auth0/docs#722]
The docs have a circular reference around custom database scripts. In the customdb script for login it says

```
1. The user's credentials are valid. The returned user profile should be in
  // the following format: https://auth0.com/docs/user-profile
```

and in the user-profile doc at https://auth0.com/docs/user-profile#creating-users-in-a-custom-database it says
`The User Profile in the custom DB can be implemented with any User Profile structure desired, but must be mapped in the Login call to the Auth0 normalized User Profile attributes as shown in the "Login" custom DB template. The Login script can also write to the app_metadata portion of the User Profile.`

Seems like not all of the elements of profile should be meddled with and an example would be pretty helpful in one spot or the other.

**Comment by mpaktiti** [comment]
Hi @chriskeyser. I can't find neither of the two references, probably because a lot of updates have been done since the time you reported it. I'm going to close this issue but if you think that we still need to update the docs please reopen it. Thanks!
