### ISSUE TITLE
Incorrect OOB MFA Docs 

### ISSUE THREAD

**Issue by jbelelieu** [auth0/docs#7294]
Regarding this page:
https://github.com/auth0/docs/blob/master/articles/multifactor-authentication/api/oob.md

The POST request in step 3 is incorrect and not inline with this documentation which is correct:
https://auth0.com/docs/api/authentication#verify-with-out-of-band-oob-

- It is missing `client_secret`
- It has `client_id` as an array instead of a string

**Comment by tamigoodall** [comment]
Will update the doc. Moved to Jira Docs Backlog. 
See https://auth0team.atlassian.net/browse/DOCS-581
