### ISSUE TITLE
Incorrect Seed project in Jquery Tutorial

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#731]
When testing Jquery with a ThirdParty API , the seed project downloaded is the widget-with-api one, even if the tutorial has this:

`<%= include('../_includes/_package', { pkgRepo: 'auth0-jquery', pkgBranch: 'gh-pages', pkgPath: (configuration.api && configuration.thirdParty) ? 'examples/widget-with-thirdparty-api' : 'examples/widget-with-api', pkgFilePath: null, pkgType: 'js' + account.clientParam }) %>`

**Comment by Annyv2** [comment]
@ntotten Please reopen, the proposed solution apparently didn't fix the problem

**Comment by iannyanes** [comment]
Fixed
