### ISSUE TITLE
Android Native: Command for gradlew is swapped for Windows and MacOS/Linux

### ISSUE THREAD

**Issue by mikearias3** [auth0/docs#7341]
In the [Android Quickstart](https://auth0.com/docs/quickstart/native/android?download=true), the commands for building the app in MacOS/Linux and Windows are swapped.

![image](https://user-images.githubusercontent.com/5594487/54000556-3b3a1f80-411e-11e9-894c-f39e37992511.png)

**Comment by alexisluque** [comment]
@cocojoe Instructions worked fine as they are.

**Comment by cocojoe** [comment]
Thanks
