### ISSUE TITLE
Layer API Addon has no tutorial

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#735]
There's an addon called Layer API  that has no associated tutorial on the quickstart. 

![layer](https://cloud.githubusercontent.com/assets/5016479/12304764/646ddef0-ba03-11e5-913c-c263e5c205f4.JPG)

![quickstart](https://cloud.githubusercontent.com/assets/5016479/12304793/8fb14bb0-ba03-11e5-90ab-37468bc18d84.JPG)

**Comment by mpaktiti** [comment]
Thank you @Annyv2 ! I moved this issue at our Docs trello board and someone will look into this shortly.
