### ISSUE TITLE
variables in email templates - is user.name valid?

### ISSUE THREAD

**Issue by smcl** [auth0/docs#7381]
The docs at https://auth0.com/docs/email/templates#common-variables give the following example:

    Hello {{ user.name }}. Welcome to {{ application.name }} from {{ friendly_name }}.

However just above this the properties of the `user` object are listed (`email`, `email_verified`, `picture`, `nickname`, `given_name`, `family_name`, `app_metadata`, `user_metadata`) but these _don't_ include `name`.

If `name` is valid, could we add it to the list of properties, or if it's not valid can the example be corrected please?

**Comment by PeterGFernandez** [comment]
As defined in the Normalized User Profile Schema (https://auth0.com/docs/users/normalized/auth0/normalized-user-profile-schema), `name` is a valid attribute of the `user` object, and AFAIK there are no restrictions regarding the attributes available on the `user` object from within email templates.

**Comment by krismb** [comment]
The email templates page has been updated to include `user.name` among the available common variables. https://auth0.com/docs/email/templates#common-variables
