### ISSUE TITLE
Python and Django

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/docs#739]
The Python seed is outdated (eg: dependencies etc...) and we should also consider adding a Django seed / quickstart.

**Comment by no-man-is-an-island** [comment]
+1

**Comment by mcueto** [comment]
Hello, i'm creating a library to handle auth0 authentication with Django @sandrinodimattia i will publish it when finished (this week)

grettings from Chile

UPDATE: Here it is :) [djangorestframework-auth0](https://github.com/mcueto/djangorestframework-auth0/)

**Comment by chenkie** [comment]
Updated
