### ISSUE TITLE
Plugin old version on Phonegap Native Tutorial

### ISSUE THREAD

**Issue by iannyanes** [auth0/docs#74]
In the following tutorial https://auth0.com/docs/quickstart/native-mobile/phonegap/no-api on step 1 is required to install a plugin to show the login popup, InAppBrowser. This plugin was renamed and the developers might not be getting the latest version. 
![inapp rowser](https://cloud.githubusercontent.com/assets/2512171/7975495/3b2535a0-0a38-11e5-9897-c5011b4f3239.png)

**Comment by Annyv2** [comment]
@iannyanes  This can be closed, it's already solved

**Comment by iannyanes** [comment]
Fixed
