### ISSUE TITLE
Custom Domain / Additional Config isn't explicit about config. 

### ISSUE THREAD

**Issue by loujaybee** [auth0/docs#7422]
On: https://auth0.com/docs/custom-domains/additional-configuration

The code that is referenced is: 

```
var webAuth = new auth0.WebAuth({
  clientID: config.clientID, 
  domain: config.auth0Domain, 
  //code omitted for brevity
  overrides: {
  	__tenant: config.auth0Tenant,
  	__token_issuer: config.authorizationServer.issuer
  },
  //code omitted for brevity
});
```

But there is no mention of what the config object properties should be. 

Especially for: 

* `config.auth0Tenant`
* `config.authorizationServer.issuer`

It looks to me that the code snippets were copy-pasta from another tutorial where maybe the `config` variable was defined? It would be nice to explicitly call out where the user can retrieve these values from.

**Comment by roberttod** [comment]
I am having major issues with this myself, really unhelpful documentation.

**Comment by loujaybee** [comment]
For future people searching this issue, my tenant was the tenant name in Auth0 and the issuer was the host name of the auth server. Also, the reason I was experiencing issues was because I enabled custom domains but was still using developer keys, which is [not allowed](https://auth0.com/docs/connections/social/devkeys). Updating developer keys fixed the issue for me.

**Comment by tamigoodall** [comment]
Based on user's use case, this is not allowed. Closing issue.

**Comment by roberttod** [comment]
Your docs explain why this is needed (see https://auth0.com/docs/custom-domains/additional-configuration)
> If you use Universal Login and you have customized the login page, you must update the code to use your custom domain.
> If you are using Lock, the additional values required in the initialization can be seen in the following sample script:

```js
var lock = new Auth0Lock(config.clientID, config.auth0Domain, {
  //code omitted for brevity
  configurationBaseUrl: config.clientConfigurationBaseUrl,
  overrides: {
  	__tenant: config.auth0Tenant,
  	__token_issuer: config.authorizationServer.issuer
  },
  //code omitted for brevity
});
```

but there's no way to decipher what `__tenant` or `__token_issuer` variables should be.

**Comment by tamigoodall** [comment]
Hi @roberttod. I think I may have found the answer for you: auth0.js and lock usually get the tenant name (required for /usernamepassword/login) and the issuer (required for id_token validation) from the domain. This works well for cloud customers and most Private Cloud customers, but some of them have proxies or custom domains where the domain name is different from the tenant/issuer. For those cases, Auth0 has updated auth0.js and Lock to provide two options: `__tenant`  and `__token_issuer`. This is for Private Cloud customers only, and not used by everyone else.

**Comment by tamigoodall** [comment]
I'm going to add some clarifying text to the page.

**Comment by roberttod** [comment]
Thanks @tamigoodall, greatly appreciated!
