### ISSUE TITLE
Bad step cordova tutorial

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#744]
Cordova tutorial uses Ionic step, as seen below. It also explains an outdated instruction, since it should be cordova plugin add cordova-plugin-inappbrowser and not `org.apache.cordova.inappbrowser`

![cordova](https://cloud.githubusercontent.com/assets/5016479/12394256/e0124c2c-bdcc-11e5-9ba8-36bb39eae183.png)

**Comment by iannyanes** [comment]
Solved by https://github.com/auth0/docs/pull/776/
