### ISSUE TITLE
Date.now()  is instantiated with the new keyword and is causing error

### ISSUE THREAD

**Issue by m-henderson** [auth0/docs#7487]
the Date.now() function is a static method, so you don't need to instantiate it with the new keyword. it is causing an error

[Image Redacted]

it should just be Date.now()

**Comment by ofhope** [comment]
@m-henderson this isn't apart of Auth0 docs. Also take care when taking screenshots inside the Auth0 admin. Your application client ID is visible in the URL.

**Comment by cocojoe** [comment]
Thanks for the feedback. I removed the image as it had your application id, can you link to the QS please if this is still an issue.

**Comment by cocojoe** [comment]
I don't see this now, please re-open if still an issue.
