### ISSUE TITLE
c# does not support single quotes in quick start API 

### ISSUE THREAD

**Issue by m-henderson** [auth0/docs#7489]
In the custom API in the quick start, there are single quotes in the code that is showing the user how to setup the api authentication. This is a C# app and using single quites is incorrect, there should be double quotes. 

The single quotes I am referring to:
![image](https://user-images.githubusercontent.com/16070192/56095356-7b20bf00-5ea1-11e9-8097-77acee8f6c7f.png)

The error it causes: 
![image](https://user-images.githubusercontent.com/16070192/56095370-a1465f00-5ea1-11e9-9b85-42ee5794e93b.png)

**Comment by tamigoodall** [comment]
This is for the Quickstarts. These issues are for the docs only.

**Comment by ofhope** [comment]
It appears someone has copied keys into the project using character literals.
Checking the documentation now `csharp.md` and `01-authorizatoin.md` for C# use string litterals ""

```
        options.Authority = "https://${'<%= tenantDomain %>'}/";
        options.Audience = "${'<%= api.identifier %>'}";
```

**Comment by cocojoe** [comment]
@alexisluque please validate

**Comment by alexisluque** [comment]
@cocojoe It seems that is fixed now.
![Screenshot_2019-11-25 API Details(1)](https://user-images.githubusercontent.com/30907012/69584516-193e4100-0fbc-11ea-8e8b-45e1c5d8a73d.png)

**Comment by cocojoe** [comment]
Thanks, will close.
