### ISSUE TITLE
Visual Studio Team Services Deployments documentation is unclear

### ISSUE THREAD

**Issue by realfink** [auth0/docs#7552]
It is unclear how to set the configuration variables on [this](https://github.com/auth0/docs/blob/master/articles/extensions/visual-studio-team-services-deploy.md) page for Azure DevOps:

| Variable | Documentation | Issue |
|---|---|---|
| REPOSITORY |  The project from which you want to deploy rules and database scripts. | The name of the variable is repository, but the documentation states to set this variable to the project name. This is clear. |
| BRANCH | The branch we should monitor for commits. | The Git branch. This is clear. |
| INSTANCE | Your Visual Studio Team Services instance name (without .visualstudio.com). | Azure DevOps calls this the *organization*, not the instance. |
| COLLECTION | Your Visual Studio collection (DefaultCollection for Azure DevOps). | Needs to be set to DefaultCollection. This is clear.|
| BASE_DIR | The base directory, where all your tenant settings are stored | Assuming that this is the directory within the repository. This is clear. |

Based on my understanding of the documentation, there is no place to define the repository where the files are stored. Where is the repository configured?

**Comment by khorne3** [comment]
Hey @realfink! `REPOSITORY` works for both git repo name and TFVC project name. Use `TYPE` to switch between TFVC and Git.

Does that help?

**Comment by realfink** [comment]
Thanks @khorne3. I'm using Azure DevOps (formerly VSTS, not TFVC). There is both a project and a Git repository. I need to define both.

**Comment by khorne3** [comment]
@realfink Ah, gotcha. I'm not sure how to handle that, so I'm working with the engineering team to see if this is possible. I'll get back to you when I have an answer.

**Comment by khorne3** [comment]
@realfink Currently, this isn't possible, but we have an item in our backlog to add this feature in the next release. Thanks for bringing this to our attention!

**Comment by realfink** [comment]
@khorne3 I see that the feature has been [merged](https://github.com/auth0-extensions/auth0-deploy-extensions/pull/23). When will this be released?
Also, you'll need to update the documentation.

**Comment by khorne3** [comment]
@realfink I've pinged engineering and will let you know when I have an answer. We will also update the docs accordingly. Thanks!

**Comment by khorne3** [comment]
@realfink This is live. I misunderstood and was expecting a new field, but what changed is the accepted value for `REPOSITORY` which now accepts `projectName/repoName`. Does that make sense? I'll update the docs accordingly.
