### ISSUE TITLE
Docs reccomends setting auth_token in localStorage.

### ISSUE THREAD

**Issue by sstern6** [auth0/docs#7565]
I thought setting auth_tokens and id_tokens in localStorage was a bad practice bc of different types of attacks, mainly XSS.  I have read in other parts of the docs where it recommends you dont do that.

https://auth0.com/docs/architecture-scenarios/spa-api/part-3

**Comment by khorne3** [comment]
Hi @sstern6! Thanks for letting us know -- we have moved away from using `localStorage` for token storage so we will add this to our backlog to review and update. Thanks!

**Comment by khorne3** [comment]
https://auth0team.atlassian.net/browse/DOCS-677

**Comment by sstern6** [comment]
Great thank you, could you link me to documentation that specifies best practices for SPA + API architecture patterns

cc @khorne3

**Comment by khorne3** [comment]
Hi @sstern6, perhaps [this article](https://auth0.com/docs/security/store-tokens) will be helpful.

**Comment by sstern6** [comment]
Awesome thanks.

**Comment by noobling** [comment]
I am curious why you switched from recommending to store tokens in local storage to in memory. Here is a screenshot of a talk given by one of your colleagues about 2 years ago.

![image](https://user-images.githubusercontent.com/23206864/62517612-55596480-b85a-11e9-8fb1-802716e885cb.png)
