### ISSUE TITLE
Planning Center Connector not functioning

### ISSUE THREAD

**Issue by cherrice** [auth0/docs#7574]
I am using auth0.com to use our planning center logins to access content on our website. I followed the steps on this page...

https://auth0.com/docs/connections/social/planning-center

I registered my app and copied the credentials to auth0 and when I test the connections I get the following error

{
"error": "invalid_request",
"error_description": "InternalOAuthError: Failed to fetch user profile (status: 401 data: HTTP Basic: Access denied.\n)"
}

**Comment by khorne3** [comment]
Hey @cherrice! Sorry to hear that this isn't working for you. Unfortunately, we can't provide support through this channel, so to get additional assistance with this, the [Auth0 Community](https://community.auth0.com/) might be a good place to post regarding this issue. Good luck!

**Comment by cherrice** [comment]
This is an error in the functionality of the system.....Does the community
support that?

*Cherrice Browne*
Project Manager/Technology Support

*Dana Carson Kingdom Ministries, Inc.*
*Leadership Development & Training Corporation*
7401 Gulf Freeway | Houston, TX 77017
www.DrDanaCarson.com <http://www.drdanacarson.com/>
www.DCKMLeadership.com <http://www.kingdomleaderstoday.com/>
281.824.4190 x.5305

**Comment by khorne3** [comment]
Hi @cherrice! I've put in a note for engineering to take a look into this, but until we know what the problem is, I won't be able to say for sure what the next steps are.

**Comment by cherrice** [comment]
@khorne3 - Thanks... Please note I reached out to Planning Center and they have confirmed that their API is functioning correctly. Here is the issue I submitted https://github.com/planningcenter/developers/issues/627 - If your engineers need a point of contact.

**Comment by khorne3** [comment]
@cherrice Thanks!

**Comment by khorne3** [comment]
@cherrice We've pushed a fix to this issue and this should be live in the next few days. Thanks!

**Comment by cherrice** [comment]
Thanks for your assistance.

*Cherrice Browne*
Project Manager/Technology Support

**Comment by cherrice** [comment]
@khorne3  -  The connector now works but I get this error.... 

There was a problem with your log in: This account does not have an email associated, as required by your site administrator. [error code: unknown]

Do I need to post this on the community or should I wait a few days for the fix?

**Comment by khorne3** [comment]
@cherrice I just retried the instructions and it looks like the connection is functioning. The error message looks to me like there might be an issue with the way your PC account is set up (namely there is a missing email address?)

**Comment by cherrice** [comment]
@khorne3  - the PC account username is an email address...something is happening where auth0 is not recognizing it....

**Comment by khorne3** [comment]
@cherrice I'd recommend reaching out to Community to see if there's someone familiar with PC (or Support if your subscription includes it). It sounds like there's an issue w/ your configuration, but unfortunately, I can't say more without looking at your full implementation. Sorry!

**Comment by cherrice** [comment]
@khorne3  - Ok... by the way I posted this original issue in the community 9 days ago with no response.... You have been the most helpful.....

Even though I think this is an issue now with the auth0 wordpress plugin and it's connection with PC

When I disable "Required Verified email" then I get this error

There was a problem with your log in: Invalid state [error code: unknown]

Do I post this on the community?

**Comment by khorne3** [comment]
@cherrice Yes, I would recommend Community, but maybe [this doc](https://auth0.com/docs/cms/wordpress/troubleshoot#i-m-seeing-the-error-message-invalid-state-that-prevents-me-from-logging-in) would be helpful as well?

**Comment by cherrice** [comment]
@khorne3 - Again... Thanks so much for your help... now that the connector is working, I can look into this next issue...
