### ISSUE TITLE
Wordpress configuration guide missing Token Endpoint Authentication Method

### ISSUE THREAD

**Issue by nasajoey** [auth0/docs#7592]
Following the configuration.md guide for Wordpress, there is no description of what "Token Endpoint Authentication Method" should be.  If it is left as default value of "None" then one cannot select the required "Client Credentials" grant type.  This grant type is indicated in the guide as being needed.

So, I've selected "POST" for the "Token Endpoint Authentication Method" hoping for the best at this point.

Guidance needs to be provided in the guide as to this setting.

**Comment by khorne3** [comment]
Hey @nasajoey! Thanks for letting us know -- I've reached out to engineering and will get back to you when I receive an answer.

**Comment by joshcanhelp** [comment]
@nasajoey - You are correct, `POST` is the value you want there. That should be the default one if you selected "Regular Web Application" so I didn't think it was worth it calling it out specifically. Are you seeing something different happening on your end?

**Comment by nasajoey** [comment]
It was a couple nights ago, but I think it stayed "None" for me even after being guided there from the "Regular Web Application" selection, hence the minor confusion on what to select.  Thanks for looking into this.
