### ISSUE TITLE
Email Template "Change Password" to "Reset Email"

### ISSUE THREAD

**Issue by ryanburr** [auth0/docs#7644]
## Description

In the [v2 Managment API](https://auth0.com/docs/api/management/v2#!/Email_Templates/get_email_templates_by_templateName), it states that the `change_password` and `password_reset` email templates are deprecated. 

In the [Customize Your Emails](https://auth0.com/docs/email/templates#change-password-email) docs, it still uses the verbiage of "Change Password", but updating the `change_password` template does not do anything. You actual should be updating the `reset_email` template.

I would like to update the verbiage to "Reset Email" to accurately reflect what is actually being updated here.

## Additional

I'm not sure it this is the correct place, but the Auth0 Dashboard is still using the "Change Password" verbiage as well. IMO, the should be updated to be "Reset Email"

![Screen Shot 2019-05-21 at 10 15 55 AM](https://user-images.githubusercontent.com/3290109/58103884-c40b1800-7bb1-11e9-9f47-4fd0621299e2.png)

**Comment by khorne3** [comment]
@ryanburr Thanks for your help! I've merged the PR and I see we have a ticket to update the Dashboard as well.

**Comment by jasonhibbs** [comment]
Still says "Change Password" for me in the dashboard

![Screenshot 2022-04-28 at 14 53 29](https://user-images.githubusercontent.com/919628/165768167-ffddeb0b-9ef6-4921-a8f6-9c219b2b784d.png)
