### ISSUE TITLE
Can not follow instructions

### ISSUE THREAD

**Issue by klahnakoski** [auth0/docs#7653]
In this section 

https://auth0.com/docs/architecture-scenarios/mobile-api/part-2#configure-the-scopes

![image](https://user-images.githubusercontent.com/2334429/58195917-183bf800-7c97-11e9-856e-c4e2a57117b2.png)

I can not find anything that looks like the example.  Specifically, there is no "scopes" tab.  Here is the closest I could get:

![image](https://user-images.githubusercontent.com/2334429/58195935-268a1400-7c97-11e9-86f5-9638d62699e5.png)

**Comment by khorne3** [comment]
Hi @klahnakoski! We've made some updates to the Dashboard, and Scopes is now Permissions (and Non Interactive Clients is now Machine to Machine Applications). We will update the docs accordingly; thanks for letting us know!
