### ISSUE TITLE
GDPR: Track Consent with Lock sample form link broken (or deprecated?)

### ISSUE THREAD

**Issue by petetnt** [auth0/docs#7678]
In https://auth0.com/docs/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-lock#option-3-redirect-to-another-page the "sample form" directs to a 404 

https://wt-peter-auth0_com-0.run.webtask.io/simple-redirect-rule-consent-form

```
{
"code": 404,
"message": "unable to resolve jtn to webtask token",
"req_id": "1559056393255.670676"
}
```

Regardless this approach seems deprecated regardless? 

> Tenants created after July 16, 2018 will not have access to the underlying Auth0 Webtask Sandbox via the Webtask CLI. Please contact Auth0 at sales@auth0.com to request access.

**Comment by tamigoodall** [comment]
Yes - it is deprecated. We have a current task to remove all references in the docs.
