### ISSUE TITLE
Lock docs are incomplete

### ISSUE THREAD

**Issue by glena** [auth0/docs#784]
There are several undocumented things from the lock API. For example, there is no information about all the params returned in the callback

**Comment by mpaktiti** [comment]
Hello @glena ! Can you check if there are still issues with the Lock documentation? If so can you please give some details to @jeffreylees who is in charge of this part of the documentation?

**Comment by mpaktiti** [comment]
Hey @glena , I'm closing this issue. If this is still valid please reopen it.
