### ISSUE TITLE
Edit on GitHub link broken

### ISSUE THREAD

**Issue by ajmeese7** [auth0/docs#7865]
I'm not sure if this is an issue on every page or just the [one I was on](https://auth0.com/docs/universal-login), but my assumption is that is a bit of code that is reused on every page. I don't know where it is to edit it in a PR, but the link in question is in the middle right of this screengrab:

![image](https://user-images.githubusercontent.com/17814535/60228113-39c06e80-9857-11e9-8c49-724044220989.png)

This is the code for it: 

![image](https://user-images.githubusercontent.com/17814535/60228257-bbb09780-9857-11e9-95d1-1aa3e0c52646.png)

It is not a pointer when you hover over it and it behaves like normal text when clicked, not like a link. If it matters, I am in Firefox Developer Edition, but I replicated this behavior on the page in Chrome and regular Firefox. I also tested it on several other pages like [here](https://auth0.com/docs/universal-login/new-experience-limitations) and [here](https://auth0.com/docs/getting-started) and the issue persisted.

What is curious is I tried it on [this page](https://auth0.com/docs/quickstart/spa/vanillajs#integrate-auth0-in-your-application) and it behaved exactly like I expected it to. I don't know what the difference in the coding between the two pages is or how to go about fixing it, but it seems like an issue to me. If it helps, the code for the working page shows that the link element actually has a href value, unlike the other links:

![image](https://user-images.githubusercontent.com/17814535/60228521-89536a00-9858-11e9-863b-77a0ae04ee75.png)

**Comment by khorne3** [comment]
Hey @ajmeese7. Thanks for letting us know! We're in the process of troubleshooting and we'll get it fixed ASAP.
