### ISSUE TITLE
isAuthenticated flag does not set to True after successful login

### ISSUE THREAD

**Issue by hostiseum** [auth0/docs#7929]
I am new to Auth0 and trying to integrate authentication with my angular app. I have followed everything that was there on the Auth0 site for authentication integration. but unfortunately the this.isAuthenticated variable is not set to True after the user authentication

**Comment by tamigoodall** [comment]
These issues are specifically for documentation errors and problems. I think that you might want to check with the dev team to see if this is a problem.
