### ISSUE TITLE
We should give more relevance on how api authentication works on tutorials

### ISSUE THREAD

**Issue by glena** [auth0/docs#799]
We should add an extra step in all our api tutorials/samples showing how requests should be made and how the `authorization` header should be sent for first time customers.

**Comment by mpaktiti** [comment]
Hello @glena . This is actually part of the quickstarts restructuring and it is in progress. Some of our API tutorials already have it (for example [ASP .NET Core](https://auth0.com/docs/quickstart/backend/aspnet-core-webapi/03-authorization)).
