### ISSUE TITLE
Node (Express) API: Sample Download button doesn't respond

### ISSUE THREAD

**Issue by mikearias3** [auth0/docs#8067]
Link: https://auth0.com/docs/quickstart/backend/nodejs/01-authorization

Description:
When clicking the Download button, nothing seems to happen. In the browser's console a 500 error shows up.

Video:
[ice_video_20190806-211714.zip](https://github.com/auth0/docs/files/3474798/ice_video_20190806-211714.zip)

Screenshot:
![image](https://user-images.githubusercontent.com/5594487/62587645-e0ede800-b890-11e9-9922-b298d0556519.png)

**Comment by albertoperdomo** [comment]
This may be related to an availability issue yesterday.
It seems to work fine for me now. Can you double check if it still fails for you? @mikearias3

**Comment by cocojoe** [comment]
This appears to have been an isolated incident.
