### ISSUE TITLE
[Angular2 Quickstart] Question about localAuthSetup() in Service constructor

### ISSUE THREAD

**Issue by Tazaf** [auth0/docs#8068]
Hi!

I've been following the latest [Angular2 Quickstart Login](https://auth0.com/docs/quickstart/spa/angular2) tutorial, and I was wondering if, in [the Service code](https://auth0.com/docs/quickstart/spa/angular2#add-an-authentication-service), there was a particular reason why the `localAuthSetup()` function was not called directly by the service constructor ?

Something like this:
```ts
// Imports

@Injectable(/* ... */)
export class AuthService {

  // Properties

  constructor(private router: Router) {
    this.localAuthSetup();
  }

  // Other methods

  private localAuthSetup() {
    // Method body
  }

  // Other methods

}
```

I've implemented this solution in my app, and it seems to work OK. But maybe there's some precaution or side effect that I did not saw?

**Comment by naingaungphyo** [comment]
Because We dont want to call localAuthSetup method everytime when we DI the Auth Service right?
We will call localAuthSetup method once only when we bootstrap our app. (AppComponent ngOnInit lifecycle call).

**Comment by Tazaf** [comment]
Why would `localAuthSetup()` be called each time the service is DIed somewhere? 🤔

Unless I'm mistaken, this service is a `providedIn: 'root'` kind of service, and thus a singleton that is instanciated once the first time its injected anywhere in the app, then reused for every consecutive injection, meaning the constructor is only executed the first time, which is indeed what we want.

**Comment by naingaungphyo** [comment]
> Unless I'm mistaken, this service is a providedIn: 'root' kind of service, and thus a singleton that is instanciated once the first time its injected anywhere in the app

You're right!

**Comment by cocojoe** [comment]
@kmaida you mind looking at this please.

**Comment by kmaida** [comment]
Hello @Tazaf, the general idea is to do so when the application bootstraps on init, but there shouldn't be any issues with calling it in the service constructor (as long as it's provided as a singleton at root). :) Thanks for pointing this out, as doing so in the constructor does simplify the steps to integration. Handling of the callback can move into the constructor as well (as long as login is redirect-based.) I will take a look at updating the guidance.

**Comment by Tazaf** [comment]
Awesome, thanks for the update 👍 

Interesting to see that `handleAuthCallback()` can also be called from within the constructor.

**Comment by kmaida** [comment]
Yes, the callback can be handled from the constructor because the application reloads after authentication, and the callback handling uses the browser API to check the query parameters rather than relying on Angular to do so (as using Angular caused issues with race conditions with when the Angular router parses the URL contents).

Thanks again for calling this to our attention and helping us to improve the Quick Start guidance!
