### ISSUE TITLE
“Page does not exist error” when going to the dashboard from a tutorial after login

### ISSUE THREAD

**Issue by silverxmary** [auth0/docs#810]
When a user is NOT LOGGED IN and viewing any tutorial, for example, https://auth0.com/docs/quickstart/backend/azure-mobile-services 

When I click the first link of the tutorial the step 1.
1. Activate the add-on.

Go to Application **Add-ons** page and activate the Azure Service Bus add-on.

The user is redirected to the authentication page and after a successful authentication the placeholder YOUR_APPLICATION_ID does not update resulting in a url like this one: https://manage.auth0.com/#/applications/YOUR_CLIENT_ID/addons 
expected result is that after logging in, the placeholder should be updated to have the client id to correctly access the application configuration dashboard.

If I am already logged in when I click it It redirects me successfully to aadons

![login](https://cloud.githubusercontent.com/assets/9697948/12677649/a68822e4-c66c-11e5-9897-102203aa36d8.jpg)
![redirecterror](https://cloud.githubusercontent.com/assets/9697948/12677648/a683a7fa-c66c-11e5-8d5d-8b7f55b40a45.jpg)

**Comment by iannyanes** [comment]
Out of Scope - Backend issue.
