### ISSUE TITLE
Azure Mobile Services non existence links 

### ISSUE THREAD

**Issue by silverxmary** [auth0/docs#811]
the links must have been moved
the tutorial https://auth0.com/docs/quickstart/backend/azure-mobile-services

in Additional Information
1. CREATE A CLIENT FOR THE APPLICATION

WAMS endpoints can be used from anywhere: Android, iOS, Windows 8 **C#** or **JavaScript** and Windows Phone. You can use any of these tutorials for configuring your app that will interact with WAMS.

![nonlink](https://cloud.githubusercontent.com/assets/9697948/12679271/6d807cfe-c675-11e5-8970-4105d14d7f06.jpg)
![nonlink2](https://cloud.githubusercontent.com/assets/9697948/12679272/6d81f6a6-c675-11e5-863e-724aa4b39fd4.jpg)

**Comment by iannyanes** [comment]
Dup of #810

**Comment by Annyv2** [comment]
@iannyanes This is not a duplicate, referenced it in a PR
