### ISSUE TITLE
WPF / Winforms UnauthorizedAccessException exception

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#812]
If you use `await auth0.LoginAsync` method as suggests in tutorial and then close login popup, it rise `UnauthorizedAccessException`. But when are using code from seed project it handles exception:

``` cs
auth0.LoginAsync(this).ContinueWith(t =>
{
   if (t.IsFaulted)
      this.UserProfileTextBox.Text = t.Exception.InnerException.ToString();
   else
      this.UserProfileTextBox.Text = t.Result.Profile.ToString();
},
TaskScheduler.FromCurrentSynchronizationContext());
```

**Comment by jerriep** [comment]
Will look into it

**Comment by mpaktiti** [comment]
Hey @jerriep does this issue still stand or should we close it?

**Comment by jerriep** [comment]
Sorry, I'll update docs and then close this issue
