### ISSUE TITLE
React Quickstart

### ISSUE THREAD

**Issue by Satyam** [auth0/docs#8123]
In the sample code in https://auth0.com/docs/quickstart/spa/react#install-the-auth0-react-wrapper, it should be better to use `useReducer` than several individual `useState` hooks.  Though calls to `setXxxx` methods are batched, since there are async calls in between each `setXxxx`, each one constitutes a batch on its own.  This forces several re-renders of most of the tree, since the Auth0 Context Provider is so close to the root.  Another, less elegant solution would be to put all the  `setXxxx` calls together towards the end where they can be batched together.

Related to this, you should seldom set the `<Auth0Context.Provider  value={{ ... }}>` with an object literal assembled on the spot as each re-render (and, as I mentioned, there are already too many) creates a new object for `value`, even if none of the properties on the object has changed.  It is better to memoize (with `useMemo`) the context beforehand and provide the memoized value for that context.

Function definitions such as those for `loginWithPopup` and `handleRedirectCallback` should also be memoized via `useCallback` or defined on initialization within the first `useEffect` to be later memoized when the context is assembled with `useMemo`.

I know my React hooks but not so much about Auth0, which I am just learning so I am afraid I cannot volunteer much reliable sample code as I am not sure of interactions and side effects of the Auth0 API. 

Though, in principle, the Auth0 context provider should only change, and thus re-render, on initialization and after login, re-renders might be induced by components higher up in the tree, which this sample would only contribute to propagate multiplied a few times.

As sample code such as this is so often copied and pasted unquestioned, I believe it should follow the best practices.

Thanks and regards

Satyam

**Comment by cocojoe** [comment]
Thanks for the feedback @Satyam we can certainly make improvements here and are working on these.
