### ISSUE TITLE
React Quickstart - doesn't work with window.history

### ISSUE THREAD

**Issue by justinhelmer** [auth0/docs#8126]
Wanted to give your team a heads up that when following the [quickstart guide](https://auth0.com/docs/quickstart/spa/react), I ran into issues with the documentation in places using `window.history.replaceState`. This method is referenced two times, in the section called [Install the Auth0 React wrapper](https://auth0.com/docs/quickstart/spa/react#install-the-auth0-react-wrapper) as well as the section called [Integrate the SDK](https://auth0.com/docs/quickstart/spa/react#integrate-the-sdk).

The issue is, the `history` object used by `react-router` is an observer. It is an instance of an abstracted history stack through [this npm dependency](https://www.npmjs.com/package/history). The observer will only trigger callbacks registered with the same instance used by the router.

To solve the problem in the quickstart example, the following can work:

1. Create a single instance of browser history:

```js
// src/history.js
import { createBrowserHistory } from 'history';
export default createBrowserHistory();
```

2. Configure the lower-level `<Router>` component to use this shared instance of history:
```jsx
// src/App.js
import history from './history';

function App() {
  return (
    <div className="App">
     {/* New - use BrowserRouter to provide access to /profile */}
      <Router history={history}>
        <header>
          <NavBar />
        </header>
        <Switch>
          <Route path="/" exact />
          <Route path="/profile" component={Profile} />
        </Switch>
      </BrowserRouter>
    </div>
  );
}
```

3. Update instances of `window.history.replaceState` with `history.replace`:
```js
// src/react-auth0-wrapper.js
import history from './history';

const DEFAULT_REDIRECT_CALLBACK = () =>
  history.replace(window.location.pathname);
```

```js
// src/index.js
const onRedirectCallback = appState => {
  history.replace(appState && appState.targetUrl ? appState.targetUrl : window.location.pathname);
};
```

Based on this [GitHub issue](https://github.com/ReactTraining/react-router/issues/6304), it would appear that `window.history.replaceState` would have worked in an old version of `react-router`, but now the application maintains it's own copy of history, which must be used.

Cheers; hope this helps.

----

`react@16.9.0`
`react-router@5.0.1`
`@auth0/auth0-spa-js@1.1.1`

**Comment by cocojoe** [comment]
This looks resolved in #8151 please re-open if I am mistaken. Thanks
