### ISSUE TITLE
WPF / Winforms outdated screenshot

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#813]
Screenshot in WPF/Winforms tutorial outdated. UI of popup window now look like that:

![image](https://cloud.githubusercontent.com/assets/1114365/12679498/353d3d54-c6ad-11e5-9cce-51fa44d9f69b.png)

instead of this:

![image](https://cdn.auth0.com/docs/media/articles/native-platforms/wpf-winforms/wpf-winforms-step1.png)

**Comment by jerriep** [comment]
I will update this in the docs when I fix this one:
https://github.com/auth0/Auth0.WinformsWPF/issues/13
