### ISSUE TITLE
QS download modal doesn't link to the correct Application

### ISSUE THREAD

**Issue by lbalmaceda** [auth0/docs#8156]
I'm currently trying out a the Node WebApp QS. https://auth0.com/docs/quickstart/webapp/nodejs. After clicking "log in and download" I'm showed this modal. However, the "Application settings" link for steps 1 and 2 link to a different application (even a different application type, not supported by this QS!!) than the one I've selected in the dropdown (called is "webapp").

![image](https://user-images.githubusercontent.com/3900123/63781364-06827600-c8c0-11e9-8bc0-7fa53c15ad1f.png)

![image](https://user-images.githubusercontent.com/3900123/63781634-6c6efd80-c8c0-11e9-8633-bc4048a35176.png)

**Comment by cocojoe** [comment]
@lbalmaceda is this still an issue? if so please talk with @davidpatrick, could pair with him on a fix.

**Comment by lbalmaceda** [comment]
@cocojoe The issue described here is now resolved. I guess we can close it. ✅ 

An improvement we can still do is select by default a client from the select input that matches the application type for this quickstart. i.e. pick a web app application and not the first item of the array. 

See what happens today:
![image](https://user-images.githubusercontent.com/3900123/69366766-c3912e00-0c75-11ea-8b5c-b6235217b786.png)

**Comment by cocojoe** [comment]
Yeah that makes sense, can you take that action item and raise with David.
