### ISSUE TITLE
Incorrect Seed project in Jquery Tutorial

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#816]
On Jquery tutorial, when selecting a ThirdpArty API, the downloaded seed project is widget-with-api, even if this is how it's being selected `<%= include('../_includes/_package', { pkgRepo: 'auth0-jquery', pkgBranch: 'gh-pages', pkgPath: (configuration.thirdParty) ? 'examples/widget-with-thirdparty-api' : 'examples/widget-with-api', pkgFilePath: null, pkgType: 'js' + account.clientParam }) %>`

Proposed solution didn't fix the problem https://github.com/auth0/docs/issues/731

**Comment by iannyanes** [comment]
The "Select Third Party API" option is no longer avilable
