### ISSUE TITLE
ThirdParty API Step not showing in Jquery tutorial

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#817]
This step is not shown even if  a ThirdParty API is selected `<% if (configuration.thirdParty) { %>
4. Configure calls to a Third Party API`

https://github.com/auth0/docs/issues/730

**Comment by mpaktiti** [comment]
Assigned to TechAid.

**Comment by vmartynets** [comment]
Tutorials now have different structure. I have not found any `if (configuration.thirdParty)` in jquery tutorial. Looks like it can be closed.

**Comment by mpaktiti** [comment]
Thank you @Amialc 👍
