### ISSUE TITLE
handleCallback ⟷ handleAuthentication

### ISSUE THREAD

**Issue by j6k4m8** [auth0/docs#8212]
Unless I'm mistaken, [the vue docs](docs/articles/quickstart/spa/vuejs/01-login.md) reference the wrong function name: Under [Handle Authentication Tokens](https://github.com/auth0/docs/blob/master/articles/quickstart/spa/vuejs/_includes/_centralized_login.md#handle-authentication-tokens), I believe the code points to `handleAuthentication`, but the markdown bullet list right below calls it `handleCallback`.

But I'm a bit out of my depth, so wanted to Issue this rather than PR...

**Comment by AlokTakshak** [comment]
@jeffreylees  I have raised a pull request for the required change. please have a look
