### ISSUE TITLE
Highlight algorithm change from HS256 -> RS256 in auth0.js >= v9.0 in quickstarts

### ISSUE THREAD

**Issue by xyfoo** [auth0/docs#8230]
If one followed the Vue quickstart documentation, https://auth0.com/docs/quickstart/spa/vuejs, they would encounter the following error:

```Error Message: The ID Token cannot be validated because it was signed using the HS256 algorithm and public applications (such as a browser) can’t store secrets. Please read the associated doc for ways to fix this.```

Resolution to this error is documented here: https://auth0.com/docs/errors/libraries/auth0-js/invalid-token#parsing-an-hs256-signed-id-token-without-an-access-token

Maybe the application algorithm change should be highlighted in the docs.

**Comment by cocojoe** [comment]
@stevehobbsdev might be worth linking ?

**Comment by stevehobbsdev** [comment]
Note that this is less to do with the actual quickstart and more to do with the fact that sometimes the Default App can be incorrectly created by Auth0, with the signature configuration set to HS256. This will affect all our SPA quickstarts.

I propose adding a small section underneath the existing configuration for Allowed Login URLs etc, that asks the reader to verify that Token Signature is set to HS256.

**Comment by stevehobbsdev** [comment]
Actually, this needs some more thought as it looks like the user cannot change this setting any more and now defaults to RS256.
