### ISSUE TITLE
'lock' library version in cdn is outdated

### ISSUE THREAD

**Issue by javlc** [auth0/docs#83]
Lock library info link: https://auth0.com/docs/libraries/lock
This issue found while reviewing react tutorial at: https://auth0.com/docs/quickstart/spa/react/no-api
(Most likely that all pertinent tutorials will need to have this reference updated)

![lock-cdn-outdated-version](https://cloud.githubusercontent.com/assets/3148402/7987238/4a2e96d2-0aaa-11e5-8137-8556d3a88d92.png)

**Comment by iannyanes** [comment]
Fixed https://auth0.com/docs/quickstart/spa/react/no-api
