### ISSUE TITLE
Outdated link Azure Blob Storage Thirdparty API

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#856]
The instructions lead to https://manage.windowsazure.com/ but the new portal link is  https://portal.azure.com/, which is already in production according to http://www.microsofttrends.com/2015/12/02/azure-preview-portal-is-now-production-portal/

**Comment by jerriep** [comment]
The layout of the new Azure Portal is completely different from the old one, so this should (potentially) not just be a simple update of the link.

If there are any instructions or screenshots then those must be updated as well.

**Comment by Annyv2** [comment]
Yes, I created another issue for it https://github.com/auth0/docs/issues/857

**Comment by iannyanes** [comment]
Out of scope - Private Repo.
