### ISSUE TITLE
Outdated image Azure Blob Storage

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#857]
The picture that explains the steps in the Azure Blob Storage Tutorial is from the old portal it should be updated. Also the name of the Keys needs to be updated 
![outdated](https://cloud.githubusercontent.com/assets/5016479/12961214/719d5b54-d011-11e5-910a-ad131f7aff58.JPG)

**Comment by iannyanes** [comment]
Out of scope - Private Repo
