### ISSUE TITLE
No blanks allowed in settings Azure Blob Storage

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#858]
When configuring the blob storage settings, some fields are supossed to be "optional", but when I tried to leave them blank it wouldn't let me. On the instructions, it's even explained that you can actually leave some of them blank, "if left blank...". Also, there is no default already set in the jwt token expiration (it's empty so I had to write a number, since it wouldn't let me leave it like that)

![no blanks allowed](https://cloud.githubusercontent.com/assets/5016479/12961356/3f991e08-d012-11e5-8564-c1eb48955d71.JPG)

**Comment by Annyv2** [comment]
@jerriep Hi, what do you think about this one? is this the expected result?

**Comment by jerriep** [comment]
@Annyv2 Oh sorry, I do not know about that... :)

**Comment by iannyanes** [comment]
Out of scope - private repo
