### ISSUE TITLE
Windows phone Seed Project link broken

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#86]
Link to download Windows Phone Seed Project sends to a local address:

http://localhost:3000/Auth0.WindowsPhone/master/create-package?path=examples/WindowsPhoneSilverlight&type=none&clientId=08t4pch5E6TFfiOA4i6wGmOsSS27P9ly

![2015-06-05_2243](https://cloud.githubusercontent.com/assets/12707130/8017955/6a2afbc6-0bd4-11e5-8439-62b9aa39bc48.png)

![2015-06-05_2233](https://cloud.githubusercontent.com/assets/12707130/8017954/6a27fdc2-0bd4-11e5-9df7-7c9ca06ef06e.png)

**Comment by iannyanes** [comment]
Issue fixed. https://auth0.com/docs/quickstart/native-mobile/windowsphone/no-api
