### ISSUE TITLE
Firebase old image

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#860]
The firebase tutorial has this image 
![oldfreibase](https://cloud.githubusercontent.com/assets/5016479/12980687/c534c966-d0af-11e5-8e3c-ff207697a1ea.JPG)

But currently it looks like this 
![firebase](https://cloud.githubusercontent.com/assets/5016479/12980704/d5068604-d0af-11e5-9872-8038a3aea968.JPG)

**Comment by iannyanes** [comment]
Out of scope - Private repo
