### ISSUE TITLE
aurelia tutorial step 5 dependency

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#861]
In optional step 5 suggest to install `jwt-decode` using `npm install jwt-decode` which is not save dependency to `package.json`. Better use `npm install jwt-decode --save` to save dependency to `package.json` automatically.

![image](https://cloud.githubusercontent.com/assets/1114365/12982270/c41d0ae2-d0ec-11e5-8120-d7f1b6644ee1.png)

**Comment by iannyanes** [comment]
Solved
