### ISSUE TITLE
Gender specific instructions

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#864]
NodeJS Web App: 

The tutorial says him, he. This can be reworded to avoid using genders in the instruction

![nodejsgender](https://cloud.githubusercontent.com/assets/5016479/12987421/35d5760c-d0ce-11e5-976d-88e12de90e15.JPG)

This is also present in: java web app tutorial. sso/regular-web-apps-sso.md azure-mobile-services scala.md saas-apps.md invite-only.md  snippets/native-platforms/ionic/setup.md nancyfx and others. 

On Jquery tutorial this is explained `<p>His name is <span class="nick"></span></p>`
On Angular too

**Comment by mpaktiti** [comment]
Assigned to TechAid: 3319

**Comment by mpaktiti** [comment]
Fixed

**Comment by camimonse** [comment]
Sanity failed, the gender still needs to be changed on the following pages:
1. https://github.com/auth0/docs/blob/24c1593c7a6010f90fc66fb797f2273cbdc2192f/articles/appliance/admin/inviting-coadmins.md
   ![image](https://cloud.githubusercontent.com/assets/18585436/20400279/6bc12526-acca-11e6-85e7-1825531aee0c.png)

2.
https://github.com/auth0/docs/blob/88a98b65c45725ef32e2b6076a4c9b39ba5ebf86/articles/native-platforms/android/07-authorization.md
![image](https://cloud.githubusercontent.com/assets/18585436/20400302/8725db9a-acca-11e6-8d59-414c259730b7.png)

3.
https://github.com/auth0/docs/blob/88a98b65c45725ef32e2b6076a4c9b39ba5ebf86/articles/server-platforms/nancyfx/01-login.md
![image](https://cloud.githubusercontent.com/assets/18585436/20400327/a2d63ace-acca-11e6-8f29-1170d55b10f1.png)

4.
https://github.com/auth0/docs/blob/745da825b9d92372013627bf096b9f16b0a055fc/articles/libraries/lock-ios/lock-ios-api.md
![image](https://cloud.githubusercontent.com/assets/18585436/20400346/b7c017b6-acca-11e6-92d7-ce0188af1385.png)

5.
https://github.com/auth0/docs/blob/88a98b65c45725ef32e2b6076a4c9b39ba5ebf86/articles/server-apis/aspnet-core-webapi/03-authorization.md
![image](https://cloud.githubusercontent.com/assets/18585436/20400376/d53e602c-acca-11e6-8153-60058aeb1ee7.png)

6.
https://github.com/auth0/docs/blob/88a98b65c45725ef32e2b6076a4c9b39ba5ebf86/articles/server-apis/webapi-owin/03-authorization.md
![image](https://cloud.githubusercontent.com/assets/18585436/20400858/d364bdda-accc-11e6-8670-0873474f244d.png)

7.
https://github.com/auth0/docs/blob/745da825b9d92372013627bf096b9f16b0a055fc/articles/server-platforms/_includes/_authorization-introduction.md
![image](https://cloud.githubusercontent.com/assets/18585436/20400887/f94bdc72-accc-11e6-9f62-8cf2b0594dae.png)

**Comment by angelaLazar** [comment]
Fixed by: https://github.com/auth0/docs/pull/3031
