### ISSUE TITLE
Auth0's Privacy Shield Registration link doesn't work

### ISSUE THREAD

**Issue by mw446391** [auth0/docs#8663]
In docs/articles/compliance/index.md, the link [Auth0's Privacy Shield Registration](https://www.privacyshield.gov/participant?id=a2zt000000001VJAAY&status=Active) gives this error:

> Invalid status parameter in the URL.

**Comment by tamigoodall** [comment]
Thanks for pointing that out. Here is the correct link: https://www.privacyshield.gov/participant?id=a2zt0000000TQsZAAW&status=Active
We will update the doc.
