### ISSUE TITLE
Please document how to document

### ISSUE THREAD

**Issue by bionicles** [auth0/docs#8666]
### Describe the problem you'd like to have solved

I want to document an API secured with Auth0 so developers can use it easily

### Describe the ideal solution

Please add a section of docs about how to document APIs secured with auth0 (using OpenAPI3, GraphQL, or RPC/JSON)

## Alternatives and current work-arounds

Could just not write docs

### Additional context

Friends don't let friends write crappy docs... how do you think we should write ours if the routes are secured by auth0?

**Comment by tamigoodall** [comment]
Hi @bionicles 
We don't have any preferences for how you might like to document your API. Feel free to create documents any way you would like.
