### ISSUE TITLE
React Native iOS Tutorial - FAQ link broken

### ISSUE THREAD

**Issue by aguerere** [auth0/docs#868]
Broken link in the React Native iOS Tutorial. https://auth0.com/docs/quickstart/hybrid/react-native-ios/no-api

![faq-broken-link-react-native-ios-110216](https://cloud.githubusercontent.com/assets/14084214/12993485/9517eb90-d0ec-11e5-8eab-c97f91fbbd3d.png)

**Comment by iannyanes** [comment]
Solved
