### ISSUE TITLE
Auth0.WindowsPhone package not working with .Net Framework v4.5

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#87]
Installing NuGet Package for Windows Phone fails on .Net Framework 4.5 application:

PM> Install-Package Auth0.WindowsPhone
Installing 'Auth0.WindowsPhone 1.4.1'.
Successfully installed 'Auth0.WindowsPhone 1.4.1'.
Adding 'Auth0.WindowsPhone 1.4.1' to WebApplication2.
Uninstalling 'Auth0.WindowsPhone 1.4.1'.
Successfully uninstalled 'Auth0.WindowsPhone 1.4.1'.
Install failed. Rolling back...
Install-Package : Could not install package 'Auth0.WindowsPhone 1.4.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package 
does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
- Install-Package Auth0.WindowsPhone
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by iannyanes** [comment]
Closing since this was created due to error in test case.
