### ISSUE TITLE
/users-exports job sample error

### ISSUE THREAD

**Issue by dmark** [auth0/docs#8733]
ref: https://community.auth0.com/t/docs-for-creating-export-users-job-is-buggy/37055

ref: https://auth0.com/docs/api/management/v2#!/Jobs/post_users_exports

The sample export job in the management API docs has an extra list structure that should not be there:

```
  "fields": [
    [
      {
```
vs.
```
  "fields": [
      {
```

**Comment by tamigoodall** [comment]
We can't currently make changes to this content.

**Comment by gatkinsNZ** [comment]
I just hit this same issue with the documentation. Closing the issue when it isn't solved seems odd, shouldn't you keep this open so you can fix it eventually?
