### ISSUE TITLE
Xamarin tutorial sends to old deprecated version of login widget

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#88]
In Xamarin tutorial's (No API) step 3 (Integration), "Auth0 Login Widget" link redirects to an old version of the login widget (https://auth0.com/docs/libraries/login-widget2). It should be linking to the newer "Lock" widget (https://auth0.com/docs/libraries/lock)

![2015-06-06_1455_001](https://cloud.githubusercontent.com/assets/12707130/8020977/f468ff9e-0c5c-11e5-86f9-94694cf35e63.png)
![2015-06-06_1455](https://cloud.githubusercontent.com/assets/12707130/8020978/f6c7eaca-0c5c-11e5-8d29-1dd56e9dff03.png)

**Comment by solepano** [comment]
This is fixed in prod.
