### ISSUE TITLE
Lock SDK Fails to show lock's cdn link when not logged in

### ISSUE THREAD

**Issue by silverxmary** [auth0/docs#889]
In laravel tutorial 
https://auth0.com/docs/quickstart/webapp/laravel

building app following the steps
in Step 5 
The html code when I am not logged in the lock line is blank

<script src=""></script>

![pasted image at 2016_02_15 12_54 pm](https://cloud.githubusercontent.com/assets/9697948/13058742/538b8d7c-d3f7-11e5-919c-18212d6313d8.png)

so when I test the code I get an error
![pasted image at 2016_02_15 12_49 pm](https://cloud.githubusercontent.com/assets/9697948/13058767/8a9c3500-d3f7-11e5-8551-65747074fb6e.png)

But when I am logged The line is correct and I get no error in my code.
![imageloggedlaravel](https://cloud.githubusercontent.com/assets/9697948/13058800/c6610214-d3f7-11e5-9172-124e8f91bb56.png)

**Comment by iannyanes** [comment]
Solved
