### ISSUE TITLE
Refresh Token API docs do not match

### ISSUE THREAD

**Issue by maxwellsmart84** [auth0/docs#8938]
### Description
It appears the API documentation is missing the optional scope parameter listed here:
https://auth0.com/docs/flows/guides/device-auth/includes/refresh-tokens

I have tested this endpoint and confirmed the above documentation is correct, if you optionally pass "scope" when requesting a refresh token you are returned an `access_token` with less permissions.

However - when looking here:
https://auth0.com/docs/api/authentication#refresh-token 

There is no mention of scope as an optional parameter.  This document should be updated to include the optional "scope" parameter.

### Reproduction

https://auth0.com/docs/flows/guides/device-auth/includes/refresh-tokens

<img width="1162" alt="Screen Shot 2020-04-17 at 9 51 03 AM" src="https://user-images.githubusercontent.com/14876902/79576318-1211ef80-8091-11ea-979b-3a7dd8352747.png">

https://auth0.com/docs/api/authentication#refresh-token 

<img width="1020" alt="Screen Shot 2020-04-17 at 9 50 28 AM" src="https://user-images.githubusercontent.com/14876902/79576332-1b02c100-8091-11ea-82bd-20578febe913.png">

### Environment

> Please provide the following:

- **Version of this library used:**  --- N/A
- **Version of the platform or framework used, if applicable:** --N/A
- **Other relevant versions (language, server software, OS, browser):** 
 -- Chrome Version 80.0.3987.163 (Official Build) (64-bit)

- **Other modules/plugins/libraries that might be involved:** -- N/A

**Comment by rkhoriander** [comment]
@maxwellsmart84 , thanks for pointing this out to us. The PR that fixes this issue should be merged shortly.
