### ISSUE TITLE
iOS ObjC Tutorial - Lock pod version outdated

### ISSUE THREAD

**Issue by aguerere** [auth0/docs#898]
Lock pod version in iOS ObjC tutorial should be updated to 1.22, current by the creation date of this issue, or later.

![ios-objc-pod-lock-version-021516](https://cloud.githubusercontent.com/assets/14084214/13066364/40a929e0-d437-11e5-9167-b9ea6f2b8d1e.png)

**Comment by iannyanes** [comment]
Solved
