### ISSUE TITLE
Enhance Example Code in React SPA Quickstart

### ISSUE THREAD

**Issue by ITenthusiasm** [auth0/docs#8987]
First of all, I wanted to say thanks a ton for providing docs for using the Auth0 SPA SDK with React. They definitely hastened my transition from `auth0-js` to `auth0-spa-js`. Unfortunately, I found the code a bit difficult to follow, so that's why I'm opening this issue.

### The Problem

I've found the code examples in the [React SPA Quickstart](https://auth0.com/docs/quickstart/spa/react/01-login) somewhat overwhelming and difficult to follow. Moreover, a few small parts are non-compliant with React standards.

### The Solution

The solution is to update the code to be simpler, and to remove any code that contradicts common standards in the React community or that doesn't get used.

To this end, I've created a [public repo](https://github.com/XxX-MLGNoob-XxX/alt-react-auth0-docs) with some suggested changes. The last commit should show the differences between my suggestions and the code on the Quickstart page. In my `README`, I've listed out the updated files, the main changes, and the reasoning behind behind each change. You don't have to read it if you don't have any concerns about my changes.

I took this approach because I didn't know what size would be too large for a PR. But if there's a different preference for how to go about this, please let me know. I largely wanted to get my suggestions out there and see if they'd be acceptable or not.

Thank you for your time.

**Comment by audiolion** [comment]
Agreed that the docs for auth0 react suggest you to do some non-standard things that are pretty weird. I like a lot of the changes @XxX-MLGNoob-XxX has suggested.
