### ISSUE TITLE
Component search for Xamarin.Auth0Client does not bring any results

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#90]
While following Xamarin (No API) tutorial, Step 2. Search and double-click on Xamarin.Auth0Client component. Xamarin Studio component search does not bring any results when searching for Xamarin.Auth0Client unless "Xamarin." is removed from the search string.

![2015-06-06_1725](https://cloud.githubusercontent.com/assets/12707130/8021551/144c7cd6-0c72-11e5-851e-bf83369b7a7a.png)

![2015-06-06_1732](https://cloud.githubusercontent.com/assets/12707130/8021550/144b293a-0c72-11e5-8bbc-028a72735226.png)

**Comment by vmartynets** [comment]
It's already fixed.
![image](https://cloud.githubusercontent.com/assets/1114365/17625492/d1cb3a88-60b1-11e6-80a2-4f713e7462f4.png)
