### ISSUE TITLE
PHP (Laravel) Quickstart - "Optional Custom User Handling" section is broken - "Target class [App\Repositories\CustomUserRepository] does not exist"

### ISSUE THREAD

**Issue by miking7** [auth0/docs#9002]
### Description

I have tried to follow the latest guide located here on a fresh install of Laravel v7.10.3.
It works until I try to implement the custom user handling.

I just get the error:
> Target class [App\Repositories\CustomUserRepository] does not exist.

Findings:
> I've tried doing composer dump and clearing Laravel cache.

> I also tried (without success) the "fix" mentioned in this issue: [https://github.com/auth0/laravel-auth0/issues/182](https://github.com/auth0/laravel-auth0/issues/182)

I found that if I remove all code from within the CustomUserRepository class, the error disappears (however obviously no new functionality is added).  
* Re-adding the upsertUser() function produces no errors.
* Re-adding either the getUserByDecodedJWT() or getUserByUserInfo() functions brings the error back again.

(This demonstrated to me that Laravel's "Target class [xxx] does not exist" error is not very helpful, because can also be triggered by coding errors in the class itself - not simply whether or not the class exists.)

As mentioned in the other above-referenced issue-report, it appears that the example code given in the QuickStart for the CustomUserRepository is no longer compatible with Auth0UserRepository.  (Presumably Auth0/Login/Repository/Auth0UserRepository.php may have changed since the tutorial was written?)

I'm no Laravel or Auth0 expert, but I kept making changes until all errors were resolved.  The main issue is that the Auth0UserRepository now the "Authenticatable" class, however a few other changes were required too.

The final (working) code for the `CustomUserRepository.php` file looks like this: 
```php
<?php

namespace App\Repositories;

use App\User;

use Auth0\Login\Auth0User;
use Auth0\Login\Auth0JWTUser;
use Auth0\Login\Repository\Auth0UserRepository;
use Illuminate\Contracts\Auth\Authenticatable;

class CustomUserRepository extends Auth0UserRepository
{

    /**
     * Get an existing user or create a new one
     *
     * @param array $profile - Auth0 profile
     *
     * @return User
     */
    protected function upsertUser( $profile ) {  
        return User::firstOrCreate(['sub' => $profile['sub']], [
            'email' => $profile['email'] ?? '',
            'name' => $profile['name'] ?? '',
        ]);
    }

    /**
     * Authenticate a user with a decoded ID Token
     *
     * @param array $decodedJwt
     *
     * @return Auth0JWTUser
     */
    public function getUserByDecodedJWT(array $decodedJwt) : Authenticatable
    {
        $user = $this->upsertUser( (array) $jwt );
        return new Auth0JWTUser( $user->getAttributes() );
    }

    /**
     * Get a User from the database using Auth0 profile information
     *
     * @param array $userinfo
     *
     * @return Auth0User
     */
    public function getUserByUserInfo(array $userinfo) : Authenticatable
    {
        $user = $this->upsertUser( $userinfo['profile'] );
        return new Auth0User( $user->getAttributes(), $userinfo['accessToken'] );
    }

}
```

This code could be pasted back into your documentation to fix all the above-mentioned problems.

### Additional Important Missing Info in QuickStart/Tutorial:
Note: It should also be mentioned in this QuickStart/tutorial that after running the migration to modify the Users table, that the "sub" field must also be added as a "fillable" field in the User model (app/User.php).  Ie:
```php
    protected $fillable = [
        'name', 'email', 'sub',
    ];
```

Failing to do so, will cause SQL insert errors when the upsertUser() function tries to add a new User record, since the "sub" field won't be included in the query, and the query inserts NULL values for "subs" instead.

### Reproduction

Follow: https://auth0.com/docs/quickstart/webapp/laravel#optional-custom-user-handling

### Environment

* Version of this library used: 6.0.1
* Version of the platform or framework used, if applicable:  Laravel 7.2.1~7.10.3

**Comment by joshcanhelp** [comment]
@miking7 - Huge thank you for the very detailed report here and fix! I'm trying this out locally now and will put through a PR today.
