### ISSUE TITLE
Outdated Documentation for Spring Security

### ISSUE THREAD

**Issue by myspivey** [auth0/docs#903]
Update docs/articles/server-apis/java-spring-security.md to show how to integrate with Spring Security 4.0. Currently using old version 0.2 release. Latest is 0.3. This goes inline with the following issues, 
#892
#893

**Comment by mpaktiti** [comment]
Library has been updated, awaiting publication to Maven:
- https://github.com/auth0/auth0-spring-security-mvc 0.2.0 -> 1.0.0

**Comment by mpaktiti** [comment]
The Java Spring Security API doc and sample, use the latest version of `auth0-spring-security-api` library (0.3): http://mvnrepository.com/artifact/com.auth0/auth0-spring-security-api
