### ISSUE TITLE
Auth0.WindowsPhone package not working with .Net Frameworks 3.5 and 4

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#91]
Running "Install-Package Auth0.WindowsPhone" in an application with .NET Framework 3.5 or 4 throws installation error.

![2015-06-06_2310](https://cloud.githubusercontent.com/assets/12707130/8022462/4a316062-0ca1-11e5-9787-f3b63a170d5b.png)

**Comment by jerriep** [comment]
@jose-e-rodriguez Yes, that package is meant for a Windows Phone application. You cannot install it in a web application.

Please see out web application quickstarts for assistance on how to use Auth0 in a web app:
https://auth0.com/docs/quickstart/webapp
