### ISSUE TITLE
iOS Swift Tutorial - XCode Screenshot Outdated

### ISSUE THREAD

**Issue by aguerere** [auth0/docs#911]
The screenshot on step 3 of the iOS Swift tutorial, about configuring the auth0 URL Type should be updated with this, corresponding to XCode 7.2.1 .

![xcode7-url-types-screenshot-021616](https://cloud.githubusercontent.com/assets/14084214/13091979/d2b18f4c-d4cf-11e5-98a7-0fdb473e674f.png)

**Comment by iannyanes** [comment]
This issue is not reproducible on the actual quickstart version

**Comment by camimonse** [comment]
This issue is been closed in Jira as well.
