### ISSUE TITLE
iOS Swift Tutorial Lock versions outdated

### ISSUE THREAD

**Issue by aguerere** [auth0/docs#913]
Lock versions indicated in the iOS Swift tutorial (Lock, Lock-Facebook and Lock-Twitter) should be updated to the indicated ones in the respective images below, or newer ones.

![swift-tutorial-lock-version-021616](https://cloud.githubusercontent.com/assets/14084214/13092791/0d6a8e8c-d4d4-11e5-83ec-e7f64c7f7e49.png)
![swift-tutorial-lock-facebook-version-021616](https://cloud.githubusercontent.com/assets/14084214/13092797/10fe635c-d4d4-11e5-9127-5bff68b0a79a.png)
![swift-tutorial-lock-twitter-version-021616](https://cloud.githubusercontent.com/assets/14084214/13092803/18647c8a-d4d4-11e5-9cd9-c1cbb4bbb4f9.png)

**Comment by iannyanes** [comment]
This issue is no longer reproducible on the actual version of the quickstart
