### ISSUE TITLE
Google Apps Identity Providers documentation page is empty.

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#92]
Clicking the link to Google Apps in the Identity Providers supported by Auth0 page (https://auth0.com/docs/identityproviders) sends to an empty documentation page (https://auth0.com/docs/connections/enterprise/google-apps)

![2015-06-07_1606](https://cloud.githubusercontent.com/assets/12707130/8025772/c6536b20-0d2f-11e5-988d-2942a2a96297.png)
![2015-06-07_1605](https://cloud.githubusercontent.com/assets/12707130/8025773/c655495e-0d2f-11e5-868d-f64bc12e87cd.png)

**Comment by mpaktiti** [comment]
The link has been removed but we are still missing this document. A request is registered and assigned to the docs team.

This issue will be closed since it's a duplicate.
