### ISSUE TITLE
Lock docs shows old version

### ISSUE THREAD

**Issue by jerriep** [auth0/docs#928]
https://auth0.com/docs/libraries/lock

<img width="367" alt="install" src="https://cloud.githubusercontent.com/assets/1006420/13143130/5aee192e-d607-11e5-9a99-16122a9a7db4.png">

**Comment by mpaktiti** [comment]
It has been fixed. 

![image](https://cloud.githubusercontent.com/assets/11715799/15114132/1db031b6-1601-11e6-8b8d-4fc433215c39.png)
