### ISSUE TITLE
Old image on Azure Service Bus tutorial

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#929]
On the Service Bus tutorial it looks like this:
![oldportal](https://cloud.githubusercontent.com/assets/5016479/13147077/e5e5bba0-d629-11e5-899e-d399cc91dc5d.JPG)

But currently it looks like this:
![new2](https://cloud.githubusercontent.com/assets/5016479/13147138/3ee4cf84-d62a-11e5-82e6-16b2f57224c5.JPG)

**Comment by iannyanes** [comment]
Out of scope - private repo.
