### ISSUE TITLE
IP Address Authentication Identity Providers documentation page is empty

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#93]
Clicking the link to IP Address Authentication in the Identity Providers supported by Auth0 page (https://auth0.com/docs/identityproviders) sends to an empty documentation page (https://auth0.com/docs/connections/enterprise/ip-address)

![2015-06-07_1613](https://cloud.githubusercontent.com/assets/12707130/8025798/6df59966-0d30-11e5-932c-ce65d12dba46.png)
![2015-06-07_1612](https://cloud.githubusercontent.com/assets/12707130/8025797/6df2cc9a-0d30-11e5-80ed-ef8043bdbf8e.png)

**Comment by mpaktiti** [comment]
The link has been removed but we are still missing this document. A request is registered and assigned to the docs team.

This issue will be closed since it's a duplicate.
