### ISSUE TITLE
No usage section on Windows Azure Mobile Services Addon Tutorial

### ISSUE THREAD

**Issue by Annyv2** [auth0/docs#930]
As can be seen in the image, there is no "usage" section, and therefore finding the right API_TYPE, which is 'wams' is not that straight forward.
![wams](https://cloud.githubusercontent.com/assets/5016479/13157171/902491c6-d658-11e5-9dc9-5749c93bdfa4.JPG)

**Comment by iannyanes** [comment]
Out of scope. Internal repository.
