### ISSUE TITLE
LDAP Identity Providers documentation page is empty

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#94]
Clicking the link to LDAP in the Identity Providers supported by Auth0 page (https://auth0.com/docs/identityproviders) sends to an empty documentation page (https://auth0.com/docs/connections/enterprise/ldap)

![2015-06-07_1619](https://cloud.githubusercontent.com/assets/12707130/8025810/1947afac-0d31-11e5-8b29-1d69e111585d.png)
![2015-06-07_1618](https://cloud.githubusercontent.com/assets/12707130/8025811/19487e82-0d31-11e5-9581-dc4e52b8da3d.png)

**Comment by ntotten** [comment]
Should link to connector, need metadata option for redirect.

**Comment by mpaktiti** [comment]
The link has been removed but we are still missing this document. A request is registered and assigned to the docs team.

This issue will be closed since it's a duplicate.
