### ISSUE TITLE
OWIN webapi quickstart package reference does not exit in nuget

### ISSUE THREAD

**Issue by azizbodal** [auth0/docs#9401]
The Auth0.OpenIdConnectSigningKeyResolver package does not exist in nuget.  The guide should either have a code snippet or refer to https://github.com/auth0/auth0-aspnet-owin/tree/master/src/Auth0.Owin.OpenIdConnectSigningKeyResolver.

**Comment by frederikprijck** [comment]
Hey @azizbodal ,

Sorry for this, I have updated the quickstart here https://github.com/auth0/docs/pull/9465. It should be removed from the quickstart and contain snippets to include the same functionality without that package.

Please note that the link you refer to is from an archived repository, which has been removed for security reasons mentioned here: https://github.com/auth0/auth0-aspnet-owin/blob/master/SECURITY-NOTICE.md.

**Comment by azizbodal** [comment]
Awesome. Great! Thank you.
