### ISSUE TITLE
NancyFX seed project exception

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#946]
Related to [this repository](https://github.com/auth0/Auth0.NancyFx.SelfHost)
I've tried to run seed project and got `System.NullReferenceException: Object reference not set to an instance of an object.` when should be redirected to `"securepage"`. 
![screenshot_6](https://cloud.githubusercontent.com/assets/1114365/13229216/7689599c-d9a8-11e5-8df8-5b6b8b65e280.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/1114365/13229215/76863244-d9a8-11e5-8461-3a68f2d6c321.png)

**Comment by iannyanes** [comment]
Solved
