### ISSUE TITLE
PingFederate Identity Providers documentation page is empty

### ISSUE THREAD

**Issue by jose-e-rodriguez** [auth0/docs#95]
Clicking the link to PingFederate in the Identity Providers supported by Auth0 page (https://auth0.com/docs/identityproviders) sends to an empty documentation page (https://auth0.com/docs/connections/enterprise/ping-federate)

![2015-06-07_1623](https://cloud.githubusercontent.com/assets/12707130/8025835/b616bd6e-0d31-11e5-8982-368b4eeaf4de.png)
![2015-06-07_1622](https://cloud.githubusercontent.com/assets/12707130/8025836/b61a1248-0d31-11e5-8f4c-b24be6dcd545.png)

**Comment by Catografix** [comment]
@ntotten I will need a PingFederate account to access the api to create the tutorial and take screenshots. Does anyone have an account I could use your should I request one from them (Its not a simple sign-up form).

**Comment by Catografix** [comment]
@ntotten I signed up for the free developer account, and looked around, but I'm pretty sure I dont have the know-how to create this doc from scratch.

**Comment by mpaktiti** [comment]
The link has been removed but we are still missing this document. A request is registered and assigned to the docs team.

This issue will be closed since it's a duplicate.
