### ISSUE TITLE
Authorize Interactive API doesn't let me change redirect_url

### ISSUE THREAD

**Issue by mgonto** [auth0/docs#954]
It'd be great if I can change redirect_uri :)

**Comment by mpaktiti** [comment]
I think this was about the old Authentication API explorer, the new one uses the [Authentication API Debugger Extension](https://auth0.com/docs/extensions/authentication-api-debugger). The Callback URL still cannot be changed, instead the client settings should be updated with the Debugger URL. 

If this is not the case and you meant something else please reopen this.
