### ISSUE TITLE
Missink link for upsertable properties

### ISSUE THREAD

**Issue by avinesse** [auth0/docs#9549]
The page concerning Bulk User Imports (https://auth0.com/docs/users/bulk-user-imports) has missing link.
The upsert parameter description ends with : `For a list of user profile fields that can be upserted during import.` but fails to provide the list.  
It should provide a link to this page : https://auth0.com/docs/users/user-profile-structure#user-profile-attributes

![image](https://user-images.githubusercontent.com/9652897/103556095-8c013780-4eb1-11eb-96e9-468567aa267e.png)

**Comment by rkhoriander** [comment]
Hi, @avinesse. We've added the missing link (and it should be on production in about 15 minutes). Thanks so much for your feedback!
