### ISSUE TITLE
Authorization flow sequence diagram links are broken

### ISSUE THREAD

**Issue by mark-drummond** [auth0/docs#9606]
Links to sequence diagrams for at least some (auth code, client creds) authz flows are broken:

https://auth0.com/docs/flows/authorization-code-flow

https://auth0.com/docs/flows/client-credentials-flow

**Comment by davidpatrick** [comment]
Hey @mark-drummond the diagrams seem to be rendering fine, possibly a network error?  Are you still unable to see the diagrams?

**Comment by mark-drummond** [comment]
Issue was on my end. DuckDuckGo privacy plugin in Chrome was blocking `images.ctfassets.net` where the images are stored. All good!
