### ISSUE TITLE
ServiceStack wrong snippet

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#969]
In step 3 used the wrong snippet, probably need to use [setup.md](https://github.com/auth0/docs/blob/master/snippets/server-platforms/servicestack/setup.md)
![image](https://cloud.githubusercontent.com/assets/1114365/13366863/a40f9796-dce6-11e5-829d-54adf632f77b.png)

**Comment by Annyv2** [comment]
This was solved

**Comment by iannyanes** [comment]
Solved
