### ISSUE TITLE
ServiceStack invalid code

### ISSUE THREAD

**Issue by vmartynets** [auth0/docs#972]
After following the steps, got issue related to this snippet. 
Signature of this function should be `public object Run(Hello request)`.
![image](https://cloud.githubusercontent.com/assets/1114365/13367085/3d34d228-dce8-11e5-9fc4-49c7408ba3dd.png)
![screenshot_8](https://cloud.githubusercontent.com/assets/1114365/13367131/ae177d9c-dce8-11e5-8a0c-cef9e9a3ae25.png)

**Comment by iannyanes** [comment]
Solved
