### ISSUE TITLE
Nested lists always have a number when they souldn't in ADFS doc

### ISSUE THREAD

**Issue by benoittgt** [auth0/docs#9941]
Hello

[On documentation about ADFS connection](https://auth0.com/docs/connections/enterprise/adfs#add-additional-ldap-attributes) we can see:

![Screenshot 2021-12-03 at 11 25 46](https://user-images.githubusercontent.com/8417720/144587290-f388793d-05f8-4321-a487-a264d4ab6f6a.png)

But it makes the two options unclear. They should not be numbered. Markdown looks ok: https://github.com/auth0/docs/blob/master/articles/connections/enterprise/adfs.md#add-additional-ldap-attributes

Also a weird thing is on other documentation we can see the same syntax and we do not have the issue.

<img width="1132" alt="Screenshot 2021-12-03 at 11 31 13" src="https://user-images.githubusercontent.com/8417720/144588008-1a56dbcf-c2a8-4d00-bb03-b591ec33d723.png">

![Screenshot 2021-12-03 at 11 32 16](https://user-images.githubusercontent.com/8417720/144588080-9a49a324-c55d-4047-b4a5-b26cad5d729a.png)

**Comment by rkhoriander** [comment]
We moved our docs to a new CMS, so the markdown no longer reflects the page content. I have corrected this in the page content, and it will be published on our site in about 20 minutes. Thanks!
